#!/bin/sh
# Copyright (C) 2006 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

initramfs_test() {
	if [ -n "$INITRAMFS" ]; then
		boot_run_hook initramfs
        mount -t ext4 /dev/sda2 /overlay
		preinit_ip_deconfig
		break
	fi
}

boot_hook_add preinit_main initramfs_test
