#!/bin/sh

. /lib/ar71xx.sh

do_load_ath10k_board_bin() {
    local board=$(ar71xx_board_name)
    local model=$(ar71xx_model)
    local mtdblock=$(find_mtd_part art)

    [ -n "$mtdblock" ] || return

    local dir="/lib/firmware/ath10k/QCA988X/hw2.0"
    local cal_data_path="/tmp"

    # load board.bin
    case "$board" in
        ap152 | unifi)
            if [ "$model" = "WL8200-I2" -o "$model" = "A920" -o "$model" = "A923" ]
            then
                size=12064
                mkdir -p ${dir}
                dd if=${mtdblock} of=${dir}/board.bin \
                    bs=1 skip=20480 count=$size
                mkdir -p ${cal_data_path}
                base_mac="$(cat /sys/class/net/eth0/address)"
                mac="${base_mac%:*}:`printf "%02x" $((0x${base_mac##*:} + 8))`"
                dd if=${mtdblock} of=${cal_data_path}/wifi0.caldata bs=32 count=34 skip=128
                dd if=${mtdblock} of=${cal_data_path}/wifi1.caldata bs=32 count=377 skip=640
                (cd /tmp;/lib/wifi/convert.py $mac $size)
            else
                size=2116
                mkdir -p ${dir}
                dd if=${mtdblock} of=${dir}/board.bin \
                    bs=1 skip=20480 count=$size
                mkdir -p ${cal_data_path}
                base_mac="$(cat /sys/class/net/eth0/address)"
                mac="${base_mac%:*}:`printf "%02x" $((0x${base_mac##*:} + 8))`"
                dd if=${mtdblock} of=${cal_data_path}/wifi0.caldata bs=32 count=34 skip=128
                dd if=${mtdblock} of=${cal_data_path}/wifi1.caldata bs=1 count=$size skip=20480
                (cd /tmp;/lib/wifi/convert.py $mac $size)
            fi
            ;;
        ap147 | ap151 | ap135 | ap137)
            if [ "$model" = "W282" -o "$model" = "A750" ]
            then
                size=2116
                mkdir -p ${cal_data_path}
                base_mac="$(cat /sys/class/net/eth0/address)"
                mac="${base_mac%:*}:`printf "%02x" $((0x${base_mac##*:} + 8))`"
                dd if=${mtdblock} of=${cal_data_path}/wifi0.caldata bs=32 count=34 skip=128
                dd if=${mtdblock} of=${cal_data_path}/wifi1.caldata bs=1 count=$size skip=20480
                (cd /tmp;/lib/wifi/convert.py $mac $size)
            else
                mkdir -p ${cal_data_path}
                dd if=${mtdblock} of=${cal_data_path}/wifi0.caldata bs=32 count=377 skip=128
                dd if=${mtdblock} of=${cal_data_path}/wifi1.caldata bs=32 count=377 skip=640
            fi
            ;;
        *)
            echo "Support to copy caldata is not there for $board"
            ;;
    esac
}

boot_hook_add preinit_main do_load_ath10k_board_bin
