IBOBJS = util.o add.o  blob.o cfg_version.o \
		 cli.o  delta.o  file.o libcfg.o  \
		 list.o  parse.o  util.o



SHLIB = libcfg.so.1.0

EXTRA_CFLAGS +=
EXTRA_LDFLAGS +=

include $(TOPDIR)/package_repos/build/okpost.mk
