#!/bin/sh

case "$1" in
    list)   
        echo '{ "bar": { "arg1": true, "arg2": 32, "arg3": "str" }, "toto": { } }'
        ;;
    call)   
        case "$2" in
            bar)
                # read the arguments
                read input;

                # optionally log the call
                logger -t "foo" "call" "$2" "$input"

                # return json object or an array
                echo '{ "hello": "world" }'
                ;;
            toto)   
                # return json object or an array
                #echo '[ "item1", "item2", "item3" ]'
                echo '{ "hello": "world" }'         
                ;;                                 
        esac      
        ;;          
esac   
