#!/bin/sh

case "$1" in
	list)
		echo '{ "bar": { "arg1": true, "arg2": 32, "arg3": "str" }, "toto": { }, "failme": {} }'
	;;
	call)
		case "$2" in
			bar)
				# read the arguments
				read input;

				# optionally log the call
				logger -t "foo" "call" "$2" "$input"

				# return json object or an array
				echo '{ "hello": "world" }'
			;;
			toto)
				# return json object
				echo '{ "something": "somevalue" }'
			;;
                        failme)
                                # return invalid
                                echo '{asdf/3454'
                        ;;
		esac
	;;
esac

