#!/bin/sh
[ -f /etc/banner ] && cat /etc/banner

export PATH=/bin:/sbin:/usr/bin:/usr/sbin
export HOME=$(grep -e "^${USER:-root}:" /etc/passwd | cut -d ":" -f 6)
export HOME=${HOME:-/root}
export PS1='\[\033[35;1m\]\u\[\033[0m\]@\[\033[31;1m\]\h \[\033[32;1m\]$PWD\[\033[0m\] [\[\033[35m\]\#\[\033[0m\]]\[\033[31m\]\$\[\033[0m\] '

[ -x /bin/more ] || alias more=less
[ -x /usr/bin/vim ] && alias vi=vim || alias vim=vi

[ -z "$KSH_VERSION" -o \! -s /etc/mkshrc ] || . /etc/mkshrc

[ -x /usr/bin/arp ] || arp() { cat /proc/net/arp; }
[ -x /usr/bin/ldd ] || ldd() { LD_TRACE_LOADED_OBJECTS=1 $*; }

# Oakridge added alias
alias iwsta='iwconfig 2>/dev/null | awk '"'"'/ath/{print $1;system("wlanconfig "$1" list");}'"'"
alias iwap='iwconfig 2>/dev/null | awk '"'"'/ath/{print $1;system("wlanconfig "$1" list ap");}'"'"
alias showlog="uci set system.@system[0].conloglevel='8';uci set system.@system[0].klogconloglevel='8';uci set system.@system[0].cronloglevel='8';uci commit system;/etc/init.d/boot restart;logread -f"
alias stoplog="uci set system.@system[0].conloglevel='3';uci set system.@system[0].klogconloglevel='3';uci set system.@system[0].cronloglevel='3';uci commit system;/etc/init.d/boot restart;"
