#ifndef _AH_CMD_S_H
#define _AH_CMD_S_H

#include "ah_net.h"
#include "ah_tlv_msg.h"
#include "ah_mpi.h"
#include <netinet/in.h>

/* Enable/Disable using hidden commands to show password
 * the CLI is:
 *      show ssid xxx _password
 *      show hive xxx _password
 *      show aaa _shared-secret
 */
#define SHOW_PASSWORD_CLIS      0

#define CLI_HLP_TXT_SHOW             "Show settings, parameters, or dynamically generated information\n"
#define CLI_HLP_TXT_INTERFACE        "Set interface parameters\n"
#define CLI_HLP_TXT_SHOW_INTERFACE   "Show interface and subinterface parameters\n"
#define CLI_HLP_TXT_SHOW_AMRP        "Show amrp information\n"
#define CLI_HLP_TXT_IPFW             "Set a Layer 3 firewall policy (Max: 1024 rules per Aerohive device)\n"

#define AH_CLI_PASS_ARRAY_LEN (20)

#define AH_CMD_TYPE_SET 0
#define AH_CMD_TYPE_GET 1
#define AH_CMD_TYPE_UNSET 2
#define AH_CMD_TYPE_EXEC 3

typedef struct {
	ushort      ctx_id;
	ushort      cmd_id;
	ushort      mod_id;
	ushort      sub_mod_id;
	uint      type;
} ah_cmd_cookie_t;

#define PRINT_COOKIE(c) \
	printf(" COOKIE = \n\
{\n\
		ctx_id = %d,\n\
		cmd_id = %d,\n\
		mod_id = %d,\n\
		sub_mod_id = %d,\n\
		type = %d,\n\
}\n", \
		   (c)->ctx_id, (c)->cmd_id, (c)->mod_id, (c)->sub_mod_id,\
		   (c)->type);

typedef struct {
	ah_cmd_cookie_t cookie;
	uint      session;
	int mh;                  /* mpi handle */
	char *data2climod;       /* mpi buffer */
	uint32_t peer_mpi_port;    /* peer mpi port number */
} ah_cmd_handle_t;

#define AH_CMD_TYPE(cmdhandle) (cmdhandle)->cookie.type
#define AH_CMD_ID(handle) (((ah_cmd_cookie_t *)handle)->cmd_id)
typedef int (*ah_cmd_vector_t)(ah_cmd_handle_t *hndl, ah_tlv_t *data, int n);

extern
void ah_reg_cmd_vector(ushort ctxid, ushort cmdid, ah_cmd_vector_t v);



#define ah_cli_get_syserr()   (strerror(errno))



/* CLI context IDs */

#define AH_ALL_CTX 0xffff

enum ah_cli_context_id {
	/*AH_CLI_CTX_TOP,*/ /*delete for user admin CLI*/
	AH_CLI_CTX_ENABLE,
	AH_MAX_CTX_ID
};

/* CLI command IDs */
enum ah_cli_cmd_id {
	AH_CMD_SHOW_CREATE_POLICY1,
	AH_CMD_SHOW_CREATE_POLICY2,
	AH_CMD_SHOW_DELETE_POLICY1,
	AH_CMD_ROUTE_NEXT_HOP,
	AH_CMD_FIB_NEXT_HOP,
	AH_CMD_PROXY,
	AH_CMD_STATION,
	AH_CMD_MESH_ID,
	AH_CMD_MESH_INTERFACE,
	AH_CMD_MESH_LSR,
	AH_CMD_MESH_AGING,
	AH_CMD_MESH_CAL,
	AH_CMD_AMRP_PROBE,
	AH_CMD_AMRP_PROBE_PORTAL,
	AH_CMD_AMRP_STOP_PROBE,
	AH_CMD_AMRP_ETH_IFP_CMD,
	AH_CMD_AMRP_FILTER_CMD,
	AH_CMD_AMRP_NBR_KA_CMD,
	AH_CMD_AMRP_GLOGAL_VAR_CMD,
	AH_CMD_SHOW_FIB,
	AH_CMD_SHOW_ROUTE,
	AH_CMD_SHOW_PROXY,
	AH_CMD_SHOW_AMRP_INFO,
	AH_CMD_SHOW_AMRP_FILTER,
	AH_CMD_SHOW_AMRP_ETHLINK,
	AH_CMD_SHOW_AMRP_ONE_ETHLINK,
	AH_CMD_SHOW_AMRP2_NODE,
	AH_CMD_SHOW_AMRP2_ONE_NODE,
	AH_CMD_SHOW_AMRP2_IFP,
	AH_CMD_SHOW_AMRP2_ONE_IFP,
	AH_CMD_SHOW_AMRP2_IFP_BMT,
	AH_CMD_SHOW_AMRP2_IFP_LML,
	AH_CMD_SHOW_AMRP_TOPO,
	AH_CMD_SHOW_AMRP_SPF,
	AH_CMD_SHOW_AMRP_L3NODE,
	AH_CMD_SHOW_AMRP_IMPORT_STA,
	AH_CMD_SHOW_AMRP_EXPORT_STA,
	AH_CMD_SHOW_AMRP_NODE,
	AH_CMD_SHOW_AMRP_LOCALLINK,
	AH_CMD_SHOW_AMRP_NEIGHBOR,
	AH_CMD_SHOW_AMRP_BEACON_NEIGHBOR,
	AH_CMD_SHOW_AMRP_DNXP_CACHE,
	AH_CMD_SHOW_AMRP_CLIENT,
	AH_CMD_SHOW_AMRP_CLIENT_OWNER,
	AH_CMD_SHOW_AMRP_TUNNEL,
	AH_CMD_SHOW_AMRP_TUNNEL_ROUTE,
	AH_CMD_SHOW_AMRP_BONJOUR,
	AH_CMD_DBG_AMRP_BONJOUR_GATEWAY,
	AH_CMD_DBG_AMRP_CLIENT_OWNER,
	AH_CMD_DBG_AMRP_BASIC,
	AH_CMD_DBG_AMRP_WIFI,
	AH_CMD_DBG_AMRP_ETH,
	AH_CMD_DBG_AMRP_MAC_LEARNING,
	AH_CMD_DBG_AMRP_XNXP,
	AH_CMD_DBG_AMRP_VPN,
	AH_CMD_SHOW_ROAMING,
	AH_CMD_SHOW_NDP_FILTER,
	/* AMRP cmd id at the top */

	AH_CMD_DEBUG,
	AH_CMD_KDEBUG,
	AH_CMD_DEBUG_STOP,

	AH_CMD_ND_FILTER,
	AH_CMD_L3ROAMING_KEEPALIVE_INTERVAL,
	AH_CMD_L3ROAMING_KEEPALIVE_COUNT,
	AH_CMD_WLAN_ENABLE_INTERFACE,
	AH_CMD_WLAN_INTERFACE_MODE,
	AH_CMD_WLAN_INTERFACE_MODE_ETH0,
	AH_CMD_WLAN_INTERFACE_CHANNEL,
	AH_CMD_WLAN_INTERFACE_POWER,
	AH_CMD_WLAN_INTERFACE_RADIO,
	AH_CMD_WLAN_INTERFACE_SSID,
	AH_CMD_WLAN_INTERFACE_HIVE,
	AH_CMD_WLAN_INTERFACE_HIVE_HVI,
	AH_CMD_WLAN_INTERFACE_VLAN,
	AH_CMD_WLAN_INTERFACE_SHUTDOWN,
	AH_CMD_WLAN_INTERFACE_SHOW,
	AH_CMD_WLAN_RADIO,
	AH_CMD_WLAN_RADIO_MODE,
	AH_CMD_WLAN_RADIO_TURBO,
	AH_CMD_WLAN_SHOW_RADIO,
	AH_CMD_WLAN_SSID,
	AH_CMD_WLAN_SSID_VLAN,
	AH_CMD_WLAN_SHOW_SSID,
	AH_CMD_WLAN_HIVE,
	AH_CMD_WLAN_HIVE_VLAN,
	AH_CMD_WLAN_SHOW_HIVE,
	AH_CMD_DCD_RADIO,
	AH_CMD_DCD_RADIO_MODE,
	AH_CMD_DCD_RADIO_TURBO,
	AH_CMD_DCD_RADIO_SPEED,
	AH_CMD_DCD_RADIO_SPEED_AUTO,
	AH_CMD_DCD_RADIO_BEACON_PERIOD,
	AH_CMD_DCD_RADIO_DETECT_BSSID_SPOOFING,
	/* radio profile acsp cmd */
	AH_CMD_DCD_TEST_ACSP_CHANNEL,
	AH_CMD_DCD_ACSP_ALL_CHNL_ENABLE,
	AH_CMD_DCD_ACSP_INTF_SWITCH_CTRL,
	AH_CMD_DCD_ACSP_INTF_SWITCH_CU,
	AH_CMD_DCD_ACSP_INTF_SWITCH_IU,
	AH_CMD_DCD_ACSP_INTF_SWITCH_CRC,
	AH_CMD_DCD_ACSP_BH_HT40_TO_HT20,
	AH_CMD_DCD_SHOW_ACSP_CHANNEL_INFO,
	AH_CMD_DCD_RADIO_MAX_TXPOWER,
	AH_CMD_DCD_RADIO_ACSP_AP_NO_STATION,
	AH_CMD_DCD_RADIO_ACSP_BH_NB_CHANGE,
	AH_CMD_DCD_RADIO_ACSP_BH_NB_TIME,
	AH_CMD_DCD_RADIO_ACSP_AP_SWITCH_CFG,
	AH_CMD_DCD_RADIO_SHOW,
	AH_CMD_DCD_RADIO_BACKHAUL_FAILOVER,
	AH_CMD_DCD_RADIO_SGI,
	AH_CMD_DCD_RADIO_AMPDU,
	AH_CMD_DCD_RADIO_AMPDU_MAXSIZE,
	AH_CMD_DCD_RADIO_AMPDU_MAX_11N_SIZE,
	AH_CMD_DCD_RADIO_AMSDU,
	AH_CMD_DCD_RADIO_TXCHAIN,
	AH_CMD_DCD_RADIO_TXCHAIN_AUTO,
	AH_CMD_DCD_RADIO_RXCHAIN,
	AH_CMD_DCD_RADIO_CHWIDTH,
	AH_CMD_DCD_RADIO_PRIMARY_CHNL_OFFSET,
	AH_CMD_DCD_RADIO_11B_CLIENT,
	AH_CMD_DCD_RADIO_11N_CLIENTS_ONLY,
	AH_CMD_DCD_RADIO_DFS,
	AH_CMD_DCD_RADIO_DFS_NEW,
	AH_CMD_DCD_RADIO_DFS_CHNL_SWITCH,
	AH_CMD_DCD_RADIO_DFS_DETECT_ONLY,
	AH_CMD_DCD_RADIO_DFS_CERT_ENABLE,
	AH_CMD_DCD_SHOW_RADIO_DFS,
	AH_CMD_DCD_RADIO_DENY_CLIENT,
	AH_CMD_DCD_RADIO_ACSP_CHNL_MODE_G3,
	AH_CMD_DCD_RADIO_ACSP_CHNL_MODE_G4,
	AH_CMD_DCD_RADIO_HIGH_DENSITY_ENABLE,
	AH_CMD_DCD_RADIO_HIGH_DENSITY_MGMT_TX_RATE_SET,
	AH_CMD_DCD_RADIO_HIGH_DENSITY_BAND_STEERING_ENABLE,
	AH_CMD_DCD_RADIO_HIGH_DENSITY_CONTINOUS_PROBE_SUPPRESS_ENABLE,
	AH_CMD_DCD_RADIO_HIGH_DENSITY_BROADCAST_PROBE_SUPPRESS_ENABLE,
	AH_CMD_DCD_RADIO_HIGH_DENSITY_BROADCAST_PROBE_SUPPRESS_BY_OUI,
	AH_CMD_DCD_RADIO_HIGH_DENSITY_WEAK_SNR_SUPPRESS_ENABLE,
	AH_CMD_DCD_RADIO_HIGH_DENSITY_CLIENT_LOAD_BALANCE_ENABLE,
	AH_CMD_DCD_RADIO_HIGH_DENSITY_SAFETY_NET_ENABLE,
	AH_CMD_DCD_RADIO_HIGH_DENSITY_CLIENT_LOAD_BALANCE_HOLD_TIME,
	AH_CMD_DCD_RADIO_HIGH_DENSITY_CLIENT_LOAD_BALANCE_STA_AIRTIME_LIMIT,
	AH_CMD_DCD_RADIO_HIGH_DENSITY_CLIENT_LOAD_BALANCE_INTERFERENCE_LIMIT,
	AH_CMD_DCD_RADIO_HIGH_DENSITY_CLIENT_LOAD_BALANCE_CRC_ERROR_LIMIT,
	AH_CMD_DCD_RADIO_HIGH_DENSITY_WEAK_SNR_SUPPRESS_SET_THRESHOLD,
	AH_CMD_DCD_RADIO_HIGH_DENSITY_SAFETY_NET_TIMEOUT,
	AH_CMD_DCD_HDD_LB_TAKE_CLIENT_THRESHOLD,
	AH_CMD_DCD_HDD_STATUS_SHOW,
	AH_CMD_DCD_HDD_5G_LIST_ADD,
	AH_CMD_DCD_HDD_DUMP_STAT,
	AH_CMD_DCD_HDD_DUMP_NT,
	AH_CMD_DCD_HDD_CLEAR_NT,
	AH_CMD_DCD_RADIO_BAND_STEERING_MODE,
	AH_CMD_DCD_BAND_STEERING_BALANCE_RATIO,
	AH_CMD_DCD_BAND_STEERING_PREFER_5G_LIMIT,
	AH_CMD_DCD_RADIO_BALANCE_SUPPRESS_LIMIT,
	AH_CMD_DCD_CLIENT_LOAD_BALANCE_MODE,
	AH_CMD_DCD_BAND_STEER_STATUS_SHOW,
	AH_CMD_DCD_RADIO_BALANCE_STATUS_SHOW,
	AH_CMD_DCD_LOAD_BALANCE_STATUS_SHOW,
	AH_CMD_DCD_RADIO_RADIO_BALANCE_ENABLE,
	AH_CMD_DCD_RADIO_BAND_STEERING_ENABLE,
	AH_CMD_DCD_RADIO_WEAK_SNR_SUPPRESS_ENABLE,
	AH_CMD_DCD_RADIO_WEAK_SNR_SUPPRESS_SET_THRESHOLD,
	AH_CMD_DCD_RADIO_CLIENT_LOAD_BALANCE_ENABLE,
	AH_CMD_DCD_RADIO_SAFETY_NET_ENABLE,
	AH_CMD_DCD_RADIO_SAFETY_NET_TIMEOUT,
	AH_CMD_DCD_RADIO_CLIENT_LOAD_BALANCE_HOLD_TIME,
	AH_CMD_DCD_RADIO_CLIENT_LOAD_BALANCE_STA_AIRTIME_LIMIT,
	AH_CMD_DCD_RADIO_CLIENT_LOAD_BALANCE_INTERFERENCE_LIMIT,
	AH_CMD_DCD_RADIO_CLIENT_LOAD_BALANCE_CRC_ERROR_LIMIT,
	AH_CMD_DCD_RADIO_CLIENT_LOAD_BALANCE_NBR_LOAD_QUERY_INTERVAL,
	AH_CMD_DCD_RADIO_MCAST_HIGH_RATE_SET,
	AH_CMD_DCD_SHOW_BACKHAUL_FAILOVER,
	AH_CMD_DCD_SET_BACKHAUL_FAILOVER_PARAMS,
	AH_CMD_DCD_SSID,
	AH_CMD_DCD_SSID_RTS_THRESHOLD,
	AH_CMD_DCD_SSID_WMM,
	AH_CMD_DCD_SSID_11A_RATESET_SET,
	AH_CMD_DCD_SSID_11G_RATESET_SET,
	AH_CMD_DCD_SSID_11N_RATESET_SET,
	AH_CMD_DCD_SSID_11N_RATESET_SET_EXPAND,
	AH_CMD_DCD_SSID_11AC_RATESET_SET,
	AH_CMD_DCD_SSID_LDPC,
	AH_CMD_DCD_SSID_TX_STBC,
	AH_CMD_DCD_SSID_RX_STBC,
	AH_CMD_DCD_SSID_MAX_CLIENT,
	AH_CMD_DCD_SSID_SHOW,
	AH_CMD_DCD_SSID_ALLOW_ALL_UP,
	AH_CMD_DCD_SSID_DENY_ACT_BAN,
	AH_CMD_DCD_SSID_DENY_ACT_BAN_DISCON,
	AH_CMD_DCD_SSID_MODE,
	AH_CMD_DCD_SSID_COMPLIANCE,
	AH_CMD_DCD_SSID_CLIENT_AGE,
	AH_CMD_DCD_HIVE,
	AH_CMD_DCD_HIVE_VLAN,
	AH_CMD_DCD_HIVE_RTS_THRESHOLD,
	AH_CMD_DCD_HIVE_SHOW,
	AH_CMD_DCD_HIVE_ETH_ENCRYPTION,
	AH_CMD_DCD_IF_MODE,
	AH_CMD_DCD_IF_MODE_ETH0,
	AH_CMD_DCD_IF_MODE_ETH0_SWITCH,
	AH_CMD_DCD_IF_WAN_MODE_ETH0,
	AH_CMD_DCD_IF_WAN_MODE_ETH0_SWITCH,
	AH_CMD_DCD_IF_WAN_NAT_ENABLE,
	AH_CMD_DCD_IF_WAN_NAT_ENABLE_SWITCH,
	AH_CMD_DCD_IF_WAN_PRIORITY,
	AH_CMD_DCD_IF_CHANNEL,
	AH_CMD_DCD_IF_CHANNEL_EXCLUDE,
#ifdef AH_ZWDFS_SUPPORT
	AH_CMD_DCD_IF_ZEROWAIT_DFS,
#endif
	AH_CMD_DCD_IF_POWER,
	AH_CMD_DCD_IF_POWER_AUTO_FLOOR,
	AH_CMD_DCD_IF_POWER_AUTO_MAXDROP,
	AH_CMD_DCD_IF_TPC,
	AH_CMD_DCD_IF_TPC_AUTO,
	AH_CMD_DCD_IF_RADIO,
	AH_CMD_DCD_IF_VAP_SSID,
	AH_CMD_DCD_IF_RADIO_SSID,
	AH_CMD_DCD_IF_HIVE_MGT0,
	AH_CMD_DCD_IF_VLAN_MGT0,
	AH_CMD_DCD_IF_MGTX_Y_IP,
	AH_CMD_DCD_IF_MGTX_Y_IP_SWITCH,
	AH_CMD_DCD_IF_MGTX_Y_VLAN,
	AH_CMD_DCD_IF_MGTX_Y_VLAN_SWITCH,
	AH_CMD_DCD_IF_BANG_RADAR,
#ifdef AH_ZWDFS_SUPPORT
	AH_CMD_DCD_IF_BANG_RADAR_SC,
#endif
	AH_CMD_DCD_VAP_SHUTDOWN,
	AH_CMD_DCD_ETH_SHUTDOWN,
	AH_CMD_DCD_RADIO_SSID_SHUTDOWN,
	AH_CMD_DCD_RADIO_HIVE_SHUTDOWN,
	AH_CMD_DCD_IF_SHOW,
	AH_CMD_DCD_IF_SHOW_SWITCH,
	AH_CMD_DCD_L3_IF_SHOW,
	AH_CMD_DCD_L3_IF_SHOW_ONE,
	AH_CMD_DCD_IF_ETH_SPEED,
	AH_CMD_DCD_IF_ETH_DUPLEX,
	AH_CMD_DCD_IF_ETH_NATIVE_VLAN,
	AH_CMD_DCD_IF_NATIVE_VLAN,
	AH_CMD_DCD_IF_TXRATE_WEIGHT,
	AH_CMD_DCD_IF_SHOW_TXRATE,
	AH_CMD_DCD_IF_PERF_BOOST,
	AH_CMD_DCD_IF_ADAPTIVE_CCA,
	AH_CMD_DCD_IF_ADAPTIVE_CCA_DEFAULT,
	AH_CMD_DCD_IF_ADAPTIVE_CCA_MAX,
	AH_CMD_DCD_IF_TX_AIRTIME,
	AH_CMD_DCD_IF_RX_AIRTIME,
	AH_CMD_DCD_SHOW_IF_DETAIL,
	AH_CMD_DCD_DF,
	AH_CMD_DCD_SHOW_ACTIVE_WEB_DIR,
	AH_CMD_DCD_SYSTEM_MONITOR,
	AH_CMD_DCD_IF_MTU_MGT0,

	/* add for integrated filter */
	AH_CMD_DCD_FILTER_L2,
	AH_CMD_DCD_FILTER_L3,
	AH_CMD_DCD_FILTER_MISC,
	AH_CMD_DCD_FILTER_NO,
	AH_CMD_DCD_FILTER_SHOW,

	/* add for packet capture */
	AH_CMD_DCD_CAPTURE_PARAM_SET,
	AH_CMD_DCD_CAPTURE_START,
	AH_CMD_DCD_CAPTURE_STAT_SHOW,
	AH_CMD_DCD_CAPTURE_LOCAL_SHOW,
	AH_CMD_DCD_CAPTURE_LOCAL_DEL,

	/* add for access console */
	AH_CMD_DCD_AC_NAME,
	AH_CMD_DCD_AC_MODE,
	AH_CMD_DCD_AC_METHOD_OPEN,
	AH_CMD_DCD_AC_METHOD_ENCYPT,
	AH_CMD_DCD_AC_MAC_FILTER,
	AH_CMD_DCD_AC_HIDE_SSID,
	AH_CMD_DCD_AC_TELNET,
	AH_CMD_DCD_AC_MAX_CLIENT,
	AH_CMD_DCD_AC_SHOW,

	AH_CMD_DCD_DF_SHOW,
	AH_CMD_DCD_LB_STATUS,
	AH_CMD_DCD_LB_DATA,

	/* add for wifi statistics */
	AH_CMD_DCD_SHOW_IF_CNT,
	AH_CMD_DCD_SHOW_IF_CNT_DBG,
	AH_CMD_DCD_SHOW_IF_CHAN,
	AH_CMD_DCD_SHOW_SSID_STA_CNT,
	AH_CMD_AUTH_SHOW_CLIENT_DETAIL_INFO,
	AH_CMD_DCD_SHOW_HIVE_NEIGHBOUR_CNT,
	AH_CMD_DCD_CLEAR_IF_CNT,
	AH_CMD_DCD_CLEAR_SSID_STA_CNT,
	AH_CMD_DCD_CLEAR_HIVE_NEIGHBOUR_CNT,
	AH_CMD_DCD_SHOW_IF_TX_POWER_PER_CHAIN,

	/* add for radio background scan */
	AH_CMD_DCD_RADIO_BGSCAN_ENABLE,
	AH_CMD_DCD_RADIO_BGSCAN_INTERVAL,
	AH_CMD_DCD_RADIO_BGSCAN_VOICE_ALLOW,
	AH_CMD_DCD_RADIO_BGSCAN_CTS,
	AH_CMD_DCD_RADIO_BGSCAN_CLIENT,
	AH_CMD_DCD_RADIO_BGSCAN_CLIENT_PS,

	/* add for bandwidth sentinel */
	AH_CMD_DCD_RADIO_BENCHMARK_11A,
	AH_CMD_DCD_RADIO_BENCHMARK_11B,
	AH_CMD_DCD_RADIO_BENCHMARK_11G,
	AH_CMD_DCD_RADIO_BENCHMARK_11N,
	AH_CMD_DCD_RADIO_BENCHMARK_11AC,

	/*add for remote sniffer*/
	AH_CMD_DCD_REMOTE_SNIFFER_ENABLE,
	AH_CMD_DCD_REMOTE_SNIFFER_SHOW,

	/* add for spectral analysis. */
	AH_CMD_DCD_RADIO_SPECTRAL_REPORT_INTERVAL,
	AH_CMD_DCD_RADIO_SPECTRAL_SET_CHANNEL,
	AH_CMD_DCD_SPECTRAL_SCAN_ACTION,
	AH_CMD_DCD_RADIO_SPECTRAL_SCAN_AIRIQ_MODE,
	AH_CMD_DCD_SHOW_IF_SPECTRAL,

	/* Zero-Wait DFS */
#ifdef AH_ZWDFS_SUPPORT
	AH_CMD_DCD_RADIO_ZWDFS_CHANNEL,
#endif

	/*add cmd id for dcd beta */
	AH_CMD_DCD_RADIO_PREAMBLE,
	AH_CMD_DCD_RADIO_MAX_CLIENT,
	AH_CMD_DCD_RADIO_WMM_CWMAX,
	AH_CMD_DCD_RADIO_WMM_CWMIN,
	AH_CMD_DCD_RADIO_WMM_AIFS,
	AH_CMD_DCD_RADIO_WMM_TXOPLIMIT,
	AH_CMD_DCD_RADIO_WMM_NO_ACK,
	AH_CMD_DCD_RADIO_IM_ENABLE,
	AH_CMD_DCD_RADIO_IM_ST_INTVL,
	AH_CMD_DCD_RADIO_IM_CU_THR,
	AH_CMD_DCD_RADIO_IM_CRCERR_THR,
	AH_CMD_DCD_SSID_FRAG_THRESHOLD,
	AH_CMD_DCD_HIVE_FRAG_THRESHOLD,
	AH_CMD_DCD_SSID_HIDE,
	AH_CMD_DCD_SSID_IGNOR_BORDCAST_PROBE,
	AH_CMD_DCD_SSID_DTIM_PERIOD,
	AH_CMD_DCD_RADIO_RANGE,
	AH_CMD_DCD_RADIO_ANTENNA_FIXED,
	AH_CMD_DCD_RADIO_ANTENNA,
	AH_CMD_DCD_RADIO_ANTENNA_DIVERSITY,
	AH_CMD_DCD_SHOW_SSID_STA,
	AH_CMD_DCD_SHOW_SSID_STA_IPV6,
	AH_CMD_DCD_MAC_FILTER,
	AH_CMD_DCD_MAC_FILTER_ENTRY,
	AH_CMD_DCD_MAC_FILTER_OUI,
	AH_CMD_DCD_MAC_FILTER_SHOW,
	AH_CMD_DCD_SSID_MAC_FILTER,
	AH_CMD_DCD_HIVE_MAC_FILTER,
	AH_CMD_DCD_DEBUG_SHOW_MACFILTER,
	AH_CMD_DCD_DEBUG_SHOW_SSID,
	AH_CMD_DCD_DEBUG_SHOW_INTERFACE,
	AH_CMD_DCD_WIFIXY_IPADDR,
	AH_CMD_DCD_SEND_MIC_FAIL,
	/* for tx beamforming */
	AH_CMD_DCD_RADIO_TXBF,
	AH_CMD_DCD_RADIO_VHT2G_MODE,
	AH_CMD_DCD_RADIO_FRAMEBURST,
	AH_CMD_DCD_RADIO_MU_MIMO,
	AH_CMD_DCD_RADIO_MU_MIMO_STA_RXCHAIN,
	AH_CMD_DCD_RADIO_MU_SOUNDING_INTERVAL,
#ifdef AH_SUPPORT_SAS
	AH_CMD_DCD_RADIO_SAS,
#endif

	/* DCD CMD for PSE controller (Branch Router) */
	AH_CMD_DCD_PSE_SHOW_PORT_INFO,
	AH_CMD_DCD_PSE_SHUTDOWN_PORT,
	AH_CMD_DCD_PSE_SET_PORT_POWER_MODE,
	AH_CMD_DCD_PSE_SET_PORT_POWER_THRESHOLD_TYPE_CLASS,
	AH_CMD_DCD_PSE_SET_PORT_POWER_THRESHOLD_TYPE_USER,
	AH_CMD_DCD_PSE_UPDATE_FIRMWARE,
	AH_CMD_DCD_PSE_SET_PORT_PRIORITY,
	AH_CMD_DCD_PSE_RESET_PORT,
	AH_CMD_DCD_PSE_SHOW_SYSTEM_INFO,
	AH_CMD_DCD_PSE_SET_MAX_POWER_SOURCE,
	AH_CMD_DCD_PSE_RESET_SYSTEM,
	AH_CMD_DCD_PSE_CMD,
	AH_CMD_DCD_PSE_TIMER_CTL,
	AH_CMD_DCD_PSE_ENABLE_SYSTEM,
	AH_CMD_DCD_PSE_ENABLE_PRIORITY,
	AH_CMD_DCD_PSE_SET_POWER_MGT_TYPE,
	AH_CMD_DCD_PSE_SET_LEGACY_ENABLE,
	AH_CMD_DCD_PSE_SET_GUARD_BAND,
	AH_CMD_DCD_PSE_SET_PROFILE,
	AH_CMD_DCD_PSE_SET_PROFILE_TO_PORT,
	AH_CMD_DCD_PSE_SHOW_TECH_DATA,
	AH_CMD_DCD_PSE_SHOW_HW_DATA,
#if defined(AH_SUPPORT_PSE_LLDP)
	AH_CMD_DCD_PSE_SET_PRIORITY_LLDP_ENABLE,
#endif
	AH_CMD_SWD_PSE_SET_HW_DATA,
	AH_CMD_SWD_PSE_SET_PROFILE_PRIORITY,
	AH_CMD_SWD_PSE_SET_PROFILE_POWERMODE_THRESHOLD ,
	AH_CMD_SWD_IF_SA_SET,
	AH_CMD_SWD_IF_SA_SHOW,
	AH_CMD_SWD_SA_MAC_SHOW,

	/* for show system power */
	AH_CMD_DCD_SHOW_SYSTEM_POWER,
	AH_CMD_DCD_SHOW_SYSTEM_POWER_STATUS,

	/* for show radio key mapping */
	AH_CMD_DCD_DUMP_KEYMAP,
	/*#Add for outdoor*/
	AH_CMD_DCD_ENVIROMENT,
	/* for multicast enhancement */
	AH_CMD_DCD_SSID_MCAST_CONV_MODE,
	AH_CMD_DCD_SSID_MCAST_CONV_CU_THRESHOLD,
	AH_CMD_DCD_SSID_MCAST_CONV_MEMBER_THRESHOLD,
	AH_CMD_DCD_CLI_SHOW_SSID_MCAST_CONV,
	AH_CMD_DCD_SHOW_MCAST_GROUP,
	AH_CMD_DCD_RADIO_SHOW_MCAST_GROUP,
	/* for kdump feature contained DCD module. */
	AH_CMD_KDUMP_GEN_RANDOM,
	AH_CMD_KDUMP_CRASH,
	AH_CMD_KDUMP_LIST,
	AH_CMD_KDUMP_CLEAR_DUMP,
	AH_CMD_KDUMP_CLEAR_ALL_DUMP,

	AH_CMD_SSID_WLAN_DOS,
	AH_CMD_SSID_WLAN_DOS_THRESHOLD,
	AH_CMD_SSID_WLAN_DOS_ALARM,
	AH_CMD_SSID_WLAN_DOS_BAN,
	AH_CMD_SSID_WLAN_DOS_BAN_FOREVER,
	AH_CMD_SHOW_SSID_WLAN_DOS,
	AH_CMD_HIVE_WLAN_DOS,
	AH_CMD_HIVE_WLAN_DOS_THRESHOLD,
	AH_CMD_HIVE_WLAN_DOS_ALARM,
	AH_CMD_HIVE_WLAN_DOS_BAN,
	AH_CMD_HIVE_WLAN_DOS_BAN_FOREVER,
	AH_CMD_SHOW_HIVE_WLAN_DOS,
	AH_CMD_SYSTEM_DOS_ENABLE,
	AH_CMD_SYSTEM_DOS_FILTER,
	AH_CMD_SHOW_SYSTEM_DOS,
	AH_CMD_SHOW_SYSTEM_DOS_BANLIST,

	AH_CMD_SSID_SCREEN_THR,
	AH_CMD_SSID_SCREEN_ACT_TIME,
	AH_CMD_SSID_SCREEN_ACT_BANFOREVER,
	AH_CMD_SSID_SCREEN_ACT_DISCONNECT,
	AH_CMD_SSID_SCREEN_ACT_QUARANTINE,
	AH_CMD_SSID_SCREEN_ACT_TIME_THR,
	AH_CMD_SSID_SCREEN_ACT_BANFOREVER_THR,
	AH_CMD_SSID_SCREEN_ACT_DISCONNECT_THR,
	AH_CMD_SSID_SCREEN_ACT_QUARANTINE_THR,
	AH_CMD_SSID_SCREEN_SHOW,
	AH_CMD_SSID_SCREEN_RADIUS_DOS,
	AH_CMD_SSID_SCREEN_RADIUS_DOS2,
	AH_CMD_SSID_SCREEN_RADIUS_DOS3,
	AH_CMD_SSID_SCREEN_RADIUS_DOS4,
	AH_CMD_SSID_SCREEN_RADIUS_DOS5,
	AH_CMD_SSID_SCREEN_TCP_SYN_CHK,
	AH_CMD_SSID_WEB_SERVER,
	AH_CMD_SSID_WEB_SERVER_SSL_PORT,
	AH_CMD_SSID_WEB_PAGE_CUSTOMIZE,
	AH_CMD_SSID_NO_WEB_PAGE_CUSTOMIZE_OPT,
	AH_CMD_SSID_WEB_FOLDER,
	AH_CMD_SSID_SHOW_WEB_SERVER,
	AH_CMD_DCD_RESET_ALL_SSID_WEBDIR,
	AH_CMD_SSID_WEB_SERVER_NO_SSL,
	AH_CMD_SSID_WEB_SERVER_NO_PORT,
	AH_CMD_SSID_WEB_SERVER_NO_TOTAL_CON,
	AH_CMD_SSID_WEB_SERVER_NO_PERIP_CON,
	AH_CMD_DCD_WEB_SRV_KEY_COMMENT,
	AH_CMD_DCD_SSID_STA_TRANFFIC,
	AH_CMD_DCD_SSID_BLOCK_MCAST,
	AH_CMD_DCD_IF_STA_TRANFFIC,
	AH_CMD_DCD_ETH_ALLOW_VLAN,
	AH_CMD_DCD_ETH_ALLOW_VLAN_ID,
	AH_CMD_DCD_ETH_ALLOW_VLAN_SHOW,
	AH_CMD_ETH_BYPASS_AUTH_VLAN,
	AH_CMD_ETH_BYPASS_AUTH_VLAN_SHOW,

	/* added for IDP rogue AP detection */
	AH_CMD_DCD_IDP_PROFILE,
	AH_CMD_DCD_IDP_IF_BIND,
	AH_CMD_DCD_IDP_PROFILE_SHOW,
	AH_CMD_DCD_IDP_INFO_SHOW,
	AH_CMD_DCD_IDP_AP_INFO_SHOW,
	AH_CMD_DCD_IDP_AP_TYPE_INFO_SHOW,
	AH_CMD_DCD_IDP_AP_COMPLIANT_INFO_SHOW,
	AH_CMD_DCD_IDP_CLIENT_INFO_SHOW,
	AH_CMD_DCD_IDP_AP_ENABLE,
	AH_CMD_DCD_IDP_AP_BSSIDOUI_ENABLE,
	AH_CMD_DCD_IDP_AP_BSSIDOUI_ADD,
	AH_CMD_DCD_IDP_AP_SSID_ENABLE,
	AH_CMD_DCD_IDP_AP_SSID_ADD,
	AH_CMD_DCD_IDP_AP_SSID_ENCRYPT_ENABLE,
	AH_CMD_DCD_IDP_AP_SSID_ENCRYPT_DEFINE,
	AH_CMD_DCD_IDP_AP_SHORT_PREAMBLE_ENABLE,
	AH_CMD_DCD_IDP_AP_SHORT_BEACON_ENABLE,
	AH_CMD_DCD_IDP_AP_WMM_ENABLE,
	AH_CMD_DCD_IDP_ADHOC_ENABLE,
	AH_CMD_DCD_IDP_IND_ENABLE,
	AH_CMD_DCD_IDP_IND_BMT_ADJMAC_ENABLE,    //bmt-adjmac
	AH_CMD_DCD_IDP_IND_BMT_CLIENT_ENABLE,    //bmt-client
	AH_CMD_DCD_IDP_IND_VLAN_ADD,
	AH_CMD_DCD_IDP_MITIGATE_INTERVAL,
	AH_CMD_DCD_IDP_MITIGATE_DURATION,
	AH_CMD_DCD_IDP_MITIGATE_ACTION,
	AH_CMD_DCD_IDP_MITIGATE_ACTION2,
	AH_CMD_DCD_IDP_MITIGATE_ACTION3,
	AH_CMD_DCD_IDP_STA_REPORT_INTV,
	AH_CMD_DCD_IDP_STA_REPORT,
	AH_CMD_DCD_IDP_STA_REPORT_AGE_TIME,
	AH_CMD_DCD_IDP_MITIGATE_CLEAR_AP,
	AH_CMD_DCD_IDP_MITIGATE_SHOW_AP,
	AH_CMD_DCD_IDP_MITIGATE_MAX_DEAUTH,
	AH_CMD_DCD_IDP_IGNORE_CAPWAP,
	AH_CMD_DCD_IDP_MITIGATE_TOLERANCE,
	AH_CMD_DCD_IDP_MITIGATE_MODE,
	AH_CMD_DCD_IDP_MITIGATE_MODE_ACTION,
	AH_CMD_DCD_IDP_MITIGATE_DETECTOR_NUM,
	AH_CMD_DCD_IDP_MITIGATE_INNET,
	AH_CMD_DCD_IDP_MITIGATE_SHOW_HIVE,
	AH_CMD_DCD_IDP_MITIGATE_CLEAR_HIVE,

	AH_CMD_DCD_ETHX_BIND_2RED,
	AH_CMD_DCD_ETHX_BIND_2AGG,
	AH_CMD_LED_SET_COLOR,
	AH_CMD_LED_SET_BUTTON,
	AH_CMD_LED_SHOW_SYSTEM,
	AH_CMD_LED_BRIGHTNESS,
#ifdef CONFIG_AP1130
	AH_CMD_LED_SET_LOCATION,
#elif AH_PLATFORM == AH_PLATFORM_BRCM1
	AH_CMD_LED_SHOW_POWER_SAVING_MODE,
	AH_CMD_SYSTEM_LED_SET_POWER_SAVING_MODE,
#endif
	AH_CMD_PRESS_RESET_BUTTON,
	/* added for HW test purpose */
	AH_CMD_DCD_TEST_CONT_TX,
	AH_CMD_DCD_TEST_RX_ONLY,
	AH_CMD_DCD_TEST_WIFI_SUMMARY,
	AH_CMD_DCD_TEST_STATION_SUMMARY,
	AH_CMD_DCD_SMART_POE,
	AH_CMD_DCD_SMART_POE_TEST,
	AH_CMD_DCD_SMART_POE_SHOW_AMPDU,

	AH_CMD_DCD_SHOW_HIVE_NEIGHBOUR,
	AH_CMD_DCDAUTH_SHOW_SUITE,
	AH_CMD_DCDAUTH_SHOW_SUITE_ALL,
	AH_CMD_DCDAUTH_SHOW_SUITE_ONE,
	AH_CMD_DCDAUTH_SUITEMETHOD_OPEN,
	AH_CMD_DCDAUTH_SUITEMETHOD_WPAAUTOPSK,
	AH_CMD_DCDAUTH_SUITEMETHOD_WPAPSKTKIP,
	AH_CMD_DCDAUTH_SUITEMETHOD_WPAPSKAES,
	AH_CMD_DCDAUTH_SUITEMETHOD_WPA2PSKTKIP,
	AH_CMD_DCDAUTH_SUITEMETHOD_WPA2PSKAES,
	AH_CMD_DCDAUTH_SUITEMETHOD_DOT1XAUTOWPA,
	AH_CMD_DCDAUTH_SUITEMETHOD_DOT1XWPATKIP,
	AH_CMD_DCDAUTH_SUITEMETHOD_DOT1XWPAAES,
	AH_CMD_DCDAUTH_SUITEMETHOD_DOT1XWPA2TKIP,
	AH_CMD_DCDAUTH_SUITEMETHOD_DOT1XWPA2AES,
	AH_CMD_DCDAUTH_SUITEMETHOD_DYNWEP40,
	AH_CMD_DCDAUTH_SUITEMETHOD_DYNWEP104,
	AH_CMD_DCDAUTH_SET_PREAUTH,
	AH_CMD_DCDAUTH_SUITEMETHOD_WEPPSK,
	AH_CMD_DCDAUTH_SUITEMETHOD_WEPPSKOPEN,
	AH_CMD_DCDAUTH_SUITEMETHOD_WALLED_GARDEN_IP,
	AH_CMD_DCDAUTH_SUITEMETHOD_WALLED_GARDEN_HOST,
	AH_CMD_DCDAUTH_SUITEMETHOD_WALLED_GARDEN_IP_SVC,
	AH_CMD_DCDAUTH_SUITEMETHOD_WALLED_GARDEN_HOST_SVC,
	AH_CMD_DCDAUTH_SUITEMETHOD_SHOW_WALLED_GARDEN,
	AH_CMD_DCDAUTH_SUITEMETHOD_SHOW_CWP,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_TIMER_DISP_REMIND,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_LOGIN_PAGE_METHOD,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_DISP_INTERNAL_PAGE,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_SUCCESS_REDIR_ORI,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_SUCCESS_REDIR_EXT,
    AH_CMD_DCDAUTH_SUITEMETHOD_CWP_LOGOUT_REDIR_EXT,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_FAIL_REDIR_LOGIN,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_FAIL_REDIR_EXT,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_NO_SUCCESS_REDIR_DELAY,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_NO_FAILURE_REDIR_DELAY,
	AH_CMD_DCDAUTH_NO_DOT1XWPA2AES_PROACTIVE,
	AH_CMD_DCDAUTH_NO_DOT1XWPA2TKIP_PROACTIVE,
	AH_CMD_DCDAUTH_NO_DOT1XWPA2AUTO_PROACTIVE,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_AUTH_MODE,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_LOCAL,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_PASS_THRU_VLAN,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_REDIR,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_CHECK_USEPOLICY4AUTH,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_EXTERNAL_LOGIN_URL,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_EXTERNAL_PWD,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_EXTERNAL_PWD_SHARED,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_EXTERNAL_MACAUTH_OPT,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_AA,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_REPORT_GUEST_INFO,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_IDM_SELF_REG,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_IDM_SELF_REG_API,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_IDM_SELF_REG_CRL,
	AH_CMD_DCDAUTH_SUITEMETHOD_ATTACH_MAC_WHITE_LIST,
	AH_CMD_DCDAUTH_SUITEMETHOD_MAC_WHITE_LIST_CWP_BYPASS_ENABLE,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_WISPR_BYPASS,
	AH_CMD_DCDAUTH_LOC_TKIP_CNT_MEASURE,
	AH_CMD_DCDAUTH_RMT_TKIP_CNT_MEASURE,
	AH_CMD_DCDAUTH_REPLAY_WINDOW,
	AH_CMD_DCDAUTH_8021X_REAUTH_ITV,

	AH_CMD_DCDAUTH_PSK_PER_USER,
	AH_CMD_DCDAUTH_PSK_PER_USER_HEX,
	AH_CMD_DCDAUTH_PSK_CONCATENATED_CHARS,
	AH_CMD_DCDAUTH_PSK_CHAR_PATTERN,
	AH_CMD_DCDAUTH_PU_COMBO_PATTERN,
	AH_CMD_DCDAUTH_PU_RADIUS_AUTH,
	AH_CMD_DCDAUTH_PU_EXEC_PSK2PMK,
	AH_CMD_DCDAUTH_PU_AUTO_SAVE,
	AH_CMD_DCDAUTH_PU_SAVE_BY_SSID,
	AH_CMD_DCDAUTH_NO_PU_INDEX,
	AH_CMD_DCDAUTH_SHOW_PU_PSK_FORMAT,
	AH_CMD_DCDAUTH_PSK_PER_USER_DYN,
	AH_CMD_DCDAUTH_PSK_PER_USER_DYN_SCH,
	AH_CMD_DCDAUTH_SHOW_PU_ENTRY,
	AH_CMD_DCDAUTH_SAVE_PU_PSK,
	AH_CMD_DCDAUTH_GEN_PU_PSK_CFG,
	AH_CMD_DCDAUTH_UNSET_PSK,
	AH_CMD_DCDAUTH_UNSET_PSK_PER_USER,
	AH_CMD_DCDAUTH_NO_CWP_POPUP,
	AH_CMD_DCDAUTH_RM_UPDATE_INTERVAL,
	AH_CMD_DCDAUTH_LOCAL_CACHE_TIMEOUT,
	AH_CMD_DCDAUTH_CLEAR_PU_ALL,
	AH_CMD_DCDAUTH_PU_DEFAULT_PSK_DISABLED,
	AH_CMD_DCD_PU_COVER_NMS_CFG,
	AH_CMD_DCDAUTH_PPSK_DISABLED,
	AH_CMD_DCDAUTH_PPSK_SAME_USER_LIMIT,

	AH_CMD_DCDAUTH_EAP_8021X_TIMEOUT,
	AH_CMD_DCDAUTH_EAP_8021X_RETRY,

	AH_CMD_DCDAUTH_SHOW_HIVE_SUITE_ALL,
	AH_CMD_DCDAUTH_HIVE_SUITEMETHOD_OPEN,
	AH_CMD_DCDAUTH_HIVE_SUITEMETHOD_WPAAUTOPSK,
	AH_CMD_DCDAUTH_HIVE_SUITEMETHOD_WPAPSKTKIP,
	AH_CMD_DCDAUTH_HIVE_SUITEMETHOD_WPAPSKAES,
	AH_CMD_DCDAUTH_HIVE_SUITEMETHOD_WPA2PSKTKIP,
	AH_CMD_DCDAUTH_HIVE_SUITEMETHOD_WPA2PSKAES,
	AH_CMD_DCDAUTH_HIVE_SUITEMETHOD_DOT1XAUTOWPA,
	AH_CMD_DCDAUTH_HIVE_SUITEMETHOD_DOT1XWPATKIP,
	AH_CMD_DCDAUTH_HIVE_SUITEMETHOD_DOT1XWPAAES,
	AH_CMD_DCDAUTH_HIVE_SUITEMETHOD_DOT1XWPA2TKIP,
	AH_CMD_DCDAUTH_HIVE_SUITEMETHOD_DOT1XWPA2AES,
	AH_CMD_DCDAUTH_HIVE_SUITEMETHOD_DYNWEP40,
	AH_CMD_DCDAUTH_HIVE_SUITEMETHOD_DYNWEP104,
	AH_CMD_DCDAUTH_SET_HIVE_IDENTITY_TTLS,
	AH_CMD_DCDAUTH_SET_HIVE_IDENTITY_PEAP,
	AH_CMD_DCDAUTH_SET_HIVE_IDENTITY_TLS,
	AH_CMD_DCDAUTH_HIVE_DFLTUSER,
	AH_CMD_DCDAUTH_HIVE_PASSWD_PSK,

	AH_CMD_DCDAUTH_MAC_BASED_AUTH_ECWP,
	AH_CMD_DCDAUTH_MAC_BASED_AUTH_MAB,
	AH_CMD_DCDAUTH_RADIUS_SVRIP,
	AH_CMD_DCDAUTH_RADIUS_SVRIP_NO,
	AH_CMD_DCDAUTH_RADIUS_DYNAMIC_AUTH,
	AH_CMD_DCDAUTH_RADIUS_RETRY_INT,
	AH_CMD_DCDAUTH_RADIUS_ACCT_INT,
	AH_CMD_DCDAUTH_SHOW_AAA,
	AH_CMD_DCDAUTH_SHOW_MAC_WHITE_LIST,
	AH_CMD_DCDAUTH_HIVE_RSSI_THRESHOD1,
	AH_CMD_DCDAUTH_HIVE_RSSI_THRESHOD2,
	AH_CMD_DCDAUTH_SHOW_HIVE_RSSI,

#if 0
	/* dcd connection alarming command */
	AH_CMD_DCD_WCA_ENABLE,
	AH_CMD_DCD_WCA_SHOW,
	AH_CMD_DCD_WCA_TX_RETRY_THRESHOLD,
	AH_CMD_DCD_WCA_TX_FRAME_ERROR_THRESHOLD,
	AH_CMD_DCD_WCA_PROB_REQUEST_THRESHOLD,
	AH_CMD_DCD_WCA_INGRESS_MULTICAST_THRESHOLD,
	AH_CMD_DCD_WCA_CHANNEL_UTILIZATION_THRESHOLD,
	AH_CMD_DCD_WCA_EGRESS_MULTICAST_THRESHOLD,
#endif

	AH_CMD_SCD_HIVEMANAGER,
	AH_CMD_SCD_HIVEMANAGER_SHOW,
	AH_CMD_SCD_SNMP_LOC,
	AH_CMD_SCD_SNMP_LOC_SHOW,
	AH_CMD_SCD_SNMP_CONTACT,
	AH_CMD_SCD_SNMP_CONTACT_SHOW,
	AH_CMD_SCD_SNMP_COMM,
	AH_CMD_SCD_SNMP_COMM_SHOW,
	/* AH_CMD_SCD_SNMP_TRAPHOST,
	   AH_CMD_SCD_SNMP_TRAPHOST_SHOW,
	   AH_CMD_SCD_SNMP_INFORMHOST,
	   AH_CMD_SCD_SNMP_INFORMHOST_SHOW,*/
	AH_CMD_SCD_SNMP_SHOW,
	AH_CMD_SCD_SNMP_DEBUG,
	AH_CMD_SCD_SNMPV3_ADMIN,
	AH_CMD_SCD_HIVEMANAGER_COOKIE,

	AH_CMD_SCD_DEVICE_LOCATION,

	AH_CMD_SCD_SHOW_WEB_SERVER,
	AH_CMD_SCD_SHOW_WEB_KEY,
	AH_CMD_SCD_NO_WEB_PAGE,
	AH_CMD_SCD_RESET_WEB_PAGES,
	AH_CMD_SCD_NO_WEB_KEY,
	AH_CMD_SCD_WEB_SERVER_ENABLE,
	AH_CMD_SCD_SHOW_WEB_SERVER_STATUS,
	AH_CMD_SCD_CREATE_WEB_FOLDER,
	AH_CMD_SCD_CLEAR_ALL_WEB_PAGES,
	AH_CMD_SCD_SET_HOSTNAME,
	AH_CMD_SCD_CWP_WEB_PAGE_LINK,
	/*Add for capwap */
	AH_CMD_SCD_PRODUCT_NAME,
	/* Add for dallas chip */
	AH_CMD_SCD_SAVE_HWAUTH_KEY,
	/* for teacher view */
	AH_CMD_SCD_CAS_CLT_SRV_NAME,
	AH_CMD_SCD_CAS_CLT_SRV_PORT,
	AH_CMD_SCD_SHOW_CAS_CLT_CFG,

	AH_CMD_AUTH_USER_GROUP,
	AH_CMD_AUTH_USER_GROUP_DEV_TYPE,
	AH_CMD_AUTH_SHOW_USER_GROUP,
	AH_CMD_AUTH_USER_GROUP_ATTR,
	AH_CMD_AUTH_USER_GROUP_VLAN,
	AH_CMD_AUTH_USER_GROUP_REAUTH_ITV,
	AH_CMD_AUTH_USER_GROUP_START_TIME,
	AH_CMD_AUTH_USER_GROUP_EXPIRED_TIME,
	AH_CMD_AUTH_USER_GROUP_PSK_GEN_MD,
	AH_CMD_AUTH_USER_GROUP_CONC_CHARS,
	AH_CMD_AUTH_USER_GROUP_PASSWD_MD,
	AH_CMD_AUTH_USER_GROUP_CHAR_PATTERN,
	AH_CMD_AUTH_USER_GROUP_COMBO_PATTERN,
	AH_CMD_AUTH_USER_GROUP_AUTO_SCHD,
	AH_CMD_AUTH_USER_GROUP_AUTO_SECRET,
	AH_CMD_AUTH_USER_GROUP_AUTO_LOCATION,
	AH_CMD_AUTH_USER_GROUP_AUTO_PREFIX,
	AH_CMD_AUTH_USER_GROUP_AUTO_PASS_LEN,
	AH_CMD_AUTH_USER_GROUP_AUTO_INDEX,
	AH_CMD_AUTH_USER_GROUP_CACHE_MODE,
	AH_CMD_AUTH_USER_GROUP_BULK,

	AH_CMD_AUTH_PPSK_ONCE_SCHEDULE,
	AH_CMD_AUTH_PPSK_RECURRENT_SCHEDULE,
	AH_CMD_AUTH_PPSK_SHOW_SCHEDULE,

	AH_CMD_AUTH_USER,
	AH_CMD_AUTH_SHOW_USER,
	AH_CMD_SCD_SHOW_USERS,
	AH_CMD_AUHT_USER_SECRET,
	AH_CMD_AUHT_USER_BIND_GROUP,
	AH_CMD_AUHT_USER_UNBIND_GROUP_ALL,
	AH_CMD_AUTH_SSID_BIND_GROUP,
	AH_CMD_AUTH_SHOW_SSID_GROUP,
	AH_CMD_AUTH_SHOW_RUN_USERS,
	AH_CMD_AUTH_SAVE_CFG_USERS,
	AH_CMD_AUTH_RADIUS_BIND_GROUP,
	AH_CMD_AUTH_RADIUS_CHECK_KEEPALIVE_ENABLE,
	AH_CMD_AUTH_RADIUS_CHECK_KEEPALIVE_INTERVAL,
	AH_CMD_AUTH_RADIUS_CHECK_KEEPALIVE_RETRIES,
	AH_CMD_AUTH_RADIUS_CHECK_KEEPALIVE_RETRY_INTERVAL,
	AH_CMD_AUTH_RADIUS_CHECK_KEEPALIVE_USERNAME_PASSWORD,
	AH_CMD_AUTH_RADIUS_EXEC_STATUS_CHECK,
	AH_CMD_AUTH_RADIUS_EXEC_STATUS_CALCHK,
	AH_CMD_AUTH_RADIUS_ACCT_EXEC_STATUS_CHECK,
	AH_CMD_AUHT_REVOKE_AUTO_USERS,
	AH_CMD_AUTH_NO_USER_ALL,
	AH_CMD_AUTH_NO_USER_GROUP_ALL,
	AH_CMD_AUTH_GROUP_PSK_TO_PMK,
	AH_CMD_AUTH_GROUP_PMK_AUTO_SAVE,
	AH_CMD_AUTH_AUTO_PSK_DIGEST,

	AH_CMD_AUTH_ROAMING_BACKHAUL_NEIGHBOR,
	AH_CMD_AUTH_ROAMING_ACCESS_NEIGHBOR,

	AH_CMD_AUTH_SHOW_RT_STA,
	AH_CMD_AUTH_MAC_BIND_TEST,
	AH_CMD_SAVE_MAC_BIND_INFO,

	AH_CMD_AUTH_1X_EXPIRE_TIME,
	AH_CMD_AUTH_1X_SUPPRESS_INTV,
	AH_CMD_AUTH_1X_SHOW,
	AH_CMD_AUTH_MDM_EXEC_ENROLL_STATUS,
	AH_CMD_AUTH_MDM_EXEC_STATUS_UPDATE,
	AH_CMD_AUTH_JSS_EXEC_GET_VER,
	/*Add for capwap */
	AH_CMD_CAPWAP_SERVER_ENABLE,
	AH_CMD_CAPWAP_CLIENT_ENABLE,
	AH_CMD_CAPWAP_CLIENT_ENABLE_WITHIP,
	AH_CMD_CAPWAP_DISCOVERY_INTERVAL,
	AH_CMD_CAPWAP_DISCOVERY_MAXINTERVAL,
	AH_CMD_CAPWAP_STAT_UPDATE_INTERVAL,
	AH_CMD_CAPWAP_HEARTBEAT,
	AH_CMD_CAPWAP_NEIGHBORDEAD,
	AH_CMD_CAPWAP_RETRYTIMEOUT,
	AH_CMD_CAPWAP_JOINTIMEOUT,
	AH_CMD_CAPWAP_DISCOUNTE,
	AH_CMD_CAPWAP_MAXTRYCOUNT,
	AH_CMD_CAPWAP_SILENTINTERVAL,
	AH_CMD_CAPWAP_SHOW_CLIENTPAR,
	AH_CMD_CAPWAP_SHOW_SERVERPAR,
	AH_CMD_CAPWAP_SHOW_CLIENTSTATE,
	AH_CMD_CAPWAP_SHOW_SERVERSTATE,
	AH_CMD_CAPWAP_SHOW_EVENTBUFF,
	AH_CMD_CAPWAP_EVENT_SND,
	AH_CMD_CAPWAP_EVENT_ENABLE,
	AH_CMD_CAPWAP_SHOW_CLI_PKT,
	AH_CMD_CAPWAP_SHOW_FRAG_BUF,
	AH_CMD_CAPWAP_TEST_CLI_CMD,
	AH_CMD_CAPWAP_TEST_HVCOM_CMD,
	AH_CMD_CAPWAP_RETURN_CODE,
	AH_CMD_CAPWAP_SRV_PORT,
	AH_CMD_CAPWAP_SRV_NAME,
	AH_CMD_NO_CAPWAP_SRV_NAME,
	AH_CMD_CAPWAP_DTLS_ENABLE,
	AH_CMD_CAPWAP_DTLS_HM_DEFINE_PASPHRASE,
	AH_CMD_CAPWAP_DTLS_BOOTSTRAP_PASPHRASE,
	AH_CMD_CAPWAP_DTLS_SET_PSK,
	AH_CMD_CAPWAP_DTLS_SESSION_DEL_TIMER,
	AH_CMD_CAPWAP_DTLS_ACEPT_BOOT_PASPHRASE,
	AH_CMD_CAPWAP_DTLS_MAX_RETYR,
	AH_CMD_CAPWAP_DTLS_HANDSHAKE_TIMER,
	AH_CMD_CAPWAP_STAT_TEST,
	AH_CMD_CAPWAP_SHOW_SHM,
	AH_CMD_CAPWAP_DTLS_NEGOTIATION,
	AH_CMD_CAPWAP_CLEAR_PKT_COUNTER,
	AH_CMD_CAPWAP_PCI_ALERT,
	AH_CMD_CAPWAP_SHOW_HVCOM_STATUS,
	AH_CMD_CAPWAP_VHM_NAME,
	AH_CMD_CAPWAP_HM_VHM_NAME,
	AH_CMD_CAPWAP_PRE_SRV_NAME,
	AH_CMD_CAPWAP_TRANSFER_MODE,
	AH_CMD_CAPWAP_PROXY_INFO,
	AH_CMD_CAPWAP_PROXY_AUTH,
	AH_CMD_CAPWAP_PROXY_CONTENT_LENGTH,
	AH_CMD_CAPWAP_DELAY_TIME,
	AH_CMD_CAPWAP_DETECTION,
	/*End add*/
	/*Process Monitor CLI*/
	AH_CMD_PM_SW_DOG,
	AH_CMD_PM_PROC_MONITOR,
	AH_CMD_PM_PROC_MONITOR_NETLINK,
	AH_CMD_PM_PROC_MONITOR_CPU,
	AH_CMD_PM_PROC_MONITOR_SHOW_CPU,
	AH_CMD_PM_SET_CPU_PARAM,
	AH_CMD_PM_PROC_MONITOR_CPU_ITV,
	AH_CMD_PM_SET_NETLINK_THRESHOLD,
	AH_CMD_PM_SHOW_LIMIT,
	AH_CMD_PM_SHOW_STATE,
	AH_CMD_PM_SET_MEMORY,
	AH_CMD_PM_CORE_FILE,
	AH_CMD_PM_SHOW_SHM,
	AH_CMD_PM_SHOW_SYSTEM_NETLINK,
	AH_CMD_PM_CHG_ACT,
	AH_CMD_PM_SET_MONITOR_VALUE,
	AH_CMD_PM_PROC_MONITOR_DISABLE_CACHE_DROP,
	/*End PM*/

	AH_CMD_SHOW_RUN_CFG,
	AH_CMD_SHOW_RUN_CFG_PWD,
	AH_CMD_SHOW_FE_CNT,
	AH_CMD_SHOW_ARPC,
	AH_CMD_SHOW_ARPC2, /* amrp2 show arp cache */
	AH_CMD_SHOW_HM_TEST, /* test hm/hiveap communication */
	AH_CMD_SHOW_IP_GATE,
	AH_CMD_SHOW_MAC_SESS_ID,
	AH_CMD_SHOW_MAC_SESS_ADDR,
	AH_CMD_SHOW_IP_SESS_ID,
	AH_CMD_SHOW_IP_SESS_PARAMS,
	AH_CMD_SHOW_INTER_SSID_FLOOD,
	AH_CMD_SHOW_POLICY,
	AH_CMD_SHOW_IP_FRAG_AGEOUT_TIME,
	AH_CMD_SHOW_IP_FCB_LIST,
	AH_CMD_SHOW_FE_STATION_UNROAM_THRESHOLD,
	AH_CMD_SET_IP_FRAG_AGEOUT_TIME,
	AH_CMD_SHOW_AGG0_MEMBER_INTERFACE,
	AH_CMD_SET_AGG0_HASH_MODE,
	AH_CMD_SHOW_VPN_GRE_TUNNEL,
	AH_CMD_SHOW_GRE_TUNNEL,
	AH_CMD_SHOW_TUNNEL,
	AH_CMD_CLEAR_MAC_SESSION_ID,
	AH_CMD_CLEAR_MAC_SESSION_PARAMS,
	AH_CMD_CLEAR_IP_SESSION_ID,
	AH_CMD_CLEAR_IP_SESS_PARAMS,
	AH_CMD_SAVE_RUN_CFG,
	AH_CMD_CONF_RUNNING_BOOTSTRAP,
	AH_CMD_CONF_RUNNING_CURRENT,
	AH_CMD_CONF_RUNNING_CURRENT_OLD_V2,
	AH_CMD_CONF_SHOW_RUNNING,
	AH_CMD_CONF_SHOW_RUNNING_PWD,
	AH_CMD_FE_STATUS,
	AH_CMD_FE_SESS_SYNC_VLAN,
	AH_CMD_FE_PROXY_ARP_STATUS,
	AH_CMD_FE_ICSA_STATUS,
	AH_CMD_FE_ICSA_LOG,
	AH_CMD_FE_ICSA_DROP,
	AH_CMD_FE_ICSA_SHOW,
	AH_CMD_FE_INTER_SSID_FLOOD,
	AH_CMD_FE_VWIRE_INTERFACES,

	AH_CMD_GET_DEBUG_INFO,

	/* clear cli */
	AH_CMD_CLEAR_ARPC,

	/* CLI TEST CMDS */
	AH_CMD_TEST,
	AH_CMD_GET_TEST,

	/*  cli for qos module  */
	AH_CMD_FTP_ALG_ENABLE,
	AH_CMD_SET_ALG_ENABLE,
	AH_CMD_QOS_ENABLE,
	AH_CMD_QOS_DISABLE,
	AH_CMD_AIRTIME_QOS_ENABLE,
	AH_CMD_AIRTIME_QOS_RATE_PREFERENCE_WEIGHT,
	AH_CMD_SHOW_QOS,
	AH_CMD_QOS_SET_CLASS_8021P,
	AH_CMD_QOS_UNSET_CLASS_8021P,
	AH_CMD_QOS_SHOW_CLASS_8021P,

	AH_CMD_QOS_SET_CLASS_80211E,
	AH_CMD_QOS_UNSET_CLASS_80211E,
	AH_CMD_QOS_SHOW_CLASS_80211E,

	AH_CMD_QOS_SET_CLASS_DSCP,
	AH_CMD_QOS_UNSET_CLASS_DSCP,
	AH_CMD_QOS_SHOW_CLASS_DSCP,

	AH_CMD_QOS_SET_CLASS_MAC,
	AH_CMD_QOS_SHOW_CLASS_MAC,

	AH_CMD_QOS_SET_CLASS_INTERFACE,
	AH_CMD_QOS_SET_VIRCLASS_INTERFACE,
	AH_CMD_QOS_SHOW_CLASS_INTERFACE,
	AH_CMD_QOS_SHOW_CLASS_VIRINTERFACE,
	AH_CMD_QOS_SET_CLASS_SSID,
	AH_CMD_QOS_SHOW_CLASS_SSID,

	AH_CMD_QOS_SET_CLASS_WIFIINTERFACE,
	AH_CMD_QOS_SET_CLASS_VIRTUALWIFIINTERFACE,

	AH_CMD_QOS_SHOW_CLASS_WIFIINTERFACE,
	AH_CMD_QOS_SHOW_CLASS_VIRTUALWIFIINTERFACE,
	AH_CMD_QOS_SHOW_CLASS_ALLINTERFACE,

	AH_CMD_QOS_SET_SERVICE,
	AH_CMD_QOS_SET_PROTOCOL_SERVICE,

	AH_CMD_L7_SERVICE,

	AH_CMD_QOS_SET_CLASS_SERVICE,
	AH_CMD_QOS_SHOW_CLASS_SERVICE,

	AH_CMD_QOS_SET_CLASS_SERVICE_ACTION,
	AH_CMD_QOS_SHOW_CLASS_SERVICE_ACTION,

	AH_CMD_QOS_SHOW_STATISTICS_USER,
	AH_CMD_QOS_SHOW_STATISTICS_VLAN,
	AH_CMD_QOS_CLEAR_STATISTICS,

	AH_CMD_QOS_ENABLE_PERFORMANCE_MEASUR,
	AH_CMD_QOS_SHOW_PERFORMANCE_STATUS,
	AH_CMD_QOS_SHOW_PERFORMANCE_DATA_USER,
	AH_CMD_QOS_SHOW_PERFORMANCE_DATA_VLAN,
	AH_CMD_QOS_SHOW_USER_SNAP,
	AH_CMD_QOS_SHOW_VLAN_SNAP,

	AH_CMD_QOS_SET_MARKPROFILE,
	AH_CMD_QOS_SHOW_MARKPROFILE,

	AH_CMD_QOS_SET_CLASS_MARKING_8021P,
	AH_CMD_QOS_UNSET_CLASS_MARKING_8021P,
	AH_CMD_QOS_SHOW_CLASS_MARKING_8021P,

	AH_CMD_QOS_SET_CLASS_MARKING_80211E,
	AH_CMD_QOS_UNSET_CLASS_MARKING_80211E,
	AH_CMD_QOS_SHOW_CLASS_MARKING_80211E,

	AH_CMD_QOS_SET_CLASS_MARKING_DSCP,
	AH_CMD_QOS_UNSET_CLASS_MARKING_DSCP,
	AH_CMD_QOS_SHOW_CLASS_MARKING_DSCP,
	AH_CMD_QOS_SET_MARKER_DIFFSERV_NAME,
	AH_CMD_QOS_SET_MARKER_8021P_NAME,
	AH_CMD_QOS_UNSET_MARKER_NAME,
	AH_CMD_QOS_SHOW_MARKER_NAME,

	AH_CMD_QOS_SET_POLICYPROFILE,
	AH_CMD_QOS_SET_USER_POLICYPROFILE,
	AH_CMD_QOS_SHOW_POLICYPROFILE,
	AH_CMD_QOS_UNSET_USERPROFILE_POLICY,
	AH_CMD_QOS_SET_DEFAULT_VLANPOLICY,
	AH_CMD_QOS_SHOW_DEFAULT_VLANPOLICY,

	AH_CMD_QOS_SET_USERPROFILE_MARKER,

	AH_CMD_QOS_SET_VLANPOLICY,
	AH_CMD_QOS_SHOW_VLANPOLICY,
	AH_CMD_QOS_SET_HIDDEN_SERVICE,
	AH_CMD_QOS_SET_SVP_SERVICE,
	AH_CMD_QOS_UNSET_SERVICE,
	AH_CMD_QOS_SHOW_SERVICE,

	AH_CMD_QOS_POLICY,
	AH_CMD_QOS_SHOW_POLICY,

	AH_CMD_QOS_INTER_ASSIGN_CLASSIFER,
	AH_CMD_QOS_VWIFIINTER_ASSIGN_CLASSIFER,
	AH_CMD_QOS_SHOW_INTER_CLASSIFER,
	AH_CMD_QOS_SHOW_VWIFIINTER_CLASSIFER,
	AH_CMD_QOS_SSID_INTER_ASSIGN_MARKER,
	AH_CMD_QOS_VWIFIINTER_ASSIGN_MARKER,
	AH_CMD_QOS_SHOW_SSID_INTER_MARKER,

	AH_CMD_QOS_SSID_INTER_ASSIGN_CLASSIFER,
	AH_CMD_QOS_SHOW_SSID_INTER_CLASSIFER,

	AH_CMD_QOS_INTER_WIFI_CLASSIFER,
	AH_CMD_QOS_INTER_VIRTUALWIFI_CLASSIFER,

	AH_CMD_QOS_SHOW_WIFI_CLASSIFER,
	AH_CMD_QOS_SHOW_VIRTUALWIFI_CLASSIFER,

	AH_CMD_QOS_INTER_WIFI_MARKER,
	AH_CMD_QOS_INTER_VIRTUAL_WIFI_MARKER,

	AH_CMD_QOS_SHOW_WIFIINTER_MARKER,
	AH_CMD_QOS_SHOW_VIRTUAL_WIFI_INTER_MARKER,
	AH_CMD_QOS_INTER_ASSIGN_MARKER,
	AH_CMD_QOS_SHOW_INTER_MARKER,

	AH_CMD_QOS_SHOW_SERVICE_COUNT,
	AH_CMD_QOS_CLEAR_SERVICE_COUNT,
	AH_CMD_QOS_SHOW_USER_COUNT,
	AH_CMD_QOS_SHOW_VLAN_COUNT,
	AH_CMD_QOS_CLEAR_COUNT,
	AH_CMD_QOS_INTER_ASSIGN_CLASSPROFILE,
	AH_CMD_QOS_SHOW_CLASSPROFILE,

	AH_CMD_QOS_SET_USERPROFILE,
	AH_CMD_QOS_UNSET_USERPROFILE_MOB,
	AH_CMD_QOS_SHOW_USERPROFILE,
	AH_CMD_QOS_MOVE_USERPROFILE,
	AH_CMD_QOS_SHOW_COUNTER_USERPROFILE,
	AH_CMD_QOS_SHOW_SNAPSHOT_USERPROFILE,
	AH_CMD_RADIO_RATES,

	//AH_CMD_RADIO_RTS_THRESHOLD,
	AH_CMD_SSID_RTS_THRESHOLD,
	AH_CMD_HIVE_RTS_THRESHOLD,
	AH_CMD_RADIO_BECON_PERIOD,
	AH_CMD_DCD_RADIO_LB_STATE,
	AH_CMD_DCD_RADIO_LB_STACOUNT,
	AH_CMD_DCD_RADIO_LB_OOLOAD,
	AH_CMD_DCD_RADIO_LB_ROAM_DBM,
	AH_CMD_DCD_RADIO_LB_ROAM_DBM_STR,

	/*ACL FIREWALL*/
	AH_CMD_FED_SET_IP_POL,
	AH_CMD_FED_SET_IP_POL_DENY_LOG,
	AH_CMD_FED_SET_IP_POL_PERMIT_LOG,
	AH_CMD_FED_SET_IP_POL_INT_STA_LOG,
	AH_CMD_FED_NO_IP_POL_LOG,

	AH_CMD_FED_SET_MAC_POL,
	AH_CMD_FED_SET_IP_POL_TOMGT,

	AH_CMD_FED_SET_MAC_POL_DENY_LOG,
	AH_CMD_FED_SET_MAC_POL_PERMIT_LOG,
	AH_CMD_FED_NO_MAC_POL_LOG,
	AH_CMD_FED_SET_UPID_MAC_POL_DEF,
	AH_CMD_FED_SHOW_MAC_POL_BY_GRP,
	AH_CMD_FED_SHOW_MAC_POL_BY_UPID,
	AH_CMD_FED_SHOW_MAC_POL_GRP,

	AH_CMD_FED_BIND_GRP,
	AH_CMD_FED_UNBIND_GRP,

	AH_CMD_FED_UNSET_USERPROFILE_ATTR,
	AH_CMD_FED_SET_UPID_IP_POL_DEF,
	AH_CMD_FED_SHOW_IP_POL_BY_GRP,
	AH_CMD_FED_SHOW_IP_POL_BY_UPID,
	AH_CMD_FED_SHOW_IP_POL_GRP,
	AH_CMD_FED_SHOW_INITERNAL_IP_POL_GRP,
	AH_CMD_FED_SHOW_IP_POL_DB,

	/*ACL MAC FIREWALL */
	AH_CMD_FED_BIND_MAC_GRP,
	AH_CMD_FED_UNBIND_MAC_GRP,

	/* IPv6 related */
	AH_CMD_DENY_IPV4_OR_V6,
	AH_CMD_IPV6_RA_GUARD_ENABLE,
	AH_CMD_IPV6_DHCPV6_SHIELD_ENABLE,

	AH_CMD_FED_IF_RATE_LIMIT_ENABLE,
	AH_CMD_FED_IF_RATE_LIMIT_MULTICAST,
	AH_CMD_FED_IF_RATE_LIMIT_BROADCAST,
	AH_CMD_FED_IF_RATE_LIMIT_UNICAST,
	AH_CMD_FED_IF_RATE_LIMIT_SHOW,
	AH_CMD_FED_CLEAR_GRE_TUN_DNXP_MAC,
	AH_CMD_FED_CLEAR_GRE_TUN_DNXP_IP,
	AH_CMD_FED_CLEAR_GRE_TUN_DNXP_ALL,
	AH_CMD_FED_CLEAR_GRE_TUN_INXP_MAC,
	AH_CMD_FED_CLEAR_GRE_TUN_INXP_IP,
	AH_CMD_FED_CLEAR_GRE_TUN_INXP_ALL,
	AH_CMD_FED_SHOW_FE_CNT,
	AH_CMD_FED_SHOW_FE_CNT_SWITCH,
	AH_CMD_FED_CLEAR_FE_CNT,
	AH_CMD_FED_CLEAR_FE_CNT_SWITCH,
	AH_CMD_FED_CLEAR_GRE_TUNNEL_CNT,
	AH_CMD_FED_IP_SESS_PER_STA,
	AH_CMD_FED_MAC_SESS_PER_STA,
	AH_CMD_FED_SHOW_MAX_IP_SESS,
	AH_CMD_FED_SHOW_MAX_MAC_SESS,
	AH_CMD_FED_CAC_ENABLE,
	AH_CMD_FED_UGR_SET_CAC_GUAR,
	AH_CMD_FED_SET_CAC_AIRTIME_PER_SECOND,
	AH_CMD_FED_SET_CAC_ROAMING_AIRTIME_PERCENT,
	AH_CMD_FED_UGR_SHOW_CAC_GUAR,
	AH_CMD_FED_CLEAR_STAT_AIRTIME,
	AH_CMD_FED_SHOW_STAT_CAC,
	AH_CMD_FED_PERFORMANCE_SENTINEL_ENABLE,
	AH_CMD_FED_PERFORMANCE_SENTINEL_ACTION,
	AH_CMD_FED_PERFORMANCE_SENTINEL_GUARANTEED,
	AH_CMD_FED_PERFORMANCE_SENTINEL_CONG_THRES,
	AH_CMD_FED_PERFORMANCE_SENTINEL_INTERVAL,
	AH_CMD_FED_PERFORMANCE_SENTINEL_INTERVAL_NEW,
	AH_CMD_FED_SHOW_PERFORMANCE_SENTINEL,
	AH_CMD_ALG_SIP_CALL_SHOW,
	AH_CMD_FED_USER_BIND_TUNNEL_POL,
	AH_CMD_SET_MAC_SESSION_AGEOUT_TIME,
	AH_CMD_SHOW_MAC_SESSION_AGEOUT_TIME,
	AH_CMD_FED_SET_SELECTIVE_MULTICAST_FORWARD,
	AH_CMD_FED_SET_SELECTIVE_MULTICAST_FORWARD_ALLOW,
	AH_CMD_FED_SET_SELECTIVE_MULTICAST_FORWARD_BLOCK,
	AH_CMD_FED_SHOW_SELECTIVE_MULTICAST_FORWARD,
	AH_CMD_FED_SET_TCP_MSS_THRESHOLD_ENABLE,
	AH_CMD_FED_SET_TCP_MSS_THRESHOLD_SIZE,
	AH_CMD_FED_SHOW_TCP_MSS_THRESHOLD,
	AH_CMD_FED_SHOW_REGISTERED_PORT,
	AH_CMD_FED_USER_PROF_SET_L3_TUNNEL_ACTION,
	AH_CMD_FED_USERPROF_IPP_REDIR,
	AH_CMD_FED_DEFAULT_ROUTE_VLAN,
	AH_CMD_FED_SHOW_DEFAULT_ROUTE_VLAN,

	/* PMTUD */
	AH_CMD_FED_SET_IP_PMTUD_ENABLE,
	AH_CMD_FED_SHOW_IP_PMTUD,

	/* virtual connection CLIs */
	AH_CMD_FED_VCON_ADD_PASS_RULE_IIF_NONWIFI_SRCMAC_OIF_NONWIFI,
	AH_CMD_FED_VCON_ADD_PASS_RULE_IIF_NONWIFI_SRCMAC_OIF_WIFI,
	AH_CMD_FED_VCON_ADD_PASS_RULE_IIF_WIFI_SRCMAC_OIF_NONWIFI,
	AH_CMD_FED_VCON_ADD_PASS_RULE_IIF_WIFI_SRCMAC_OIF_WIFI,

	AH_CMD_FED_VCON_ADD_PASS_RULE_IIF_NONWIFI_SRCOUI_OIF_NONWIFI,
	AH_CMD_FED_VCON_ADD_PASS_RULE_IIF_NONWIFI_SRCOUI_OIF_WIFI,
	AH_CMD_FED_VCON_ADD_PASS_RULE_IIF_WIFI_SRCOUI_OIF_NONWIFI,
	AH_CMD_FED_VCON_ADD_PASS_RULE_IIF_WIFI_SRCOUI_OIF_WIFI,

	AH_CMD_FED_VCON_ADD_PASS_RULE_IIF_NONWIFI_SRCIGNORE_OIF_NONWIFI,
	AH_CMD_FED_VCON_ADD_PASS_RULE_IIF_NONWIFI_SRCIGNORE_OIF_WIFI,
	AH_CMD_FED_VCON_ADD_PASS_RULE_IIF_WIFI_SRCIGNORE_OIF_NONWIFI,
	AH_CMD_FED_VCON_ADD_PASS_RULE_IIF_WIFI_SRCIGNORE_OIF_WIFI,

	AH_CMD_FED_VCON_ADD_DROP_RULE_IIF_NONWIFI_SRCMAC,
	AH_CMD_FED_VCON_ADD_DROP_RULE_IIF_WIFI_SRCMAC,

	AH_CMD_FED_VCON_ADD_DROP_RULE_IIF_NONWIFI_SRCOUI,
	AH_CMD_FED_VCON_ADD_DROP_RULE_IIF_WIFI_SRCOUI,

	AH_CMD_FED_VCON_ADD_DROP_RULE_IIF_NONWIFI_SRCIGNORE,
	AH_CMD_FED_VCON_ADD_DROP_RULE_IIF_WIFI_SRCIGNORE,

	AH_CMD_FED_VCON_DEL_RULE,
	AH_CMD_FED_VCON_SHOW_RULES,

	AH_CMD_FED_VCON_DEBUG,

	/* add for FE new filter */
	AH_CMD_FED_FF,
	AH_CMD_FED_FFV6,    /* not used */
	AH_CMD_FED_DEL_FF,
	AH_CMD_FED_FF_DHCP,
	AH_CMD_FED_FF_SHOW,

	/* AUTH module cmd */
	AH_CMD_HIVE_DCDAUTH_SUITEMETHOD_DOT1XAUTOWPA,
	AH_CMD_AUTH_SHOW_RM_CACHE,
	AH_CMD_AUTH_SHOW_RM_ONE_CACHE,
	AH_CMD_AUTH_SET_RM_CACHE,

	AH_CMD_AUTH_MAC_FORMAT_DELIMITER,
	AH_CMD_AUTH_MAC_FORMAT_STYLE,
	AH_CMD_AUTH_MAC_FORMAT_CASE,

	AH_CMD_AUTH_RADIUS_SVRIP,
	AH_CMD_AUTH_RADIUS_SVRIP_NO,
	AH_CMD_AUTH_RADIUS_ACCT_SVRIP,
	AH_CMD_AUTH_RADIUS_ACCT_SVRIP_NO,
	AH_CMD_AUTH_RADIUS_DYNAMIC_AUTH,
	AH_CMD_AUTH_RADIUS_RETRY_INT,
	AH_CMD_AUTH_RADIUS_ACCT_INT,
	/*support Nas-Identifier & Operator-Name*/
	AH_CMD_AUTH_ATTR_NAS_IDENTIFIER,
	AH_CMD_AUTH_ATTR_NAS_IDENTIFIER_APPEND_BSSID,
	AH_CMD_AUTH_ATTR_OPERATOR_NAME,
	AH_CMD_AUTH_ATTR_OPERATOR_NAME_SPACE_ID_OPTIONAL,
	AH_CMD_AUTH_ATTR_OPERATOR_NAME_SPACE_ID_NUMBER,
	AH_CMD_AUTH_RADIUS_NAS_SUPPORT_OPERATOR_NAME,
	AH_CMD_AUTH_ADD_VENDOR_ATTR_ID,
	AH_CMD_AUTH_DISABLE_ADD_UPID,

	AH_CMD_AUTH_MACBIND_AUTOSAVE_GAP,
	AH_CMD_AUTH_PPSK_SELF_SRV_RADIUS,
	AH_CMD_PPSK_SELF_SRV_RADIUS_NO,

	AH_CMD_AUTH_SHOW_AAA,
	AH_CMD_AUTH_SHOW_AUTH_STATE,
	AH_CMD_AUTH_SHOW_AUTH_STATE_SWITCH,
	AH_CMD_AUTH_EXEC,
	AH_CMD_AUTH_EXTEND,
	AH_CMD_AUTH_DBG_FILTER,
	AH_CMD_AUTH_DBG_FILTER_NO_INTF,
	AH_CMD_AUTH_DBG_FILTER_NO_STA,
	AH_CMD_AUTH_DBG_FILTER_NO_MOD,
	AH_CMD_AUTH_SHOW_DBG_FILTER,
	AH_CMD_AUTH_GEN_PU_DYN_PSK,
	AH_CMD_AUTH_GET_RM_MAC_USERNAME,
	AH_CMD_AUTH_SHOW_AUTH_PU_STATIC,

	/* AMRP NEW cmd */
	AH_CMD_AUTH_SET_RMM_CACHE,
	AH_CMD_AUTH_ROAMING_HOP,
	AH_CMD_AUTH_ROAMING_ENABLE,
	AH_CMD_AUTH_CLEAR_CACHE,
	AH_CMD_AUTH_CLEAR_CACHE_ONE_HIVE,
	AH_CMD_AUTH_CLEAR_CACHE_ALL_HIVE,
	AH_CMD_AUTH_CLEAR_CACHE_BYSSID,
	AH_CMD_AUTH_CLEAR_CACHE_BYUSERNAME,
	AH_CMD_AUTH_CLEAR_PU_CACHE,

	/* User Attribute Policy */
	AH_CMD_AUTH_MAC_OUI_OBJ,
	AH_CMD_AUTH_MAC_OUI_OBJ_DISPLAY,
	AH_CMD_AUTH_OS_OBJ,
	AH_CMD_AUTH_OS_OBJ_DISPLAY,
	AH_CMD_AUTH_DN_OBJ,
	AH_CMD_AUTH_DN_OBJ_DISPLAY,
	AH_CMD_AUTH_DEVICE_GROUP,
	AH_CMD_AUTH_DEVICE_GROUP_DISPLAY,
	AH_CMD_AUTH_ATTR_POLICY,
	AH_CMD_AUTH_ATTR_POLICY_MOVE,
	AH_CMD_AUTH_ATTR_POLICY_APPLY,
	AH_CMD_AUTH_ATTR_POLICY_DETECT_METHOD,
	AH_CMD_AUTH_ATTR_POLICY_DISPLAY,
	AH_CMD_AUTH_SO_ATTR_POLICY_DISPLAY,
	AH_CMD_AUTH_UPNAME_ID_DISPLAY,
	AH_CMD_AUTH_OS_DETECT_ENABLE,
	AH_CMD_AUTH_OS_DETECT_METHOD_UA,
	AH_CMD_AUTH_OS_DETECT_METHOD_DHCP55,
	AH_CMD_AUTH_OS_MAPPING_OPTION55,
	AH_CMD_AUTH_SHOW_DHCP_OS_TO_OPTION55,
	AH_CMD_AUTH_SHOW_DHCP_FP_STA,
	AH_CMD_AUTH_DHCP_FP_UPDATE,

	AH_CMD_AUTH_UP_POLICY,
	AH_CMD_AUTH_UP_POLICY_NO_ATTR,
	AH_CMD_AUTH_UP_POLICY_NO_RULE,
	AH_CMD_AUTH_UP_POLICY_MDM_TIMEOUT,
	AH_CMD_AUTH_UP_POLICY_UPID_ACT,
	AH_CMD_AUTH_UP_POLICY_SHOW,
	AH_CMD_AUTH_MDM_OBJ,
	AH_CMD_AUTH_MDM_OBJ_NO,
	AH_CMD_AUTH_RECURRENT_TIME_OBJ,
	AH_CMD_AUTH_RECURRENT_TIME_OBJ_NO,
	AH_CMD_AUTH_UP_POLICY_TIME_INTERVAL,
	AH_CMD_AUTH_SHOW_MDM_OBJ,
	AH_CMD_AUTH_SHOW_LOC_OBJ,
	AH_CMD_AUTH_SHOW_TIME_OBJ,
	AH_CMD_AUTH_UP_POLICY_RULE,
	AH_CMD_AUTH_UP_POLICY_RULE_AUTH_UPID,
	AH_CMD_AUTH_UP_POLICY_RULE_GRP_NAME,
	AH_CMD_AUTH_UP_POLICY_RULE_MAC_OBJ,
	AH_CMD_AUTH_UP_POLICY_RULE_OS_OBJ,
	AH_CMD_AUTH_UP_POLICY_RULE_DEVICE_LOC,
	AH_CMD_AUTH_UP_POLICY_RULE_TIME_OBJ,
	AH_CMD_AUTH_UP_POLICY_RULE_MDM_OBJ,
	AH_CMD_AUTH_ONCE_TIME_OBJ,


	/* RM NEW cmd */
	AH_CMD_AUTH_ROAMING_CACHE_QUERY,
	AH_CMD_AUTH_ROAMING_CACHE_UPDATE,
	AH_CMD_AUTH_ROAMING_CACHE_UPDATE_VERSION,
#if 0
	AH_CMD_AUTH_SHOW_NEIGHBOR_HIDE,
#endif

	AH_CMD_AUTH_SHOW_BEH_RECON,

	/* dynamic server config */
	AH_CMD_AUTH_SERVER_RADSEC_DYNAMIC,
	AH_CMD_AUTH_SHOW_DYNAMIC_SERVER,
	AH_CMD_AUTH_IDM_EXEC_STATUS_CHECK,

	AH_CMD_AUTH_SHOW_CLIENT_INFO,
	AH_CMD_AUTH_ENABLE_CLIENT_INFO,

	/* DCD ACSP cmd */
	/*AH_CMD_DCD_ACSP_ENABLE,
	AH_CMD_DCD_ACSP_ONCE,
	AH_CMD_DCD_ACSP_NO_STA,
	AH_CMD_DCD_ACSP_POWER_SELECT_ENABLE,
	AH_CMD_DCD_ACSP_CHANNEL_SELECT_ENABLE,*/

	AH_CMD_DCD_ACSP_CHNL_SWITCH_INTERVAL,
	AH_CMD_DCD_SHOW_CHNL_SLT,
	AH_CMD_DCD_SHOW_CHNL_STC,
	AH_CMD_DCD_SHOW_PWER_STC,
	AH_CMD_DCD_SHOW_NBR_LIST,
	AH_CMD_DCD_SHOW_NEIGHBOR_LIST,

	AH_CMD_DCD_ROAMING_PORT,
	AH_CMD_DCD_NEIGHBOR_QUERY,
	AH_CMD_DCD_NEIGHBOR_STATIC_INCLUDE,
	AH_CMD_DCD_NEIGHBOR_STATIC_EXCLUDE,
	AH_CMD_DCD_SHOW_NEIGHBOR,
	AH_CMD_DCD_CLEAR_NEIGHBOR,
	AH_CMD_DCD_CLEAR_NEIGHBOR_COUNT,


	AH_CMD_DCD_DEBUG_WIFI,
	AH_CMD_DCD_DEBUG_WIFI_SHOW,
	AH_CMD_DCD_IF_ACCESS_ENABLE,
	AH_CMD_DCD_IF_ACCESS_ENABLE_SWITCH,
	AH_CMD_DCD_IF_ACCESS_ENABLE_ALL_SW_IF,
	AH_CMD_DCD_SSID_ACCESS_ENABLE,
	AH_CMD_DCD_IF_SHOW_MANAGE,
	AH_CMD_DCD_IF_SHOW_MANAGE_SWITCH,
	AH_CMD_DCD_IF_SHOW_MANAGE_SWITCH_ALL,
	AH_CMD_DCD_IF_MGT_MANAGE_PING,
	AH_CMD_DCD_IF_MGT_MANAGE_SHOW,
	AH_CMD_DCD_SSID_SHOW_MANAGE,
	AH_CMD_DCD_SSID_ACCESS_ENABLE_ALL,
	AH_CMD_DCD_SSID_UAPSD,
	AH_CMD_DCD_SET_HIVE_ACCESS_ENABLE,
	AH_CMD_DCD_SET_HIVE_ACCESS_ENABLE_ALL,
	AH_CMD_DCD_HIVE_SHOW_MANAGE,
	AH_CMD_DCD_SET_ONCE_SCHEDULER,
	AH_CMD_DCD_UNSET_ONCE_SCHEDULER,
	AH_CMD_DCD_SET_RECURRENT_SCHEDULER,
	AH_CMD_DCD_SHOW_SCHEDULER,
	AH_CMD_DCD_SHOW_SCHED_DETAIL,
	AH_CMD_DCD_SSID_BIND_SCHE,
	AH_CMD_DCD_INTERFACE_BIND_SCHED,
	AH_CMD_DCD_SHOW_USER_PROFILE_SCHED,
	AH_CMD_DCD_SHOW_SSID_SCHED,
	AH_CMD_DCD_SHOW_INTERFACE_SCHED,
	AH_CMD_DCD_SHOW_SSID_SCHED_STAT,
	AH_CMD_DCD_SHOW_USER_SCHED_STAT,
	AH_CMD_DCD_SCHED_ENABLE,
	AH_CMD_DCD_HIVE_ACCESS_ENABLE,

	AH_CMD_DCD_ADMIN_MANAGE_IP,
	AH_CMD_DCD_SHOW_ADMIN_MANAGE_IP,
	AH_CMD_DCD_SET_ETHX_PROFILE_ATTR,
	AH_CMD_DCD_SET_ETHX_ACCESS_VALN_ATTR,
	AH_CMD_DCD_ETHX_MAC_LEARNING,
	AH_CMD_DCD_ETHX_MAC_IDLE_TIMEOUT,
	AH_CMD_DCD_SET_ETHX_STATIC_MAC,
	AH_CMD_DCD_SHOW_ETHX_MAC,
	AH_CMD_DCD_ETHX_UNSET_DYNAMIC_MAC,
	AH_CMD_DCD_ETHX_UNSET_DYNAMIC_ALL,
	AH_CMD_DCD_ETHX_UNSET_STATIC_ALL,
	AH_CMD_DCD_SHOW_BACKHAUL_MAC,

	AH_CMD_DCD_LOAD_ATTR_VLAN_AGAIN,

	// for non-switch
	AH_CMD_DCD_LLDP_CDP_ENABLE,
	AH_CMD_DCD_LLDP_CDP_RADIO_ENABLE,
	AH_CMD_DCD_LLDP_CDP_NUM_MAX,
	AH_CMD_DCD_LLDP_POWER,
	AH_CMD_DCD_CLEAR_LLDP_CDP_TABLE,
	AH_CMD_DCD_LLDP_CDP_IF_ENABLE,
	AH_CMD_DCD_SHOW_LLDP_CDP_INFO_FOR_NON_SWTICH,
	// for switch
	AH_CMD_DCD_LLDP_ENABLE,
	AH_CMD_DCD_CDP_ENABLE,
	AH_CMD_DCD_LLDP_NUM_MAX,
	AH_CMD_DCD_CDP_NUM_MAX,
	AH_CMD_DCD_LLDP_REINIT,
	AH_CMD_DCD_LLDP_FAST_START_COUNT,
	AH_CMD_DCD_CLEAR_LLDP_TABLE,
	AH_CMD_DCD_CLEAR_CDP_TABLE,
	AH_CMD_DCD_LLDP_IF_MODE,
	AH_CMD_DCD_CDP_IF_MODE,
	AH_CMD_DCD_SHOW_LLDP_CDP_INFO,
	AH_CMD_DCD_SHOW_IF_LLDP_CDP_MODE_LIST,
	AH_CMD_DCD_SHOW_IF_LLDP_CDP_MODE,
	// for common
	AH_CMD_DCD_LLDP_TIMER,
	AH_CMD_DCD_LLDP_HOLDTIME,

	AH_CMD_DCD_SHOW_DEVICE_STATUS,
	AH_CMD_DCD_SHOW_KVAR,
	AH_CMD_DCD_LIVE_DUMP,
	AH_CMD_DCD_SET_KVAR,
	AH_CMD_DCD_SHOW_KMEM,
	AH_CMD_DCD_SHOW_KLIST_SERIES,
	AH_CMD_DCD_SHOW_KLIST_PARATAXIS,
	AH_CMD_DCD_SHOW_KHASH,
	AH_CMD_DCD_SHOW_KSLAB,
	AH_CMD_DCD_SHOW_EVENT,

	/* add for dcd stats report */
	AH_CMD_DCD_STATS_REPORT_ENABLE,
	AH_CMD_DCD_STATS_REPORT_PERIOD,
	AH_CMD_DCD_STATS_REPORT_ALARM_THRES_INT,
	AH_CMD_DCD_STATS_REPORT_ALARM_THRES_CLT,
	AH_CMD_DCD_STATS_REPORT_CFG_SHOW,
	AH_CMD_DCD_STATS_REPORT_SHOW_DTL,
	AH_CMD_DCD_STATS_REPORT_CLR,

	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_SERVER_NAME,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_SERVER_NAME_DN,

	AH_CMD_DCD_SO,
	AH_CMD_DCD_SO_SSID_BIND,

	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_LIBSIP,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_LIBSIP_REDIR,
	AH_CMD_DCDAUTH_SUITEMETHOD_CWP_DFT_LANG,
	AH_CMD_DCDAUTH_SUITEMETHOD_MDM_ENROLL,
	AH_CMD_DCDAUTH_SUITEMETHOD_MDM_ROOT_URL,
	AH_CMD_DCDAUTH_SUITEMETHOD_MDM_USER_PWD,
	AH_CMD_DCDAUTH_SUITEMETHOD_MDM_BIND_OS,
	AH_CMD_DCDAUTH_SUITEMETHOD_MDM_SHOW,
	AH_CMD_DCDAUTH_SUITEMETHOD_MDM_POLL_STATUS,
	/* Add new commands for AirWatch */
	AH_CMD_DCDAUTH_SUITEMETHOD_MDM_API_KEY,
	AH_CMD_DCDAUTH_SUITEMETHOD_MDM_ENROLL_URL,
	AH_CMD_DCDAUTH_SUITEMETHOD_MDM_REST_API_URL,
	AH_CMD_DCDAUTH_SUITEMETHOD_MDM_AW_NONCOMP_UPID,
	AH_CMD_DCDAUTH_SUITEMETHOD_MDM_AW_NONCOMP_MSG_TYPE,
	AH_CMD_DCDAUTH_SUITEMETHOD_MDM_AW_NONCOMP_MSG_TITLE,
	AH_CMD_DCDAUTH_SUITEMETHOD_MDM_AW_NONCOMP_MSG_BODY,
	AH_CMD_DCDAUTH_SUITEMETHOD_MDM_AW_NONCOMP_DISCON_VLAN,

	AH_CMD_DCDAUTH_PU_EXTERNAL,
	AH_CMD_DCDAUTH_PU_EXTERNAL_RENEW,
	AH_CMD_DCDAUTH_PPSK_EXTERNAL_LOCAL_CO,
	AH_CMD_DCDAUTH_PPSK_NO_PARALLEL,
	AH_CMD_DCDAUTH_PU_MAC_BIND_SERVER_SO,
	AH_CMD_DCDAUTH_PPSK_MAC_BIND_ENABLE_SO,
	AH_CMD_DCDAUTH_PPSK_MAC_BIND_PPSKS_PER_MAC,
	AH_CMD_DCDAUTH_PPSK_MAC_BIND_MACS_PER_PPSK,
	AH_CMD_AUTH_EXEC_MAC_BIND_BY_PPSK,
	AH_CMD_AUTH_EXEC_MAC_BIND_BY_MAC,
	AH_CMD_AUTH_EXEC_MAC_BIND_BY_MAC_PPSK,
	AH_CMD_AUTH_SHOW_MAC_BIND,
	AH_CMD_DCDAUTH_PPSK_SELF_REG_ENABLE,
	AH_CMD_DCDAUTH_MAC_BASED_AUTH,
	AH_CMD_DCDAUTH_RADIUS_MSG_AUTHENTICATOR_ENABLE,

	AH_CMD_DCDAUTH_RADIUS_ACCT_SVRIP_SO,
	AH_CMD_DCDAUTH_RADIUS_CLIENT_FAIL_RETRY,

	AH_CMD_DCDAUTH_SUITEMETHOD_WPAPSKTKIP_SO_FORCE,
	AH_CMD_DCDAUTH_SUITEMETHOD_WPAPSKAES_SO_FORCE,
	AH_CMD_DCDAUTH_SUITEMETHOD_DOT1XWPATKIP_SO_FORCE,
	AH_CMD_DCDAUTH_SUITEMETHOD_DOT1XWPAAES_SO_FORCE,

	/* Ethernet 802.1X */
	AH_CMD_DCDAUTH_SUITEMETHOD_802DOT1X,
	AH_CMD_DCDAUTH_SUITEMETHOD_802DOT1X_PAEMAC,
	AH_CMD_DCDAUTH_SUITEMETHOD_MODE_PORT,
	AH_CMD_DCDAUTH_SUITEMETHOD_MODE_PORT_NO_FAIL_UPID,
	AH_CMD_DCDAUTH_SUITEMETHOD_MODE_HOST,
	AH_CMD_DCDAUTH_SUITEMETHOD_MODE_HOST_NO_MULT_DOM,
	AH_CMD_DCDAUTH_SUITEMETHOD_INITIAL_AUTH,

	AH_CMD_DCDAUTH_SUITEMETHOD_WPA2AES_11W,
	AH_CMD_DCDAUTH_SO_DFLTUSER,
	AH_CMD_DCDAUTH_SO_UPID_SEQUENCE,

	AH_CMD_SO_WEB_SERVER,
	AH_CMD_SO_WEB_SERVER_SSL_PORT,
	AH_CMD_SO_WEB_PAGE_CUSTOMIZE,
	AH_CMD_SO_WEB_FOLDER,
	AH_CMD_SO_NO_WEB_EXTERNAL,
	AH_CMD_SO_WEB_EXT_BIND_PPSK_SSID,
	AH_CMD_SO_WEB_EXT_WEB_DIR,
	AH_CMD_SO_WEB_EXT_LOGIN_PAGE,
	AH_CMD_SO_WEB_EXT_LOGIN_SCRIPT,
	AH_CMD_SO_WEB_EXT_LOGIN_HTTPS,
	AH_CMD_SO_WEB_EXT_AUTH_USER,
	AH_CMD_SSID_SHOW_WEB_SERVER_EXTERNAL,

	AH_CMD_DHCPS_SERVER_SO,
	AH_CMD_DHCPS_RENEWNAK_SO,
	AH_CMD_DCD_IF_ETH_SO,
	AH_CMD_DCD_IF_ETH_SO_SWITCH,
	AH_CMD_DCD_ETH_IP,
	AH_CMD_DCD_ETH_IP_SWITCH,
	AH_CMD_DCD_SO_ALLOW_ALL_UP,
	AH_CMD_DCD_SO_DENY_ACT_BAN,
	AH_CMD_DCD_SO_DENY_ACT_BAN_DISCON,
	AH_CMD_DCDAUTH_SO_BIND_ATTR_POLICY,
	AH_CMD_SO_NO_WEB_PAGE_CUSTOMIZE_OPT,
	AH_CMD_DHCPS_NOLEASE_SO,

	AH_CMD_DCDAUTH_RADIUS_ACCT_SVRIP_NO_SO,
	AH_CMD_DCDAUTH_RADIUS_SVR_INJECT,
	AH_CMD_DCDAUTH_USER_PROFILE_MAPPING_ID,
	AH_CMD_DCDAUTH_USER_PROFILE_MAPPING_VENDOR_ID,
	AH_CMD_DCDAUTH_USER_PROFILE_MAPPING_ENABLE,
	AH_CMD_DCD_SO_SHOW,
	AH_CMD_DCD_SHOW_CWP_PORT,
	AH_CMD_SO_WEB_SERVER_NO_PORT,
	AH_CMD_SO_WEB_SERVER_NO_SSL,
	AH_CMD_DCDAUTH_80211R_ENABLE,
	AH_CMD_DCDAUTH_80211R_MDID,

	AH_CMD_SCD_MGT_IP,
	AH_CMD_SCD_MGT_IP2,
#ifdef AH_SUPPORT_IPV6
	AH_CMD_IPV6_AUTOCONFIG_ENABLE,
	AH_CMD_SCD_MGT_IPV6,
	AH_CMD_SCD_MGT_IPV6_LINK_LOCAL,
	AH_CMD_IP_VERSION_PREFERENCE,
	AH_CMD_IPV6_DHCPC_ENABLE,
	AH_CMD_IPV6_DHCPC_SHOW,
#endif
	AH_CMD_SCD_MGT_DEFAULT_PREFIX,
	AH_CMD_SCD_MGT_DEFAULT_PREFIX2,
	AH_CMD_SCD_DOMAIN,
	AH_CMD_SCD_DNS_SVR,
	AH_CMD_SCD_SHOW_DNS,
	AH_CMD_SCD_SHOW_CLOCK,
	AH_CMD_SCD_SYS_CFG_DONE,
	AH_CMD_SCD_SYS_MULTICAST_PING,
	AH_CMD_SCD_SYS_ICMP_REDIRECT,
	AH_CMD_SCD_SYS_SHOW,

	AH_CMD_SCD_NTP_SVR,
	AH_CMD_SCD_NTP_ENABLE,
	AH_CMD_SCD_NTP_ITV,
	AH_CMD_SCD_NTP_TZN,
	AH_CMD_SCD_SHOW_INTL,
	AH_CMD_SCD_CLOCK,
	AH_CMD_SCD_NTP_DST, /* day light saving time */

	AH_CMD_SCD_ADD_USER,
	AH_CMD_SCD_ADD_SUPUSER,
	AH_CMD_SCD_PWD_LEN,
	AH_CMD_SCD_SHOW_LEN,
	AH_CMD_SCD_SHOW_ADM,
	AH_CMD_SCD_RESET_BUTTON_RESET_CONFIG,
	AH_CMD_SCD_SHOW_RESET_CONFIG_BY_BUTTON,

	AH_CMD_SCD_ADMIN_AUTH,
	AH_CMD_SCD_ADMIN_AUTH_RADIUS_METHOD,
	AH_CMD_SCD_SHOW_ADMIN_AUTH,
	AH_CMD_SCD_ADMIN_AUTH_RADIUS,

	AH_CMD_SCD_ADD_ROUTE,
	AH_CMD_SCD_ADD_ROUTE_HOST,
	AH_CMD_SCD_ADD_ROUTE_DEFAULT,
	AH_CMD_SCD_CLEAE_ROUTE_DEFAULT,
	AH_CMD_SCD_SHOW_IP_ROUTE,
#ifdef AH_SUPPORT_IPV6
	AH_CMD_SCD_ADD_IPV6_ROUTE,
	AH_CMD_SCD_ADD_IPV6_IF_ROUTE,
	AH_CMD_SCD_ADD_IPV6_ROUTE_DEFAULT,
	AH_CMD_SCD_ADD_IPV6_IF_ROUTE_DEFAULT,
#endif
	AH_CMD_SCD_LICENSE,/*add time bomb*/
	AH_CMD_SCD_SHOW_LICENSE,
	AH_CMD_SCD_SHOW_ALL_LICENSE,
	AH_CMD_SCD_TB_TIMER,

	AH_CMD_SCD_LOG_FACILITY,
	AH_CMD_SCD_LOG_CONSOLE_LEVEL,
	AH_CMD_SCD_LOG_TTY_LEVEL,
	AH_CMD_SCD_LOG_BUFFERED_LEVEL,
	AH_CMD_SCD_LOG_FLASH_LEVEL,
	AH_CMD_SCD_LOG_DEBUG,
	AH_CMD_SCD_LOG_HOSTNAME,
	AH_CMD_SCD_SHOW_LOGGING,
	AH_CMD_SCD_SNMP_SERVER,

	AH_CMD_SCD_SHOW_HWINFO,

	AH_CMD_SCD_SET_BL_DEVICE,
	AH_CMD_SCD_SET_BL_DEVICE_NO,
	AH_CMD_SCD_SET_BL_DEVICE_IP,
	AH_CMD_SCD_SET_BL_DEVICE_IP_NO,
	AH_CMD_SCD_SET_BL_SERVER,
	AH_CMD_SCD_SET_BL_SERVER_NO,
	AH_CMD_SCD_SET_BL_GATEWAY,
	AH_CMD_SCD_SET_BL_GATEWAY_NO,
	AH_CMD_SCD_SET_BL_VLAN,
	AH_CMD_SCD_SET_BL_VLAN_NO,
	AH_CMD_SCD_SET_BL_NVLAN,
	AH_CMD_SCD_SET_BL_NVLAN_NO,
	AH_CMD_SCD_SET_BL_FILE,
	AH_CMD_SCD_SET_BL_FILE_NO,

	AH_CMD_SCD_SET_BL_POE_MAX_POWER,
	AH_CMD_SCD_SET_BL_POE_MAX_POWER_NO,

	AH_CMD_SCD_SET_BL_PWD,
	AH_CMD_SCD_SET_BL_PWD_NO,

	/* snmp trap support */
	AH_CMD_SCD_LOG_TRAP_LEVEL,
	AH_CMD_SCD_LOG_TRAP_HOST,
	AH_CMD_SCD_LOG_TRAP_HOST_V3,
	AH_CMD_SCD_LOG_TRAP_SNMPV3_ADMIN,
	AH_CMD_SCD_LOG_TRAP_PATH,
	AH_CMD_SCD_LOG_TRAPHOST_SHOW,
	AH_CMD_SCD_IS_LOG_TRAP,
	AH_CMD_SCD_IS_PRINT_DEBUG_TIMESTAMP,
	AH_CMD_SCD_TEST_TRAP_CASE,
	AH_CMD_SCD_TEST_LOG_CASE,

	AH_CMD_SCD_CONSOLE_PAGE,
	AH_CMD_SCD_CONSOLE_TIMEOUT,
	AH_CMD_SCD_CONSOLE_OBSC_PWD,
	AH_CMD_SCD_SHOW_CONSOLE,

	AH_CMD_SCD_MPOLICY_INXP_C,
	AH_CMD_SCD_MPOLICY_INXP_S,
	AH_CMD_SCD_MPOLICY_INXP_IPV6_C,
	AH_CMD_SCD_MPOLICY_INXP_IPV6_S,
	AH_CMD_SCD_MPOLICY_INXP_IPV6_S_RANGE,
	AH_CMD_SCD_MPOLICY_INXP_IPV6_S_VLAN,
	AH_CMD_SCD_MPOLICY_INXP_IPV6_S_RANGE_VLAN,
	AH_CMD_SCD_MPOLICY_INXP_S_RANGE,
	AH_CMD_SCD_MPOLICY_INXP_S_VLAN,
	AH_CMD_SCD_MPOLICY_INXP_S_RANGE_VLAN,
	AH_CMD_SCD_MPOLICY_DNXP,
	AH_CMD_SCD_MPOLICY_DNXP_NOMADIC,
	AH_CMD_SCD_MPOLICY_DNXP_NOROAM,
	AH_CMD_SCD_MPOLICY_DNXP_MGTVLAN,
	AH_CMD_SCD_SHOW_MPOLICY,
	AH_CMD_SCD_SHOW_MPOLICY_CLEAR,

	AH_CMD_SCD_SHOW_TUNNEL_THRESHOLD,
	AH_CMD_SCD_SHOW_TUNNEL_THRESHOLD_SHOW,

	AH_CMD_SCD_SET_IP_TCPMSS_ENABLE,
	AH_CMD_SCD_SET_IP_TCPMSS_THRESHOLD,
	AH_CMD_SCD_SET_IP_TCPMSS_L3VPN_THRESHOLD,
	AH_CMD_SCD_SHOW_IP_TCPMSS,

	AH_CMD_SCD_AMRP_NBR,
	AH_CMD_SCD_AMRP_METRCS_TYPE,
	AH_CMD_SCD_AMRP_METRCS_POLLINTERVAL,
	AH_CMD_SCD_AMRP_METRCS_SHOW,
	AH_CMD_SCD_AMRP_ETHX_PRIO,

	AH_CMD_SCD_SAVE_FILES,
	/* CMD for radius-server */
	AH_CMD_SCD_SHOW_RADIUSD,
	AH_CMD_SCD_SHOW_RADIUSD_CACHE,
	AH_CMD_SCD_SHOW_RADIUSD_USER,
	AH_CMD_SCD_SHOW_RADIUSD_CLIENT,
	AH_CMD_SCD_RADIUSD_CLIENT,
	/* should delete */
	AH_CMD_SCD_RADIUSD_USER,

	AH_CMD_SCD_RADIUSD_PORT,
	AH_CMD_SCD_RADIUSD_AUTH,
	AH_CMD_SCD_RADIUSD_AUTH_TYPE,
	AH_CMD_SCD_RADIUSD_DFT_AUTH_TYPE,
	AH_CMD_SCD_RADIUSD_AUTH_TYPE_TLS,
	AH_CMD_SCD_RADIUSD_AUTH_TYPE_PEAP,
	AH_CMD_SCD_RADIUSD_MAP_VLAN,
	AH_CMD_SCD_RADIUSD_MAP_GROUP,
	AH_CMD_SCD_RADIUSD_MAP_REAUTH,
	AH_CMD_SCD_RADIUSD_MAP_GROUPNAME,
	AH_CMD_SCD_RADIUSD_LDAP_RETRY_INTERVAL,
	AH_CMD_SCD_RADIUSD_PRIMARY_RETRY_INTERVAL,
	AH_CMD_SCD_RADIUSD_LOCAL_RETRY_INTERVAL,
	AH_CMD_SCD_RADIUSD_AD_SERVER,
	AH_CMD_SCD_RADIUSD_AD_LOGIN,
	AH_CMD_SCD_RADIUSD_AD_DOMAIN,
	AH_CMD_SCD_RADIUSD_AD_ID_4DOMAIN,
	AH_CMD_SCD_RADIUSD_AD_FOREST,
	AH_CMD_SCD_RADIUSD_AD_BASEDN_4DOMAIN,
	AH_CMD_SCD_RADIUSD_AD_COU,
	AH_CMD_SCD_RADIUSD_AD_TLS,
	AH_CMD_SCD_RADIUSD_AD_SMB_LDAP_SASL_WRAPPING,
	/* support Open Directory */
	AH_CMD_SCD_RADIUS_OD_LOGIN,
	AH_CMD_SCD_RADIUS_OD_DOMAIN,
	AH_CMD_SCD_RADIUS_OD_BINDDN,
	AH_CMD_SCD_RADIUS_OD_BASEDN,
	AH_CMD_SCD_RADIUS_OD_TLS,
	/* support proxy */
	AH_CMD_SCD_RADIUS_PROXY_RETRY,
	AH_CMD_SCD_RADIUS_PROXY_DEADTIME,
	AH_CMD_SCD_RADIUS_PROXY_FORMAT,
	AH_CMD_SCD_RADIUS_PROXY_OPERATOR_NAME,
	AH_CMD_SCD_RADIUS_PROXY_SERVER_OLD,
	AH_CMD_SCD_RADIUS_PROXY_AUTHPORT_OLD,
	AH_CMD_SCD_RADIUS_PROXY_ACCTPORT_OLD,
	AH_CMD_SCD_RADIUS_PROXY_SERVER,
	AH_CMD_SCD_RADIUS_PROXY_AUTHPORT,
	AH_CMD_SCD_RADIUS_PROXY_ACCTPORT,
	AH_CMD_SCD_RADIUS_PROXY_REALM,
	AH_CMD_SCD_RADIUS_PROXY_REALM_NOSTRIP,
	AH_CMD_SCD_RADIUS_SHOW_PROXY,
	AH_CMD_SCD_RADIUS_SHOW_DOMAIN_JOINED,
	AH_CMD_SCD_ADS_INFO,
	/* support radsecproxy */
	AH_CMD_SCD_RADSEC_PROXY_ENABLE,
	AH_CMD_SCD_RADSEC_PROXY_AUTHPORT,
	AH_CMD_SCD_RADSEC_PROXY_ACCTPORT,
	AH_CMD_SCD_RADSEC_PROXY_TLSPORT,
	AH_CMD_SCD_RADSEC_PROXY_SERVER,
	AH_CMD_SCD_RADSEC_PROXY_SERVER_TLSPORT,
	AH_CMD_SCD_RADSEC_PROXY_REALM,
	AH_CMD_SCD_RADSEC_CLIENT,
	AH_CMD_SCD_RADSEC_RESTART,
	AH_CMD_SCD_RADSEC_TEST,
	AH_CMD_SCD_RADSEC_SHOW,
	AH_CMD_SCD_RADSEC_CERTCLEAR,
	AH_CMD_SCD_RADSEC_CLEAR_CERTKEY,
	AH_CMD_SCD_RADSEC_CLRROOTCA,
	AH_CMD_SCD_RADSEC_DEBUG,
	AH_CMD_SCD_SERVICE_RADSEC_PROXY_ENABLE,
	AH_CMD_SCD_RADSEC_EXEC_IDM_TEST,
	AH_CMD_SCD_RADSEC_SHOW_IDM,
	AH_CMD_SCD_RADSEC_PROXY_DYNAMIC_AUTH,
	AH_CMD_SCD_RADSEC_SHOW_IDM_CERT,
	AH_CMD_SCD_SHOW_RADSEC_ELCT_POOL,
	AH_CMD_SCD_SET_MAX_SCORE_DIFF,
	AH_CMD_SCD_RADSEC_PROXY_SERVER_NUM_LIMIT,
	AH_CMD_SCD_RADSEC_PROXY_SET_NAS_NUM_LIMIT,
	AH_CMD_SCD_RADSEC_SHOW_EXCESS_NUM,
	/* support library SIP2 */
	AH_CMD_SCD_RADIUS_LIBSIP_SERVER,
	AH_CMD_SCD_RADIUS_LIBSIP_PORT,
	AH_CMD_SCD_RADIUS_LIBSIP_LOGIN_ENABLE,
	AH_CMD_SCD_RADIUS_LIBSIP_LOGIN,
	AH_CMD_SCD_RADIUS_LIBSIP_OID,
	AH_CMD_SCD_RADIUS_LIBSIP_DELIMITER,
	AH_CMD_SCD_RADIUS_LIBSIP_RETRIES,
	AH_CMD_SCD_RADIUS_LIBSIP_POLICY,
	AH_CMD_SCD_RADIUS_LIBSIP_POLICY_CMP_NUM,
	AH_CMD_SCD_RADIUS_LIBSIP_POLICY_DEFAULT,
	AH_CMD_SCD_RADIUS_LIBSIP_POLICY_MOVING,
	AH_CMD_SCD_RADIUS_LIBSIP_POLICY_DISPLAY,
	AH_CMD_SCD_RADIUS_LIBSIP_POLICY_BIND,
	AH_CMD_SCD_RADIUS_LIBSIP_EXE_USER_TEST,
	/* support LDAP server */
	AH_CMD_SCD_RADIUSD_OPENLDAP_AUTH,
	AH_CMD_SCD_RADIUSD_OPENLDAP_SERVER,
	AH_CMD_SCD_RADIUSD_OPENLDAP_BASEDN,
	AH_CMD_SCD_RADIUSD_OPENLDAP_ID,
	AH_CMD_SCD_RADIUSD_OPENLDAP_PORT,
	AH_CMD_SCD_RADIUSD_OPENLDAP_PROT,
	AH_CMD_SCD_RADIUSD_OPENLDAP_FILTER,
	AH_CMD_SCD_RADIUSD_OPENLDAP_FILTER_NEW,
	AH_CMD_SCD_RADIUSD_OPENLDAP_FILTER_NO_STRIP,
	AH_CMD_SCD_RADIUSD_OPENLDAP_EDIR,
	AH_CMD_SCD_RADIUSD_OPENLDAP_EDIR_CHECK,
	AH_CMD_SCD_RADIUS_OD_FILTER,
	AH_CMD_SCD_RADIUS_OD_FILTER_NO_STRIP,
	AH_CMD_SCD_RADIUSD_LOCAL,
	AH_CMD_SCD_RADIUSD_MAX_SESSION,
	AH_CMD_SCD_RADIUSD_SESS_AGE_TIMEOUT,
	AH_CMD_SCD_RADIUSD_SHOW_ACT_SESS,
	AH_CMD_SCD_RADIUSD_CACHE,
	AH_CMD_SCD_RADIUSD_REQ_MSG_AUTH,
	AH_CMD_SCD_RADIUSD_ENABLE,
	AH_CMD_SCD_RADIUSD_CLEARCACHE,
	AH_CMD_SCD_RADIUSD_CERTSHOW,
	AH_CMD_SCD_RADIUSD_CERTCLEAR_OLD,
	AH_CMD_SCD_RADIUSD_CERTCLEAR,
	AH_CMD_SCD_RADIUSD_ACCT,
	AH_CMD_SCD_RADIUSD_ACCT_PORT,
	AH_CMD_SCD_RADIUSD_AUTO_SHARED_SECRET,
	AH_CMD_SCD_RADIUSD_EXEC_NET,
	AH_CMD_SCD_RADIUSD_EXEC_NTLM_AUTH,
	AH_CMD_SCD_RADIUSD_EXEC_LDAP_SEARCH,
	AH_CMD_SCD_RADIUSD_EXEC_LDAP_TREE,
	AH_CMD_SCD_RADIUSD_EXEC_NET_JOIN_NEW,
	AH_CMD_SCD_RADIUSD_RESTART,
	AH_CMD_SCD_RADIUSD_DEBUG,
	AH_CMD_SCD_CONFIG_VERSION,
	AH_CMD_SCD_SHOW_CONFIG_VERSION,
	AH_CMD_SCD_ENABLE_CONSOLE,
	/* CMD for temperature */
	AH_CMD_SCD_SHOW_SYSTEM_TEMPERATURE_PARMS,
	AH_CMD_SCD_SET_SYSTEM_TEMPERATURE_PARMS,
	AH_CMD_SCD_DEBUG_SYSTEM_TEMPERATURE_PARMS,
	/* CMD for fans controller */
	AH_CMD_SCD_SHOW_SYSTEM_FANS_PARMS,
	AH_CMD_SCD_SET_SYSTEM_FANS_PARMS,
	AH_CMD_SCD_DEBUG_SYSTEM_FANS_PARMS,
	/* cmd for track ip */
	AH_CMD_SCD_TRACK_GROUP_IP,
	AH_CMD_SCD_TRACK_GROUP_DEFAULT_GW,
	AH_CMD_SCD_TRACK_GROUP_ACTION,
	AH_CMD_SCD_TRACK_GROUP_ACTION_MESH,
	AH_CMD_SCD_TRACK_GROUP_MULTI_LOGIC,
	AH_CMD_SCD_TRACK_GROUP_ENABLE,
	AH_CMD_SCD_TRACK_GROUP_USING_FOR_WAN_TESTING,
	AH_CMD_SCD_TRACK_GROUP_INTERVAL,
	AH_CMD_SCD_TRACK_GROUP_TIMEOUT,
	AH_CMD_SCD_TRACK_GROUP_RETRY,
	AH_CMD_SCD_SHOW_TRACK_GROUP,
	AH_CMD_SCD_SSH_TUNNEL,
	AH_CMD_SCD_SHOW_SSH_TUNNEL,
	AH_CMD_SCD_EXEC_SSH_CLIENT,
	AH_CMD_SCD_CLEAR_SSH_KNOWNHOST,
	AH_CMD_SCD_LOGIN_BANNER,

	AH_CMD_SCD_CGIC_DBG,
	AH_CMD_SCD_CGIC_DBG2,
	AH_CMD_SCD_SHOW_CGIC_DBG,
	AH_CMD_SCD_WEB_SERVER_DBG,
	AH_CMD_SCD_WEB_SERVER_DBG2,
	AH_CMD_SCD_SHOW_WEB_SERVER_DBG,
	AH_CMD_SCD_NTP_DBG,

	/* SCD CMD for DHCPS */
	AH_CMD_SCD_DHCPS_SERVER,
	AH_CMD_SCD_DHCPS_SERVER_SWITCH,
	AH_CMD_SCD_DHCPS_RELAY,
	AH_CMD_SCD_DHCPS_RELAY_SWITCH,
	AH_CMD_SCD_DHCPS_RELAY_SHOW,
	AH_CMD_SCD_DHCPS_RELAY_SHOW_SWITCH,
	AH_CMD_SCD_DHCPS_AUTH_FLAG,
	AH_CMD_SCD_DHCPS_AUTH_FLAG_SWITCH,
	AH_CMD_SCD_DHCPS_RENEWNAK,
	AH_CMD_SCD_DHCPS_LEASE,
	AH_CMD_SCD_DHCPS_LEASE_SWITCH,
	AH_CMD_SCD_DHCPS_MTU,
	AH_CMD_SCD_DHCPS_MTU_SWITCH,
	AH_CMD_SCD_DHCPS_GW,
	AH_CMD_SCD_DHCPS_GW_SWITCH,
	AH_CMD_SCD_DHCPS_DNS,
	AH_CMD_SCD_DHCPS_DNS_SWITCH,
	AH_CMD_SCD_DHCPS_OPTIONS_SINGLE_IP,
	AH_CMD_SCD_DHCPS_OPTIONS_SINGLE_IP_SWITCH,
	AH_CMD_SCD_DHCPS_NTP,
	AH_CMD_SCD_DHCPS_NTP_SWITCH,
	AH_CMD_SCD_DHCPS_WINS,
	AH_CMD_SCD_DHCPS_WINS_SWITCH,
	AH_CMD_SCD_DHCPS_WINS_HIDDEN,
	AH_CMD_SCD_DHCPS_WINS_HIDDEN_SWITCH,
	AH_CMD_SCD_DHCPS_HM,
	AH_CMD_SCD_DHCPS_HM_SWITCH,
	AH_CMD_SCD_DHCPS_HMNAME,
	AH_CMD_SCD_DHCPS_HMNAME_SWITCH,
	AH_CMD_SCD_DHCPS_DOMAIN,
	AH_CMD_SCD_DHCPS_DOMAIN_SWITCH,
	AH_CMD_SCD_DHCPS_PORT,
	AH_CMD_SCD_DHCPS_MASK,
	AH_CMD_SCD_DHCPS_MASK_SWITCH,
	AH_CMD_SCD_DHCPS_RANGE,
	AH_CMD_SCD_DHCPS_RANGE_SWITCH,
	AH_CMD_SCD_DHCPS_OPTION_INT,
	AH_CMD_SCD_DHCPS_OPTION_INT_SWITCH,
	AH_CMD_SCD_DHCPS_OPTION_STR,
	AH_CMD_SCD_DHCPS_OPTION_STR_SWITCH,
	AH_CMD_SCD_DHCPS_OPTION_IP,
	AH_CMD_SCD_DHCPS_OPTION_IP_SWITCH,
	AH_CMD_SCD_DHCPS_OPTION_HEX,
	AH_CMD_SCD_DHCPS_OPTION_HEX_SWITCH,
	AH_CMD_SCD_DHCPS_VENDOR_NAME,
	AH_CMD_SCD_DHCPS_VENDOR_NAME_SWITCH,
	AH_CMD_SCD_DHCPS_VENDOR_SPECIFIC_STR,
	AH_CMD_SCD_DHCPS_VENDOR_SPECIFIC_STR_SWITCH,
	AH_CMD_SCD_DHCPS_VENDOR_SPECIFIC_IP,
	AH_CMD_SCD_DHCPS_VENDOR_SPECIFIC_IP_SWITCH,
	AH_CMD_SCD_DHCPS_VENDOR_SPECIFIC_INT,
	AH_CMD_SCD_DHCPS_VENDOR_SPECIFIC_INT_SWITCH,
	AH_CMD_SCD_DHCPS_VENDOR_SPECIFIC_HEX,
	AH_CMD_SCD_DHCPS_VENDOR_SPECIFIC_HEX_SWITCH,
	AH_CMD_SCD_DHCPS_SHOW,
	AH_CMD_SCD_DHCPS_SHOW_SWITCH,
	AH_CMD_SCD_DHCPS_SHOW_ALL,
	AH_CMD_SCD_DHCPS_SHOW_ALL_SWITCH,
	AH_CMD_SCD_DHCPS_CLEAR,
	AH_CMD_SCD_DHCPS_CLEAR_SWITCH,
	AH_CMD_SCD_DHCPS_CLEAR_IP,
	AH_CMD_SCD_DHCPS_CLEAR_IP_SWITCH,
	AH_CMD_SCD_DHCPS_CLEAR_MAC,
	AH_CMD_SCD_DHCPS_CLEAR_MAC_SWITCH,
	AH_CMD_SCD_DHCPS_LEASE_NUM,
	AH_CMD_SCD_DHCPS_LEASE_NUM_SWITCH,
	AH_CMD_SCD_DHCPS_RELAY_MAXHOPS,
	AH_CMD_SCD_DHCPS_RELAY_MAXHOPS_SWITCH,
	AH_CMD_SCD_DHCPS_RELAY_MAXHOPS_SHOW,
	AH_CMD_SCD_DHCPS_RELAY_MAXHOPS_SHOW_SWITCH,
	AH_CMD_SCD_DHCPS_RESERVED_BINDING,
	AH_CMD_SCD_DHCPS_RESERVED_BINDING_SWITCH,
	AH_CMD_SCD_DHCPS_RESERVED_ADDRESS,
	AH_CMD_SCD_DHCPS_RESERVED_ADDRESS_SWITCH,
	AH_CMD_SCD_DHCPS_RESERVED_SHOW_BINDING,
	AH_CMD_SCD_DHCPS_RESERVED_SHOW_BINDING_SWITCH,
	AH_CMD_SCD_DHCPS_RESERVED_SHOW_ADDRESS,
	AH_CMD_SCD_DHCPS_RESERVED_SHOW_ADDRESS_SWITCH,

#ifdef AH_SUPPORT_OPENDNS
	AH_CMD_SCD_DNS_SHOW_CACHE,
#endif

	/* BGD module */
	AH_CMD_BGD_ENABLE,
	AH_CMD_BGD_VLAN_GROUP_DISPLAY,
	AH_CMD_BGD_FILTER_DISPLAY,
	AH_CMD_BGD_STATUS_DISPLAY,
	AH_CMD_BGD_LOCAL_SERVICE_DISPLAY,
	AH_CMD_BGD_REMOTE_SERVICE_DISPLAY,
	AH_CMD_BGD_TEST_PEER_BDD,
	AH_CMD_BGD_TEST_VLAN,
	AH_CMD_BGD_TEST_SHOW,
	AH_CMD_BGD_NEIGHBOR,
	AH_CMD_BGD_VLAN,
	AH_CMD_BGD_VLAN_GROUP,
	AH_CMD_BGD_PRIORITY,
	AH_CMD_BGD_REALM,
	AH_CMD_BGD_FILTER_ORGANIZE,
	AH_CMD_MDNSD_SHOW,
	AH_CMD_MDNSD_SHOW_COUNTER,
	AH_CMD_MDNSD_CLR_COUNTER,
	AH_CMD_BGD_VLAN_DISTRIBUTE_ENABLE,    /* HOS-5519 */
	AH_CMD_BGD_VLAN_DISTRIBUTE_SHOW,
	AH_CMD_BGD_TEST_VLAN_DISTRIBUTE_HELLO,
	AH_CMD_BGD_TEST_VLAN_DISTRIBUTE_INTERVAL,

	AH_CMD_MDNSD_DEBUG,

	/* SCD CMD for configuration rollback */
	AH_CMD_SCD_CONF_ROLBCK_ENABLE,
	AH_CMD_SCD_CONF_ROLBCK_POINT,
	AH_CMD_SCD_CONF_ROLBCK_POINT_MANUAL,
	AH_CMD_SCD_CONF_ROLBCK_NOW,
	AH_CMD_SCD_SHOW_CONF_ROLBCK,
	AH_CMD_SCD_CLEAR_CONF_ROLBCK,

	/* SCD CMD for DNS (Branch Router) */
	AH_CMD_SCD_IFACE_DNS_SERVER_MODE,
	AH_CMD_SCD_IFACE_DNS_SERVER_MODE_SWITCH,
	AH_CMD_SCD_IFACE_DNS_SERVER_EXT_RESOLVE,
	AH_CMD_SCD_IFACE_DNS_SERVER_EXT_RESOLVE_SWITCH,
	AH_CMD_SCD_IFACE_DNS_SERVER_INT_RESOLVE,
	AH_CMD_SCD_IFACE_DNS_SERVER_INT_RESOLVE_SWITCH,
	AH_CMD_SCD_IFACE_DNS_SERVER_INT_DOMAIN_NAME,
	AH_CMD_SCD_IFACE_DNS_SERVER_INT_DOMAIN_NAME_SWITCH,
	AH_CMD_SCD_IFACE_DNS_SERVER_OPENDNS_DEVICE_ID,
	AH_CMD_SCD_IFACE_DNS_SERVER_OPENDNS_DEVICE_ID_SWITCH,
	AH_CMD_SCD_IFACE_DNS_SERVER_ENABLE,
	AH_CMD_SCD_IFACE_DNS_SERVER_ENABLE_SWITCH,
#ifdef AH_SUPPORT_OPENDNS
	AH_CMD_SCD_IFACE_DNS_SERVER_CACHE_SIZE,
	AH_CMD_SCD_IFACE_DNS_SERVER_DBG_LEVEL,
	AH_CMD_SCD_IFACE_DNS_SERVER_DBG_CLIENT_IP,
	AH_CMD_SCD_IFACE_DNS_SERVER_DBG_DOMAIN_NAME,
#endif

	/* need by old CWP */
	AH_CMD_DHCPS_SERVER,
	AH_CMD_DHCPS_SHOW,
	AH_CMD_DHCPS_SHOW_SSID,
	AH_CMD_DHCPS_DEBUG,
	AH_CMD_DHCPS_RENEWNAK,
	AH_CMD_DHCPS_RENEWNAK2,
	AH_CMD_DHCPS_NOLEASE,
	AH_CMD_DHCPS_NOPORT,
	AH_CMD_DNS_SERVER,
	AH_CMD_DNS_SHOW,
	AH_CMD_DNS_SHOW_SSID,
	AH_CMD_DNS_NOTTL,
	AH_CMD_DNS_NOPORT,
	AH_CMD_DNS_DEBUG,


	AH_CMD_DHCPC_ENABLE,  /* dhcp client enable */
	AH_CMD_DHCPC_ENABLE_SWITCH,
	AH_CMD_DHCPC_OLD_CUSOPT,  /* dhcp client custom opt */
	AH_CMD_DHCPC_OLD_CUSOPT_SWITCH,
	AH_CMD_DHCPC_OLD_CUSOPT_PPSKSRV,  /* dhcp client custom opt for ppsk server*/
	AH_CMD_DHCPC_OLD_CUSOPT_PPSKSRV_SWITCH,
	AH_CMD_DHCPC_OLD_CUSOPT_RADSRV,   /* dhcp client custom opt for radius server*/
	AH_CMD_DHCPC_OLD_CUSOPT_RADSRV_SWITCH,
	AH_CMD_DHCPC_OLD_CUSOPT_RAD_ACCT, /* dhcp client custom opt for radius acct server*/
	AH_CMD_DHCPC_OLD_CUSOPT_RAD_ACCT_SWITCH,
	AH_CMD_DHCPC_CUSOPT,  /* dhcp client custom opt */
	AH_CMD_DHCPC_CUSOPT_SWITCH,
	AH_CMD_DHCPC_CUSOPT_IP,  /* dhcp client custom opt */
	AH_CMD_DHCPC_CUSOPT_IP_SWITCH,
	AH_CMD_DHCPC_CUSOPT_PPSKSRV,  /* dhcp client custom opt for ppsk server*/
	AH_CMD_DHCPC_CUSOPT_PPSKSRV_SWITCH,
	AH_CMD_DHCPC_CUSOPT_RADSRV,   /* dhcp client custom opt for radius server*/
	AH_CMD_DHCPC_CUSOPT_RADSRV_SWITCH,
	AH_CMD_DHCPC_CUSOPT_RAD_ACCT, /* dhcp client custom opt for radius acct server*/
	AH_CMD_DHCPC_CUSOPT_RAD_ACCT_SWITCH,
	AH_CMD_DHCPC_RAND,  /* dhcp client random */
	AH_CMD_DHCPC_PREFER_SUBNET,  /* dhcp client prefer subnet */
	AH_CMD_DHCPC_PREFER_SUBNET_SWITCH,
	AH_CMD_DHCPC_TIMEOUT,
	AH_CMD_DHCPC_TIMEOUT_SWITCH,
	AH_CMD_DHCPC_PRIMARY,
	AH_CMD_DHCPC_ADDRESS_ONLY,
	AH_CMD_DHCPC_ADDRESS_ONLY_SWITCH,
	AH_CMD_DHCPC_SHOW,
	AH_CMD_DHCPC_SHOW_SWITCH,
	AH_CMD_SCD_DHCPC_DEBUG,
	AH_CMD_DHCP_PROBE,
	AH_CMD_DHCP_PROBE_SHOW,
	AH_CMD_DHCP_CHECK_STATUS_ENABLE,
	AH_CMD_DHCP_CHECK_STATUS_VLAN,
	AH_CMD_DHCP_CHECK_STATUS_INTERVAL,
	AH_CMD_DHCP_CHECK_STATUS_TIMEOUT,
	AH_CMD_DHCP_CHECK_STATUS_RETRY,
	AH_CMD_DHCP_CHECK_STATUS_SHOW,

	/* CMD for LCS */
	AH_CMD_LCS_ENG_ENABLE,
	AH_CMD_LCS_ENG_EKAHAU_ENABLE,
	AH_CMD_LCS_ENG_RPT_ENABLE,
	AH_CMD_LCS_ENG_SRV_SET,
	AH_CMD_LCS_ENG_TZSP_SRV_SET,
	AH_CMD_LCS_ENG_EKAHAU_SRV_SET,
	AH_CMD_LCS_ENG_TZSP_MCAST_MAC_SET,
	AH_CMD_LCS_ENG_EKAHAU_MCAST_MAC_SET,
	AH_CMD_LCS_ENG_STAT_SHOW,
	AH_CMD_LCS_ENG_COUNTER_SHOW,
	AH_CMD_LCS_ENG_COUNTER_CLEAR,
	AH_CMD_LCS_SHOW_DBG,
	AH_CMD_LCS_RSSI_WEIGHT_SET,
	AH_CMD_LCS_RATE_LIMIT_SET,

	/* CMD for LTR */
	AH_CMD_LTR_TRACK_ENABLE,
	AH_CMD_LTR_SUPPRESS_SET,
	AH_CMD_LTR_STAT_SHOW,
	AH_CMD_LTR_MLIST_SET,
	AH_CMD_LTR_OLIST_SET,
	AH_CMD_LTR_TLIST_SHOW,
	AH_CMD_LTR_RSSI_SHOW,
	AH_CMD_LTR_RSSI_SHOW_MAC,
	AH_CMD_LTR_RSSI_SHOW_OUI,
	AH_CMD_LTR_STATE_DUMP,
	AH_CMD_LTR_DRV_STATS_DUMP,
	AH_CMD_LTR_RSSI_RPT_INTVL_SET,
	AH_CMD_LTR_RSSI_UPD_THR_SET,
	AH_CMD_LTR_RSSI_VLD_PRD_SET,
	AH_CMD_LTR_LIST_MATCH_SET,
	AH_CMD_LTR_RSSI_HOLD_TIME_SET,

	AH_CMD_ALG_SERVICE,
	AH_CMD_ALG_SET_QOS,
	AH_CMD_ALG_SET_INACTIVE_TIMEOUT,
	AH_CMD_ALG_SET_MAX_CALL_DURATION,
	AH_CMD_ALG_SHOW,
	AH_CMD_ALG_SHOW_SIP_ROAMING,

	/*Command for VPN*/
	AH_CMD_VPN_ENABLE,
	AH_CMD_VPN_ENTRY_CREATE,
	AH_CMD_VPN_XAUTH_POOL_CREATE,
	AH_CMD_VPN_XAUTH_POOL_ADD,
	AH_CMD_VPN_IP_POOL,
	AH_CMD_VPN_CLIENT,
	AH_CMD_VPN_SERVER,
	AH_CMD_VPN_IKE_ENCY,
	AH_CMD_VPN_IKE_HASH,
	AH_CMD_VPN_IKE_LIFETIME,
	AH_CMD_VPN_IKE_DH,
	AH_CMD_VPN_IKE_PFS,
	AH_CMD_VPN_IKE_MY_ID,
	AH_CMD_VPN_IKE_PEER_ID,
	AH_CMD_VPN_IKE_AUTH_METHOD,
	AH_CMD_VPN_IKE_NAT_T,
	AH_CMD_VPN_IKE_DPD,
	AH_CMD_VPN_AMRP_HEARTBEAT,
	AH_CMD_VPN_SHOW_IKE_SA,
	AH_CMD_VPN_GET_CONFIG,
	AH_CMD_VPN_SHOW_IPSEC_SA,
	AH_CMD_VPN_SHOW_SP,
	AH_CMD_VPN_CLEAR_SA,
	AH_CMD_VPN_INIT_CONTACT,
	AH_CMD_VPN_CLEAR_EVENT,
	AH_CMD_VPN_TUNNEL_POL_PWD,
	AH_CMD_VPN_TUNNEL_POL_CLIENT,
	AH_CMD_VPN_TUNNEL_POL_SERVER,
	AH_CMD_VPN_SHOW_IPSEC_TUNNEL,
	AH_CMD_VPN_SHOW_VPN_SHARE_MEM,
	AH_CMD_VPN_SHOW_TUNNEL_POLICY,
	AH_CMD_VPN_IKE_AUTH_METHOD_PSK,
	AH_CMD_VPN_IKE_SUPPORT_THIRD_GW,
	AH_CMD_VPN_SHOW_THIRD_GW_FLAG,
	AH_CMD_VPN_SHOW_TUNNEL_ID,
	AH_CMD_VPN_CLEAR_CERT_KEY,
	AH_CMD_VPN_SHOW_LAYER3_TUNNEL,
	AH_CMD_VPN_L3_TUNNEL_EXCEPTION,
	AH_CMD_VPN_SHOW_L3_TUNNEL_EXCEPTION,
	AH_CMD_VPN_SHOW_SOCKET,
	AH_CMD_VPN_REMOTE_ACCESS_CREATE,
	AH_CMD_VPN_TUNNEL_GROUP_ADD,
	AH_CMD_VPN_IKE_PHASE1_MODE,
	AH_CMD_VPN_SHOW_XAUTH_USER,

	/*Process Memory Track*/
	AH_CMD_MT_SHOW_SETTING,
	AH_CMD_MT_SET_CONFIG,
	AH_CMD_MT_SET_FILTER,
	AH_CMD_MT_SET_FILTER_DURATION,
	AH_CMD_MT_SET_SORT,
	AH_CMD_MT_SET_SORT_DEFAULT,
	AH_CMD_MT_QUERY,
	AH_CMD_MT_SET_SIMPLE_DISPLAY,
	/*End Memory Track*/

	/*Process Capwap Server*/
	AH_CMD_CS_DEBUG,
	AH_CMD_CS_ENABLE,
	AH_CMD_CS_HIVE_ENABLE,
	AH_CMD_CS_SHOW,
	AH_CMD_CS_SET_PORT,
	/*End Capwap Server*/

	/**/
	AH_CMD_WEBUI_TEST,
	AH_CMD_WEBUI_SHOW_USER_INFO,
	AH_CMD_WEBUI_SHOW_RADIUS_USER_INFO,
	AH_CMD_WEBUI_SHOW_MSG_INFO,

	/*webui*/
	AH_CMD_WEBUI_SHOW_USR_CFG,
	AH_CMD_WEBUI_SHOW_HIVE_INFO,
	AH_CMD_WEBUI_SHOW_HIVE_OFFLINE,
	AH_CMD_WEBUI_SHOW_CLNT_CFG,
	AH_CMD_WEBUI_SHOW_CLNT_FILE,
	AH_CMD_WEBUI_ENABLE,
	AH_CMD_WEBUI_CLEAR_USER,
	AH_CMD_WEBUI_SHOW_RADIUS_INFO,
	AH_CMD_WEBUI_SET_RADIUS_TMP_USER_INTERVAL,
	AH_CMD_WEBUI_TV_RES_MAP,
	AH_CMD_WEBUI_SHOW_TV_RES_MAP,
	AH_CMD_WEBUI_TV_TEST_SESS,
	AH_CMD_WEBUI_TV_TEST_GET_RES_MAP,
	AH_CMD_WEBUI_TV_SHOW_CLASS,
	AH_CMD_WEBUI_TV_PROMPT_BLOCKED_URL,

	AH_CMD_WEBUI_TV_TEST_ADD,
	AH_CMD_WEBUI_TV_TEST_QUERY,
	AH_CMD_WEBUI_TV_TEST_DEL,
	AH_CMD_WEBUI_TV_TEST_SET_FOLLOW_ME,
	AH_CMD_WEBUI_TV_TEST_ADD_FOLLOW_ME,
	AH_CMD_WEBUI_TV_TEST_SHOW,
	AH_CMD_WEBUI_TV_ALG,
	AH_CMD_WEBUI_TV_ALG_CAPTURE,

	/* AirScreen */
	AH_CMD_ASD_ACTION_LOCALBAN,
	AH_CMD_ASD_ACTION_DEAUTH,
	AH_CMD_ASD_ACTION_REPORT,
	AH_CMD_ASD_RULE,
	AH_CMD_ASD_RULE_SOURCE,
	AH_CMD_ASD_RULE_BEHAVIOR,
	AH_CMD_ASD_RULE_ACTION,
	AH_CMD_ASD_RULE_DEBUG,
	AH_CMD_ASD_RULE_DEBUG_SHOW,
	AH_CMD_ASD_RULE_SSID,
	AH_CMD_ASD_RULE_UPID,
	AH_CMD_ASD_RULE_SHOW,
	AH_CMD_ASD_RULE_SRC_SHOW,
	AH_CMD_ASD_BEHAVIOR_SHOW,
	AH_CMD_ASD_CARRIER_SHOW,
	AH_CMD_ASD_ACTION_SHOW,
	AH_CMD_ASD_ACTION_EXEC,
	AH_CMD_ASD_INSTANCE_SHOW,

	AH_CMD_ASD_BEHAVIOR_RECONNECTION,
	AH_CMD_ASD_NO_BEHAVIOR_RECONNECTION,

	AH_CMD_ASD_CARRIER_CLIENT,
	AH_CMD_ASD_CARRIER_CLIENT_OUI,
	AH_CMD_ASD_CARRIER_CLIENT_AUTH,
	AH_CMD_ASD_CARRIER_CLIENT_AUTH_WPA,
	AH_CMD_ASD_NO_CARRIER_CLIENT_AUTH,
	AH_CMD_ASD_CARRIER_CLIENT_RSSI,
	AH_CMD_ASD_CARRIER_CLIENT_COMMENT,


	/* nbrcom */
	AH_CMD_NBRCOM_SHOW_NEIGHBOR,
	AH_CMD_NBRCOM_CLEAR_NEIGHBOR,
	AH_CMD_NBRCOM_CLEAR_NEIGHBOR_COUNT,
	AH_CMD_NBRCOM_ROAMING_PORT,
	AH_CMD_NBRCOM_NEIGHBOR_STATIC_INCLUDE,
	AH_CMD_NBRCOM_NEIGHBOR_STATIC_INCLUDEIPV6,
	AH_CMD_NBRCOM_NEIGHBOR_STATIC_EXCLUDE,
	AH_CMD_NBRCOM_NEIGHBOR_QUERY,
	AH_CMD_NBRCOM_NEIGHBOR_DEBUG,

	AH_CMD_DELAY_EXECUTE_COMMAND,

	/* mem-trace enhancement */
	AH_CMD_MT_PLUS_CLEAR,
	AH_CMD_MT_PLUS_ENABLE,
	AH_CMD_MT_PLUS_DISABLE,
	AH_CMD_MT_PLUS_LIMIT_SIZE,
	AH_CMD_MT_PLUS_SHOW,
	/* end mem-trace enhancement */

	/*data collection*/
	AH_CMD_DCM_ENABLE,
	AH_CMD_DCM_SHOW,
	AH_CMD_DCM_REPORT_TIMER,
	AH_CMD_DCM_COLLECT_TIMER,
	AH_CMD_DCM_SNAP,
	AH_CMD_DCM_EXEC,
	AH_CMD_DCM_TEST,
	AH_CMD_DCM_SHOW_CLNT,
	AH_CMD_DCM_CLEAR_FILE,
	/*end data collection*/

	/* client-trace */
	AH_CMD_CT_SHOW,
	AH_CMD_CT_ADD,
	AH_CMD_CT_TEST,
	/* end client-trace */


	AH_CMD_CLI_TEST1,
	AH_CMD_CLI_TEST2,
	AH_CMD_CLI_TEST3,
	AH_CMD_CLI_TEST4,
	AH_CMD_CLI_TEST5,
	AH_CMD_CLI_TEST6,
	AH_CMD_SCD_DEBUG_MONITOR,

	AH_CMD_DCD_SHOW_REBOOT_INFO,
	AH_CMD_LED_SET_DEF_ROUTE,

	AH_CMD_DCD_SHOW_KSTACK_USAGES,
	AH_CMD_DCD_SHOW_VLAN_DEV,

	//rx attenuator
	AH_CMD_DCD_RX_ATTENUATOR_MODE_SHOW,
	AH_CMD_DCD_RX_ATTENUATOR_MODE_CFG,

	AH_CMD_DCD_STA_SHOW,
	AH_CMD_DCD_STA_CNT_SHOW,
	AH_CMD_DCD_STA_IPV6_SHOW,
	AH_CMD_DCD_STA_MUMIMO_SHOW,
	AH_CMD_DCD_MUMIMO_COUNTERS_SHOW,
	AH_CMD_DCD_MUMIMO_COUNTERS_CLEAR,
	AH_CMD_DCD_MUMIMO_CANDIDATES_SHOW,
#ifdef CONFIG_AP1130
	AH_CMD_DCD_NEIGHBOR_RSSI_THRESHOLD,
#endif
	AH_CMD_DCD_ANT_ALIGN,
	AH_CMD_DCD_SET_CHECK_ETH_RX_HANG,

	AH_CMD_BRD_ROUTING_ENABLE,
	AH_CMD_BRD_ROUTING_PROTOCOL_TYPE,
	AH_CMD_BRD_ROUTING_RIP_ADVERTISE,
	AH_CMD_BRD_ROUTING_RIP_AUTH_MODE,
	AH_CMD_BRD_ROUTING_OSPF_ADVERTISE,
	AH_CMD_BRD_ROUTING_OSPF_AREA,
	AH_CMD_BRD_ROUTING_OSPF_ROUTER_ID,
	AH_CMD_BRD_ROUTING_OSPF_AUTH_MODE,
	AH_CMD_BRD_ROUTING_BGP_SYSTEM_NUM,
	AH_CMD_BRD_ROUTING_BGP_NEIGHBOR,
	AH_CMD_BRD_ROUTING_BGP_KEEP_ALIVE,
	AH_CMD_BRD_ROUTING_BGP_ROUTER_ID,
	AH_CMD_BRD_ROUTING_BGP_AUTH_MODE,
	AH_CMD_BRD_SHOW_ROUTING_ROUTES,
	AH_CMD_BRD_SHOW_OSPF,
	AH_CMD_BRD_SHOW_RIP,

	/* cmd for route update */
	AH_CMD_BRD_ROUTE_UPDATE_ENABLE,
	AH_CMD_BRD_ROUTE_UPDATE_INTERVAL,
	AH_CMD_BRD_ROUTE_UPDATE_SHOW,
	AH_CMD_BRD_INTERNAL_SUBNET,
	AH_CMD_BRD_INTERNAL_SUBNET_DEBUG,
	AH_CMD_BRD_INTERNAL_SUBNET_DEBUG_SUBNETS,
	AH_CMD_BRD_INTERNAL_SUBNET_SHOW,

	/* layer-3 firewall cli */
	AH_CMD_IPFW_ENABLE,
	AH_CMD_IPFW_ADD_RULE_VPN_TO_VPN,
	AH_CMD_IPFW_ADD_RULE_VPN_TO_NETWORK,
	AH_CMD_IPFW_ADD_RULE_VPN_TO_RANGE,
	AH_CMD_IPFW_ADD_RULE_VPN_TO_HOST,
	AH_CMD_IPFW_ADD_RULE_VPN_TO_WILDCARD,
	AH_CMD_IPFW_ADD_RULE_NETWORK_TO_VPN,
	AH_CMD_IPFW_ADD_RULE_NETWORK_TO_NETWORK,
	AH_CMD_IPFW_ADD_RULE_NETWORK_TO_RANGE,
	AH_CMD_IPFW_ADD_RULE_NETWORK_TO_HOST,
	AH_CMD_IPFW_ADD_RULE_NETWORK_TO_WILDCARD,
	AH_CMD_IPFW_ADD_RULE_RANGE_TO_VPN,
	AH_CMD_IPFW_ADD_RULE_RANGE_TO_NETWORK,
	AH_CMD_IPFW_ADD_RULE_RANGE_TO_RANGE,
	AH_CMD_IPFW_ADD_RULE_RANGE_TO_HOST,
	AH_CMD_IPFW_ADD_RULE_RANGE_TO_WILDCARD,
	AH_CMD_IPFW_ADD_RULE_UP_TO_VPN,
	AH_CMD_IPFW_ADD_RULE_UP_TO_NETWORK,
	AH_CMD_IPFW_ADD_RULE_UP_TO_RANGE,
	AH_CMD_IPFW_ADD_RULE_UP_TO_HOST,
	AH_CMD_IPFW_ADD_RULE_UP_TO_WILDCARD,
	AH_CMD_IPFW_ADD_RULE_WILDCARD_TO_VPN,
	AH_CMD_IPFW_ADD_RULE_WILDCARD_TO_NETWORK,
	AH_CMD_IPFW_ADD_RULE_WILDCARD_TO_RANGE,
	AH_CMD_IPFW_ADD_RULE_WILDCARD_TO_HOST,
	AH_CMD_IPFW_ADD_RULE_WILDCARD_TO_WILDCARD,
	AH_CMD_IPFW_SHOW_RULE,
	AH_CMD_IPFW_NO_RULE,
	AH_CMD_IPFW_CLEAR_SESSION,
	AH_CMD_IPFW_BYPASS_HARDENING,

	AH_CMD_BRD_CLOUD_PROXY_HTTP_HOST,
	AH_CMD_BRD_CLOUD_PROXY_HTTPS_HOST,
	AH_CMD_BRD_CLOUD_PROXY_HTTP_PORT,
	AH_CMD_BRD_CLOUD_PROXY_HTTPS_PORT,
	AH_CMD_BRD_CLOUD_PROXY_ACCT_ID,
	AH_CMD_BRD_CLOUD_PROXY_ACT_UNREACH,
	AH_CMD_BRD_CLOUD_PROXY_ENABLE,
	AH_CMD_BRD_CLOUD_PROXY_BIND_SUBNET,
	AH_CMD_BRD_CLOUD_PROXY_SUBNET_NO,
	AH_CMD_BRD_CLOUD_PROXY_SHOW_CFG,
	AH_CMD_BRD_CLOUD_PROXY_DFT_USERNAME,
	AH_CMD_BRD_CLOUD_PROXY_DFT_DOMAIN,
	AH_CMD_BRD_CLOUD_PROXY_WEBSENSE_ACCT_KEY,
	AH_CMD_BRD_CLOUD_PROXY_WHITELIST,
#ifdef AH_SUPPORT_OPENDNS
	AH_CMD_BRD_CLOUD_PROXY_OPENDNS_SERVER_IP,
	AH_CMD_BRD_CLOUD_PROXY_OPENDNS_SECURE_ID,
	AH_CMD_BRD_CLOUD_PROXY_OPENDNS_LOG_ENABLE,
#endif
	AH_CMD_BRD_TINYPROXY_DBG,

	/*for 3G_USB_MODEM*/
	AH_CMD_BRD_3G_USB_MODEM_POWER_ENABLE,
	AH_CMD_BRD_3G_USB_MODEM_POWER_CYCLE,
	AH_CMD_BRD_3G_USB_MODEM_ENABLE,
	AH_CMD_BRD_3G_USB_MODEM_DIALUP_APN,
	AH_CMD_BRD_3G_USB_MODEM_DIALUP_NUMBER,
	AH_CMD_BRD_3G_USB_MODEM_DIALUP_USERNAME,
	AH_CMD_BRD_3G_USB_MODEM_DIALUP_PASSWORD,
	AH_CMD_BRD_3G_USB_MODEM_MODE,
	AH_CMD_BRD_3G_USB_MODEM_NETWORK_MODE,
	AH_CMD_BRD_3G_USB_MODEM_RESET_DEVICE,
	AH_CMD_BRD_3G_USB_MODEM_ENABLE_TEST_MODE,
	AH_CMD_BRD_3G_USB_MODEM_CONFIG_TEST_MODE,
	AH_CMD_BRD_3G_USB_MODEM_RSSI_THRESHOLD,
	AH_CMD_BRD_3G_USB_MODEM_RUN_AT_CMD,
	AH_CMD_BRD_3G_USB_MODEM_SHOW,
	AH_CMD_BRD_3G_USB_MODEM_SHOW_STATUS,
	AH_CMD_BRD_3G_USB_MODEM_SHOW_RSSI,
	AH_CMD_BRD_3G_USB_MODEM_SHOW_INFO,
	AH_CMD_BRD_3G_USB_MODEM_SHOW_NETWORK_MODE,
	AH_CMD_BRD_3G_USB_MODEM_SHOW_SIM_INFO,
	AH_CMD_BRD_3G_USB_MODEM_SHOW_NETWORK_SERVICE,
	AH_CMD_BRD_3G_USB_MODEM_SHOW_TEST_MODE,

	/* for usbmodem open support */
	AH_CMD_BRD_USB_MODEM_MODESWITCH,
	AH_CMD_BRD_USB_MODEM_MODEM_ID,
	AH_CMD_BRD_USB_MODEM_MODEM_VID_PID,
	AH_CMD_BRD_USB_MODEM_CONNECT_TYPE,
	AH_CMD_BRD_USB_MODEM_CONNECT_CMD,
	AH_CMD_BRD_USB_MODEM_DISCONNECT_CMD,
	AH_CMD_BRD_USB_MODEM_CONNECT_STATUS_CMD,
	AH_CMD_BRD_USB_MODEM_NETWORK_DRIVER_CMD,
	AH_CMD_BRD_USB_MODEM_USBSERIAL_DRIVER_CMD,
	AH_CMD_BRD_USB_MODEM_AT_CMD_SET,
	AH_CMD_BRD_USB_MODEM_AT_CMD_GET,
	AH_CMD_BRD_USB_MODEM_RUN_PPP_CMD,
	AH_CMD_BRD_USB_MODEM_DHCP_CLIENT_ENABLE,
	AH_CMD_BRD_USB_MODEM_SHOW_MODESWITCH,
	AH_CMD_BRD_USB_MODEM_SHOW_DESCRIPTOR,

	/* for vpn report */
	AH_CMD_BRD_VPN_REPORT_ENABLE,


#ifdef AH_SUPPORT_VOIP_QOS
	AH_CMD_BRD_VOIP_QOS_ENABLE,
	AH_CMD_BRD_VOIP_QOS_UPLOAD_BW,
	AH_CMD_BRD_VOIP_QOS_DOWNLOAD_BW,
	AH_CMD_BRD_VOIP_QOS_TIMEOUT,
	AH_CMD_BRD_VOIP_QOS_SHOW,
	AH_CMD_BRD_VOIP_QOS_SHOW_INTERFACE,
	AH_CMD_BRD_VOIP_QOS_SHOW_STATS,
	AH_CMD_BRD_VOIP_QOS_SHOW_STATS_INTERFACE,
#endif

	/*NAAS CLI*/
	AH_CMD_SCD_NAAS_ENABLE,
	AH_CMD_SCD_NAAS_TIMER,
	AH_CMD_SCD_NAAS_UPDATE,
	AH_CMD_SCD_NAAS_SHOW,

#ifdef AH_SUPPORT_CPM
	AH_CMD_DCD_CPM_SET_STA,
	AH_CMD_DCD_CPM_SHOW_STATE,
	AH_CMD_DCD_CPM_SET_INTERVAL,
	AH_CMD_DCD_CPM_SET_THRESHOLD,
#endif

	/*WDIP AP-Classify CLI*/
	AH_CMD_DCD_IDP_AP_CLASSIFY,
	AH_CMD_DCD_IDP_AP_CLASSIFY_SHOW,
	AH_CMD_DCD_IDP_WAIT_INTERVAL,
	AH_CMD_DCD_IDP_QUERY_INTERVAL,

	AH_CMD_DCD_RADIO_PRESENCE_ENABLE,
	AH_CMD_DCD_RADIO_PRESENCE_TRAP_INTERVAL,
	AH_CMD_DCD_RADIO_PRESENCE_AGING_TIME,
	AH_CMD_DCD_RADIO_PRESENCE_DWELL_TIME,
	AH_CMD_DCD_RADIO_PRESENCE_CHANNEL_LIST,
	AH_CMD_DCD_SHOW_PRESENCE_TABLE,
	AH_CMD_DCD_RADIO_PRESENCE_AGGR_INTERVAL,

	/* for PBR */
	AH_CMD_BRD_PBR_POLICY,
	AH_CMD_BRD_PBR_POLICY_FROM,
	AH_CMD_BRD_PBR_POLICY_PRIMARY_WAN,
	AH_CMD_BRD_PBR_POLICY_PRIMARY_L3_TUNNEL_ACTION,
	AH_CMD_BRD_PBR_POLICY_SECONDARY_WAN,
	AH_CMD_BRD_PBR_POLICY_SECONDARY_L3_TUNNEL_ACTION,
	AH_CMD_BRD_PBR_POLICY_SHOW,
	AH_CMD_BRD_PBR_POLICY_SHOW_ONE,
	AH_CMD_BRD_PBR_POLICY_SHOW_ROUTE,
	AH_CMD_BRD_PBR_MMAP_FROM_ANY2OPT,
	AH_CMD_BRD_PBR_MMAP_FROM_ANY2NET,
	AH_CMD_BRD_PBR_MMAP_FROM_ANY2HOST,
	AH_CMD_BRD_PBR_MMAP_FROM_ANY2IPRANGE,
	AH_CMD_BRD_PBR_MMAP_FROM_NET2OPT,
	AH_CMD_BRD_PBR_MMAP_FROM_NET2NET,
	AH_CMD_BRD_PBR_MMAP_FROM_NET2HOST,
	AH_CMD_BRD_PBR_MMAP_FROM_NET2IPRANGE,
	AH_CMD_BRD_PBR_MMAP_FROM_IPRANGE2OPT,
	AH_CMD_BRD_PBR_MMAP_FROM_IPRANGE2NET,
	AH_CMD_BRD_PBR_MMAP_FROM_IPRANGE2HOST,
	AH_CMD_BRD_PBR_MMAP_FROM_IPRANGE2IPRANGE,
	AH_CMD_BRD_PBR_MMAP_USERPF2OPT,
	AH_CMD_BRD_PBR_MMAP_USERPF2NET,
	AH_CMD_BRD_PBR_MMAP_USERPF2HOST,
	AH_CMD_BRD_PBR_MMAP_USERPF2IPRANGE,
	AH_CMD_BRD_PBR_MMAP_IIF2OPT,
	AH_CMD_BRD_PBR_MMAP_IIF2NET,
	AH_CMD_BRD_PBR_MMAP_IIF2HOST,
	AH_CMD_BRD_PBR_MMAP_IIF2IPRANGE,
	AH_CMD_BRD_PBR_RMAP_OIF,
	AH_CMD_BRD_PBR_RMAP_OIF_OPT,
	AH_CMD_BRD_PBR_RMAP_DEL,
	AH_CMD_BRD_PBR_POLICY_CREATE,
	AH_CMD_BRD_PBR_POLICY_ID_CHANGE,
	AH_CMD_BRD_PBR_SHOW_SPECIFY_MAP,

#ifdef AH_SUPPORT_MULTIWAN
	/* for Track IP for WAN*/
	AH_CMD_BRD_TRACK_WAN_GROUP_NAME,
	AH_CMD_BRD_TRACK_WAN_GROUP_IP,
	AH_CMD_BRD_TRACK_WAN_GROUP_DEFAULT_GW,
	AH_CMD_BRD_TRACK_WAN_GROUP_MULTI_LOGIC,
	AH_CMD_BRD_TRACK_WAN_GROUP_ENABLE,
	AH_CMD_BRD_TRACK_WAN_GROUP_INTERVAL,
	AH_CMD_BRD_TRACK_WAN_GROUP_TIMEOUT,
	AH_CMD_BRD_TRACK_WAN_GROUP_RETRY,
	AH_CMD_BRD_TRACK_WAN_GROUP_IF,
	AH_CMD_BRD_SHOW_TRACK_WAN,
	AH_CMD_BRD_SHOW_WAN_INTERFACE,
	AH_CMD_BRD_SHOW_WAN_INTERFACE_IFNAME,
	AH_CMD_BRD_SHOW_WAN_FAILOVER,
	AH_CMD_BRD_SHOW_WAN_DB,

	AH_CMD_BRD_IP_NAT_POLICY_SHOW,
	AH_CMD_BRD_IP_NAT_POLICY_SHOW_ONE,
	AH_CMD_BRD_IP_NAT_POLICY_SHOW_SERVICE_PORT,
	AH_CMD_BRD_IP_SESSION_SHOW,
	AH_CMD_BRD_IP_SESSION_NAT_POLICY_SHOW,
	AH_CMD_BRD_IP_SESSION_NAT_POLICY_SHOW_ONE,
#endif
#ifdef AH_SUPPORT_HIVEUI_WAN_CMD
	AH_CMD_BRD_CLI_HIVEUI_WANCFG_ENABLE,
	AH_CMD_BRD_CLI_SHOW_HIVEUI_WANCFG,
	AH_CMD_BRD_CLI_CLEAR_HIVEUI_WANCFG,
	AH_CMD_BRD_CLI_HIVEUI_WANCFG_LINK_ENABLE,
#endif
	AH_CMD_BRD_CLI_DDNS_ENABLE,
	AH_CMD_BRD_CLI_DDNS_HOSTNAME,
	AH_CMD_BRD_CLI_DDNS_SERVER_ACCOUNT,
	AH_CMD_BRD_CLI_SHOW_DDNS,

#ifdef AH_SUPPORT_WIPS
	AH_CMD_DCD_IDP_WIPS_POLICY,
	AH_CMD_DCD_IDP_WIPS_POLICY_BIND,
	AH_CMD_DCD_IDP_WIPS_POLICY_SHOW,
#endif

#ifdef AH_SUPPORT_WPA_SUPP
	AH_CMD_DCD_CLIENT_ESTABLISH_CONNECTION,
	AH_CMD_DCD_CLIENT_DEBUG,
	AH_CMD_DCD_IF_WAN_WLAN_PRIORITY,
	AH_CMD_DCD_IF_WAN_WLAN_NAT,
	AH_CMD_DCD_CLIENT_DISPLAY_SSID,
	AH_CMD_DCD_CLIENT_CONNECT_SSID,
	AH_CMD_DCD_CLIENT_PRIORITY,
	AH_CMD_DCD_CLIENT_BAND_MODE,
	AH_CMD_DCD_CLIENT_CLEAR,
	AH_CMD_DCD_IF_MODE_FORCE,
#endif



	AH_CMD_DCD_SSID_RRM_ENABLE,
	AH_CMD_DCD_SSID_RRM_QUIET_ENABLE,
	AH_CMD_DCD_SSID_RRM_QUIET,
	AH_CMD_DCD_SSID_WNM_ENABLE,
	AH_CMD_DCD_SSID_WNM_STA,
	AH_CMD_DCD_SSID_ADMCTL_AC_ENABLE,
	AH_CMD_DCD_SSID_ADMCTL_BW,
	AH_CMD_DCD_SSID_ADMCTL_DELTS_STA,
	AH_CMD_DCD_SSID_ADMCTL_SHOW_TSINFO_STA,
	AH_CMD_DCD_SSID_RRM_BCNREQ,
	AH_CMD_DCD_SSID_RRM_TSMREQ,
	AH_CMD_DCD_SSID_RRM_BCNREQ_CHANREP,
	AH_CMD_DCD_SSID_RRM_SHOW_CHANREP,
	AH_CMD_DCD_SSID_RRM_SHOW,

	AH_CMD_L7D_CONTROL,
	AH_CMD_L7D_PERIOD,
	AH_CMD_L7D_SHOW_CFG,
	AH_CMD_L7D_APPID,
	AH_CMD_L7D_APPID_HIDDEN,
	AH_CMD_L7D_WATCHLIST,
	AH_CMD_L7D_WATCHLIST_HIDDEN,
	AH_CMD_L7D_ORG_RPT_DUMP,
	AH_CMD_L7D_IF_ENABLE,
	AH_CMD_L7D_CLEAR_STATS,
	AH_CMD_L7D_SHOW_STATS,
	AH_CMD_L7D_PCAP,
	AH_CMD_L7D_SHOW_APPS,
	AH_CMD_L7D_SHOW_DPI_STATS,
	AH_CMD_L7D_CLEAR_DPI_STATS,
	AH_CMD_L7D_SHOW_DPI_DIAG,
	AH_CMD_L7D_SET_DPI_PARAMS,
	AH_CMD_L7D_DISABLE_PLUGIN,
	AH_CMD_L7D_SHOW_DPI_DIAG_DE,
	AH_CMD_L7D_INTERFACE_REPORT,
	AH_CMD_L7D_SHUTDOWN,
	AH_CMD_L7D_UPDATE_PLUGINS,
	AH_CMD_L7D_DEBUG_LEVEL,
	AH_CMD_L7D_DEBUG_LEVEL_REPORT,
	AH_CMD_L7D_CDP_ADD_PROTO,
	AH_CMD_L7D_CDP_ADD_RULE,
	AH_CMD_L7D_SHOW_APP_STATS,
	AH_CMD_L7D_CLEAR_APP_STATS,
	AH_CMD_L7D_TOHM,
	AH_CMD_L7D_UPDATE_PLUGINS_STATUS,
	AH_CMD_L7D_SET_DISCOVERY,
	AH_CMD_L7D_SHOW_DISCOVERY,
	AH_CMD_L7D_SET_SPACE,
	AH_CMD_L7D_SHOW_SPACE,
	AH_CMD_L7D_SHOW_MALLOC_STATS,
	AH_CMD_L7D_CDP_SHOW,
	AH_CMD_L7D_MEMORY_PURGE,
	AH_CMD_L7D_MEMORY_PURGE_ALL,
	AH_CMD_L7D_CASB_CONTROL,

	AH_CMD_SFLOW_SHUTDOWN,
	AH_CMD_SFLOW_INSTANCE,
	AH_CMD_SFLOW_SHOW_INSTANCE,
	AH_CMD_SFLOW_SHOW,
	AH_CMD_SFLOW_SET_PARAM,

	AH_CMD_CAPWAP_BONJOUR_CONTROL,

	AH_CMD_SCD_EXEC_HTTPC_TEST,
	AH_CMD_DCD_SEND_MLME,
#ifdef AH_SUPPORT_MDM
	AH_CMD_DCDAUTH_SUITEMETHOD_MDM_ARHV_APIKEY,  /* aerohive mdm */
	AH_CMD_DCDAUTH_SUITEMETHOD_MDM_ARHV_ACCESS_SSID,
	AH_CMD_MDM_ARHV_DEVICE_GROUP,
#endif
	AH_CMD_CAPWAP_DISCOVERY_METHOD,
	AH_CMD_CAPWAP_ACTIVE_ALARMS_RESEND,
	AH_CMD_CAPWAP_SHOW_ALARMS_BUFFER,
	AH_CMD_DCD_SMU_SEND_PACKET_TO_NMS,  /*simulate sending packet to NMS*/
	AH_CMD_SCD_WEB_SERVER_SIG_ARG,

	AH_CMD_TEST_UPP,
	AH_CMD_DCD_CLOUD_CWP_ENABLE,
	AH_CMD_DCD_SET_CLOUD_CWP_URL,
	AH_CMD_DCD_SET_CLOUD_CWP_SERVICE_ID,
	AH_CMD_DCD_SET_CLOUD_CWP_CUSTOMER_ID,
	AH_CMD_DCD_SET_CLOUD_CWP_APIKEY,

#ifdef AH_CVG_AS_AP
	AH_CMD_DCD_IF_SIMX_Y_IP,
#endif

	AH_CMD_DCD_HW_ACCESS,
	AH_CMD_DCD_HW_BREAKPOINT,
	AH_CMD_KDUMP_REPORT_HM,
	AH_CMD_BBOX_LIST,
	AH_CMD_BBOX_CLEAR_ALL_DUMP,
	AH_CMD_BBOX_CLEAR_DUMP,
	AH_CMD_BBOX_STATUS,
	AH_CMD_SCD_CORRECT_MAC_ADDR,    /* correct board base MAC address if it is illegel. */
#ifdef AH_SUPPORT_11AC
	AH_CMD_DCD_RADIO_VHT_SPEED,
#endif

	AH_CMD_DCD_SET_SYSTEM_BUZZER_SHUTDOWN,
	AH_CMD_DCD_SET_SYSTEM_BUZZER_BEEP,
	AH_CMD_DCD_SET_SYSTEM_BUZZER_BEEP_IN_ISLAND_MODE,
	AH_CMD_DCD_SET_SYSTEM_BUZZER_SIGNAL,
	AH_CMD_DCDAUTH_RADIUS_ACCT_SRVIP_IDM_SO,
	AH_CMD_DCDAUTH_RADIUS_IDM_SO,
	AH_CMD_DCDAUTH_RADIUS_IDM_ACCT_SO,
	AH_CMD_DCDAUTH_RADIUS_IDM_SO_NO,
	AH_CMD_BGD_VLAN_DISPLAY,

#ifdef AH_SUPPORT_IBEACON
	AH_CMD_IBEACON_SHOW_INTERFACE,
	AH_CMD_DCD_IBEACON_ENABLE,
	AH_CMD_DCD_IBEACON_CFG,
	AH_CMD_DCD_NO_IBEACON_CFG,
	AH_CMD_DCD_IBEACON_MONITOR_ENABLE,
	AH_CMD_IBEACON_SHOW_MONITOR_LIST,
#endif

#ifdef AH_SUPPORT_EXT_USB_POWER_SETTING
	/* there's another CLI:
	 * AH_CMD_BRD_USB_EXT_PORT_POWER_ENABLE
	 * is for debugging only, hidden CLI
	 * (on BR200 only)
	 *
	 * AH_CMD_DCD_USB_EXT_PORT_POWER_CFG
	 * is common persistent config CLI
	 */
	AH_CMD_DCD_USB_EXT_PORT_POWER_CFG,
#endif

	/* client monitor cmd */
	AH_CMD_DCD_CM_POLICY,
	AH_CMD_DCD_SSID_CM_POLICY,
	AH_CMD_DCD_ETH_CM_POLICY,
	AH_CMD_DCD_SHOW_CM_POLICY,
	AH_CMD_DCD_CM_POLICY_NO,
	AH_CMD_CT2_SHOW,

	AH_CMD_DCD_SET_SYSTEM_POWER_MODE_8023AT,
	AH_CMD_DCD_SET_SYSTEM_POWER_MODE,
	AH_CMD_DCD_NO_SYSTEM_POWER_MODE,
	AH_CMD_DCD_SHOW_SYSTEM_POWER_MODE,
	AH_CMD_DCD_SET_SYSTEM_PERF_MODE,
	AH_CMD_DCD_SHOW_SYSTEM_PERF_MODE,
	AH_CMD_DCD_SHOW_IF_TARGET,
	AH_CMD_DCD_DBG_WIFI_READ_REG,
	AH_CMD_DCD_DBG_WIFI_WRITE_REG,
	AH_CMD_DCD_DBG_WIFI_TARGET_CPU,
	AH_CMD_DCD_IF_RC_NUM_RETRIES,
	AH_CMD_DCD_IF_CWP_SSL_KEY,
#ifdef AH_SUPPORT_ANTENNA_TYPE
	AH_CMD_DCD_IF_ANTENNA_TYPE,
#endif
	AH_CMD_DCD_CM_ENABLE,
	AH_CMD_AUTH_CONNECTION_TRAP_DELAY,
	AH_CMD_AUTH_SHOW_CONNECTION_TRAP_DELAY,
	AH_CMD_SCD_LOG_TRAP_WHITE_LIST_LEVEL,
	AH_CMD_SCD_LOG_TRAP_WHITE_LIST_CATEGORY,
	AH_CMD_SCD_REBOOT_SCHEDULE_WEEKLY,
	AH_CMD_SCD_REBOOT_SCHEDULE_DAILY,
	AH_CMD_SCD_REBOOT_SCHEDULE_SHOW,
	AH_CMD_DCD_MANAGEMENT_TELNET_PORT,
	AH_CMD_AUTH_TEST_VLAN_POOL,

#ifdef AH_SUPPORT_WPA_SUPP_WIRED
	AH_CMD_DCD_SUPP_OBJ,
	AH_CMD_DCD_SUPP_OBJ_CREDENTIAL,
	AH_CMD_DCD_SUPP_OBJ_PASSWD,
	AH_CMD_DCD_SUPP_OBJ_EAP_TYPE,
	AH_CMD_DCD_ETH_BIND_SUPP_OBJ,
	AH_CMD_DCD_SUPP_CA,
	AH_CMD_DCD_SUPP_CERT,
	AH_CMD_DCD_SUPP_SHOW,
	AH_CMD_DCD_SUPP_CLR_CERT,
	AH_CMD_DCD_SUPP_SHOW_CERT,
#endif
	AH_CMD_AUTH_SHOW_AAA2,
#ifdef AH_VRRP_SUPPORT
	AH_CMD_VRRPD_VID,
	AH_CMD_VRRPD_IP,
	AH_CMD_VRRPD_PRIORITY,
	AH_CMD_VRRPD_ADV_TIMER,
	AH_CMD_VRRPD_PREEMPT,
	AH_CMD_VRRPD_SHOW,
	AH_CMD_VRRPD_TRACK_WAN,
#endif
	AH_CMD_AUTH_ROAMING_BRIDGED_NEIGHBOR,


#if defined(AH_SUPPORT_IPV6) && defined(AH_IPV6_IP_SESSION)
	AH_CMD_SHOW_IPV6_SESS_PARAMS,
	AH_CMD_CLEAR_IPV6_SESS_PARAMS,
#endif

#if defined(AH_SUPPORT_IPV6) && defined(AH_IPV6_CWP)
	AH_CMD_DCD_WIFIXY_IPV6ADDR,
	AH_CMD_DCD_ETH_IPV6ADDR,
#endif


#if defined(AH_SUPPORT_IPV6) && defined(AH_IPV6_ND_CACHE)
	AH_CMD_FE_PROXY_ND_STATUS,
	AH_CMD_SHOW_NDC,
	AH_CMD_CLEAR_NDC,
#endif

	/*MACSec cmd*/
//#ifdef AH_SUPPORT_MACSEC
	AH_CMD_DCD_MACSEC_CA,
	AH_CMD_DCD_MACSEC_CA_SECURITY_MODE,
	AH_CMD_DCD_MACSEC_CA_SC_SCI_SA,
	AH_CMD_DCD_MACSEC_CA_CAK_KEY,
	AH_CMD_DCD_MACSEC_CA_CAK_KEY_SERVER_PRIORITY,
	AH_CMD_DCD_MACSEC_CA_CAK_REFRESH_INTERVAL,
	AH_CMD_DCD_MACSEC_CA_ENCRYPTION_OFFSET,
	AH_CMD_DCD_MACSEC_CA_ENCRYPTION_NO_OFFSET,
	AH_CMD_DCD_MACSEC_CA_REPLAY_PROTECT_WINDOW_SIZE,
	AH_CMD_DCD_MACSEC_CA_REPLAY_PROTECT_NO_WINDOW_SIZE,
	AH_CMD_DCD_MACSEC_CA_EXCLUDED_PROTOCOL,
	AH_CMD_DCD_MACSEC_CA_BIND,
	AH_CMD_DCD_MACSEC_CA_SHOW,
	AH_CMD_DCD_INTERFACE_MACSEC_SHOW_MIB,
	AH_CMD_DCD_INTERFACE_MACSEC_CLEAR_MIB,
	AH_CMD_DCD_MACSEC_CA_NEXT_PN,
//#endif
#ifdef AH_SUPPORT_SAS
	AH_CMD_DCD_SET_SYSTEM_SAS_DEBUG_PARAM_CMDS,
#endif

	AH_CMD_NORMAL_END /*don't add CLI cmdid behind of this CLI ID*/
};

enum ah_cli_cmd_id_rely {
	/*
	 * NOTE: the cmds below AH_CMD_RELY_START will appear in "show running" in the exactly same order
	 * as you define the cmd macros. Any cmds without such order requirement should be placed above
	 * AH_CMD_RELY_START.
	 */
	AH_CMD_RELY_START = AH_CMD_NORMAL_END,

	AH_CMD_DCD_SSID_BIND_USER_PROFILE,
	AH_CMD_DCD_SO_BIND_USER_PROFILE, /* depend on user-profile cmd */
	AH_CMD_DCD_USER_BIND_SCHE,
	AH_CMD_DCD_USER_SCHE_DENY_ACT,
	AH_CMD_SWD_SET_UP_DEFAULT_ACTION, /* depend on user-profile cmd */
	AH_CMD_SWD_SET_IP_ACL_TO_UP, /* depend on user-profile cmd */
	AH_CMD_BGD_FILTER,
	AH_CMD_DCD_SHOW_VIDEO,
	AH_CMD_DCD_SHOW_VIDEO_RANGE,
	AH_CMD_DCD_STA_MC_SHOW,

#ifdef AH_SUPPORT_MULTIWAN
	/* BRD NAT */
	AH_CMD_BRD_IP_NAT_POLICY,
	AH_CMD_BRD_IP_NAT_POLICY_IPMAP,
	AH_CMD_BRD_IP_NAT_POLICY_NETMAP,
	AH_CMD_BRD_IP_NAT_POLICY_PORTFWD,
	AH_CMD_DCD_IF_WAN_NAT_POLICY_ENABLE,
	AH_CMD_DCD_IF_WAN_WLAN_NAT_POLICY_ENABLE,
	AH_CMD_VPN_NAT_POLICY_ENABLE,
#endif

	AH_CMD_BRD_USB_EXT_PORT_POWER_ENABLE,
	AH_CMD_DCDAUTH_SO_BIND_UP_POLICY,
	AH_CMD_DHCLIENT_DEBUG,
	AH_CMD_QOS_SET_USERPROFILE_VLANGROUP, /* depend on user-profile cmd and vlan-group cmd */
	AH_CMD_AUTH_USER_GROUP_ALGORITHM_VER,

	AH_CMD_FE_DHCP_SPOOF_SHIELD,
	AH_CMD_FE_ARP_SPOOF_SHIELD,

	AH_CMD_RXSENSE_CLEAR,
	AH_CMD_RXSENSE_CLEAR_CHANNEL,
	AH_CMD_RXSENSE_SET,
	AH_CMD_RXSENSE_SET_CHANNEL,
	AH_CMD_TXPOWER_CLEAR,
	AH_CMD_TXPOWER_CLEAR_CHANNEL,
	AH_CMD_TXPOWER_SET,
	AH_CMD_TXPOWER_SET_CHANNEL,

#if AH_SUPPORT_IPV6
	AH_CMD_BGD_NEIGHBOR6,
	AH_CMD_BGD_NEIGHBOR_DOMAIN,
#endif
	AH_CMD_DCD_WL_CMDS,
#ifdef AH_SUPPORT_SAS
	AH_CMD_DCD_SAS_AI_CMDS,
	AH_CMD_DCD_SHOW_SAS_CMDS,
#endif

	AH_CMD_LAST_ONE, /*don't add CLI cmdid behind of this CLI ID*/

	/*
	 * !!! don't add CLI cmdid behind of AH_CMD_RELY_START !!!
	 * there is special usage to add cmdid behind of AH_CMD_RELY_START
	 */

	AH_CMD_ANY = 0xffff
};

/* CLI cmd parameter internal type ID */
#define KEYWORD       0
#define BOOLEAN       1
#define INTEGER       2
#define INTERVAL      3
#define STRING        4
#define OPTIONS       5
#define IP_ADDR       6
#define IP_RANGE      7
#define IP_MASK       8
#define OCTET_STR_256 9
#define MAC_ADDR      10
#define HEXUL         11
#define WIFI          12
#define VIRTUALWIFI   13
#define UINTEGER      14
#define LONGSTRING    15
#define LOCATION      16
#define ETHX          17
#define MGTX          18
#define DATE          19
#define TIME          20
#define OUI           21
#define SECRETSTR     22
#define IP_AND_MASK   23
#define STRING_64     24
#define STRING_256    25
#define TIME_HM       26
#define DATE_MD       27
#define COMPOUND      28 /* typed or'd together */
#define AGGX          29
#define REDX          30
#define KEYALL        31
#define CHANNEL_G3    32
#define CHANNEL_G4    33
#define UINTERVAL     34
#define VIRTUALMGT    35
#define DATETIME      36
#define UPTIME        37
#define SECRET_STR32  38
#define TUNNELX       39
#define PORT          40
#define IP_WILDC_MASK 41
#define SECRET_STR64  42
#define URL           43
#define VIRTUALBGD    44
#define USBNETX       45
#define VLANX         46
#define IPV6_AND_MASK 47
#define PORT_CHANNELX 49
#define ETHXY         50
#define WL            51
#define VIRTUALWL     52
#ifdef AH_SUPPORT_IBEACON
#define BLEX          53
#endif
#define IPV6_ADDR   54
#define STRING_512  55

typedef struct {
	unsigned int ip;
	unsigned int mask;
} ah_ip_mask_t;

typedef struct {
	struct in6_addr ipv6;
	unsigned int    mask;
} ah_ipv6_mask_t;

/* CLI command sync type */
enum {
	AH_SET_CMD,
	AH_GET_CMD
};

/* Type id for MPI. Temporarily put here. Should be in ah_smpi.h */
#define AH_TEST_CLI_MSG_T 123

#define ah_decode_ctx_id(id) ((id)>>16)
#define ah_decode_cmd_id(id) ((id)&0xffff)

/* Returns the max fd set for fd_set */
extern void ah_reg_cfg_generator(int (*cfg_gen)(ah_cmd_handle_t *, void *), void *data);

#define AH_CMD_REPLY 1
#define AH_CMD_NO_REPLY 0
#define AH_CMD_ERROR -1

/*extern void ah_set_cmd_reply_string(const char *reply);*/

#define AH_CLI_PAGE_LEN ( AH_MAX_TLV_BUF_SIZE - sizeof(ah_tlv_t) )
#define AH_CLI_MAX_RECV_LEN (AH_CLI_PAGE_LEN+sizeof(ah_tlv_hdr_t)+sizeof(ah_tlv_t))
#define AH_MAX_STR_PARM_LEN 32 /* STRING_32*/
#define AH_MAX_STR_64_LEN 64
#define AH_MAX_LONG_STR_LEN (128) /*add for password*//* STRING_128*/
#define AH_MAX_STR_256_LEN   256
#define AH_MAX_SECRET_STR_LEN   (128) /*add for secret password*/
#define AH_ENCRYPT_ORG_LEN      (5) /* move from ah_cli_sec.h */
#define AH_MAX_LCT_256_LEN      (256)  /* fix bug 10552, increase location type length to 256 */
#define AH_MAX_RATE_STR_512_LEN      (512)  /* fix bug HOS-7959, increase string length to 512 */

#define MAX_NUM_TOKS 24
/* 1 for no node; 1 for future use */
#define PATH_MAX_NUM_TOKS (MAX_NUM_TOKS + 2)
typedef struct {
	char      **tokens;
	unsigned short *tokens_off;
	char      *buf;
	uint      tokens_len;
	uint      buf_len;
} ah_tokens_t;

extern void ah_cli_puts(ah_cmd_handle_t *, const char *);
extern void ah_cli_printf(ah_cmd_handle_t *, const char *format, ...);
extern void ah_cli_hexdump(ah_cmd_handle_t *h, const uchar *buf, uint size);
extern int ah_cli_flush(ah_cmd_handle_t *h, int eom);
extern int ah_cli_keepalive(ah_cmd_handle_t *h);
extern int ah_cli_refresh_winsize(ah_cmd_handle_t *h);
/* extern boolean ah_cli_token_has_space(const char* str); */
int ah_str_to_user_str(char *buf, unsigned int buf_len,
					   const char *str);
int ah_tokenize(const char *str, ah_tokens_t *token_cookie);
void ah_cli_send_instance(ah_cmd_handle_t *cmd,
						  ushort      type,
						  int      instance,
						  boolean eom);
void ah_cli_send_tlv(ah_cmd_handle_t *cmd,
					 ushort      type,
					 ushort      len,
					 void *val);


#define ah_cfg_printf ah_cli_printf

extern void ah_register_debug_flag(char *mod, char *flag, uint *var, uint val);
extern void ah_register_dbg_lib_flag(char *mod, char *flag, uint *var, uint val);
#ifdef __STLIB
extern void ah_debug_init();
#define AH_CMD_VEC_INIT()
#else
typedef void (*ah_cmd_vec_init_t)();

extern void ah_add_cli_vector_initializer(ah_cmd_vec_init_t);


#ifdef CLI_THREAD
extern void ah_debug_init();
extern void ah_reg_cfg_generators();
extern void ah_reg_cmd_vectors();
extern void ah_reg_cmd_vec_auto();
#else
extern void ah_debug_init();
extern void ah_reg_cmd_vec_auto();
#endif

#define AH_CMD_VEC_INIT()\
	ah_add_cli_vector_initializer(ah_debug_init);\
	ah_add_cli_vector_initializer(ah_reg_cfg_generators);\
	ah_add_cli_vector_initializer(ah_reg_cmd_vectors);\
	ah_add_cli_vector_initializer(ah_reg_cmd_vec_auto)

#endif

#define AH_MAX_DEBUG_FLAGS (sizeof(uint)<<3)

#define AH_DCL_DBG_VAR(mod_name) extern int ah_##mod_name##_dbg
#define AH_DBG_VAR_BIT_TEST(mod_name, val) (ah_##mod_name##_dbg & val)

#define AH_REG_COM_DBG(mod_name, mod_id, flag, val)\
	ah_register_debug_flag(#mod_name, #flag, &ah_##mod_name##_dbg, val)
#define AH_REG_LIB_DBG(mod_name, mod_id, flag, val)\
	ah_register_dbg_lib_flag(#mod_name, #flag, &ah_lib_dbg, val)


#define AH_CLI_BE_DECL_IPC_BUF(ch)\
	ch->data2climod = NULL;\

	extern ah_tlv_t *ah_cli_agent_add_tlv(ah_cmd_handle_t *ch, int cmdid, void *cmddataptr, int cmddatasize, int tlvtypeid);
	ah_tlv_t *ah_cli_agent_add_tlv_msg(ah_cmd_handle_t *h,
									   void *data,
									   int size,
									   int type);
	int ah_cli_agent_flush_tlv(ah_cmd_handle_t *h, int final);
	ah_tlv_t *ah_cli_agent_add_delay_cmd(ah_cmd_handle_t *h,
										 uint32_t delay_time,
										 const char *cmd);

#define AH_CLI_BE_ADD_CMD_DATA(ch,cmdid,cmddataptr)\
	ah_cli_agent_add_tlv(ch,\
						 cmdid, cmddataptr, sizeof(*(cmddataptr)),\
						 AH_CLI_TLV_GET_RUN_CFG_T)

	typedef struct ah_rely_type {
		int cmd_id;
		char item[0];
	} ah_rely_type_t;

#define AH_CLI_BE_ADD_RELY_CMD(ch,cmd,cmdstr)\
	do {\
		ah_rely_type_t* a = (ah_rely_type_t*)malloc(sizeof(int) + strlen(cmdstr) + 1);\
		if(NULL == a){\
			break;\
		}\
		a->cmd_id = cmd;\
		strcpy(a->item, cmdstr); \
		ah_cli_agent_add_tlv_msg(ch, \
								 a, \
								 (sizeof(int) + strlen(cmdstr)+1), \
								 AH_CLI_TLV_CFG_RELYID_T); \
		free(a);\
	}while(0)

#define AH_CLI_BE_ADD_CMD_STR(ch,cmdstr) \
	do { \
		ah_cli_agent_add_tlv_msg(ch,  \
								 cmdstr, \
								 strlen(cmdstr) + 1, \
								 AH_CLI_TLV_CFG_STR_T); \
	}while(0)

#define AH_CLI_BE_ADD_CMD_TLV(ch,type,len,val) \
	do { \
		ah_cli_agent_add_tlv_msg(ch, val, len, type); \
	}while(0)

#define AH_CLI_BE_CFG_GEN_END(ch)\
	do {\
		ah_cli_agent_add_tlv_msg(ch, NULL, 0, AH_CLI_TLV_CFG_END_T); \
	} while(0)

#define AH_CLI_RETRIEVE_DATA(tlvbuf, T, dataptr) \
	T *dataptr;\
	do {\
		ah_tlv_iterator_t it;\
		ah_tlv_t *p = ah_first_tlv (&it, tlvbuf, 1);\
		ah_assert(p->type==AH_CLI_IPC_STRUCT_T);\
		dataptr = TLV_V(p, T);\
	} while(0)


	/* Return code of CLI back-end vectors */
#define AH_CLI_ESHOW_TECH_UNKNOWN_CMD         15
#define AH_CLI_EINPUT_CHAR                    14
#define AH_CLI_EINPUT_TOO_LONG                13
#define AH_CLI_EINVALID_DELAY_CMD             12
#define AH_CLI_EDUPLICATED_DELAY_CMD          11
#define AH_CLI_EINVALID_READONLY_CMD          10
#define AH_CLI_EAMBIGUOUS_INPUT                9
#define AH_CLI_EINVALID_INTERFACE              8
#define AH_CLI_EAMBIGUOUS_COMMAND              7
#define AH_CLI_EINCOMPLETE_COMMAND             6
#define AH_CLI_EINCOMPLETE_INPUT               5
#define AH_CLI_EUNKNOWN_KEYWORD                4
#define AH_CLI_ETOO_MANY_TOKENS                3
#define AH_CLI_ECHAR_AFTER_QUOTE               2
#define AH_CLI_EUNMATCHED_QUOTE                1
//#define AH_CLI_OK 0
#define AH_CLI_EUSR -1
#define AH_CLI_ESYS -2
#define AH_CLI_EUNKNOWN -0xffff

#define __AH_CBASE(obj) ((ah_cmd_ipc_data_struct_base_t *)(obj))

#define AH_CMD_VAR_OK(obj, id)\
	(id>=0 && id<=30 && (__AH_CBASE(obj)->flag & (1<<(id))))

#define AH_CLI_BE_SET_CMD_ID(obj, i)\
	__AH_CBASE(obj)->id = (AH_CLI_CTX_ENABLE<<16)|i

#define AH_CLI_BE_CMD_FLAG_NO(obj)\
	(__AH_CBASE(obj)->flag & (1<<31))

#define AH_CLI_BE_CMD_FLAG_SET_NO(obj)\
	__AH_CBASE(obj)->flag |= (1<<31)

#define AH_CLI_BE_CMD_FLAG_UNSET_NO(obj)\
	__AH_CBASE(obj)->flag &= ~(1<<31)

#define AH_CLI_BE_SET_CMD_PARM_VALID(obj, i)\
	__AH_CBASE(obj)->flag |= (1<<i)

	typedef struct {
		union {
			uint      flag; /* flag for valid parameters */
			struct {
#if __BYTE_ORDER == __BIG_ENDIAN
				uint      __no_flag: 1;
				uint      __unused: 31;
#else
				uint      __unused: 31;
				uint      __no_flag: 1;
#endif
			} valid;
		};
		uint      id; /* (ctx<<16|cmd) */
		uint16_t    exec_flag;
		uint16_t    no_prompt; /* (generic no-prompt for NMS) */
	} ah_cmd_ipc_data_struct_base_t;

	typedef int (*ah_cli_ui_show_callback_t)(void);
	typedef struct {
		int mh; /* mpi handler */
		char *mpi_buf; /* mpi buffer */
		ah_cli_ui_show_callback_t callback; /*this is used for ui callback*/
		ah_cli_ui_show_callback_t old_callback; /*this is used for old ui callback*/
	} ah_cli_ui_state;

#define AH_DEF_HOST_NAME "admin"
#define AH_CLI_TAB_MAX   32
#define AH_CLI_PWD_PREFIX "?PASSWORD?"
#define AH_CLI_SPECIAL_HELP_HEAD "?\b"

	extern int ah_cli_data_2_cmdstr(char *cmdstr, unsigned short cmdid, char *data);

#define AH_CLI_FLAG_SHOW_TECH  0x01
#define AH_CLI_FLAG_WEBUI_EXEC 0x02
#define AH_CLI_FLAG_OBSC_PWD   0x04
#define AH_CLI_FLAG_SHOW_HIST  0x08
#define AH_CLI_FLAG_SHOW_ALL_RUNNING_CONFIG  0x10

#define AH_CLI_CMD_IS_SHOW_TECH(p) \
	(p->exec_flag & AH_CLI_FLAG_SHOW_TECH )

#define AH_CLI_SHOW_TECH_PATH  "/etc/ah_cli_show_tech.conf"
#define AH_CLI_SHOW_ALL_RUNNING_CFG_PATH  "/etc/ah_cli_show_all.conf"

	/* define string in quote value */
#define AH_STR_IN_QUOTE_FALSE   0  /* not quote or double quote */
#define AH_STR_IN_QUOTE_TRUE   -1  /* in double quote */
#define AH_STR_IN_QUOTE_TRUE2  -2  /* in double quote, the end is singel '\'*/

#define AH_MAX_INPUT_LEN 800  /* Max number of cmd input line */
#endif
