#ifndef _AH_CLI_TLV_TLV_H_S
#define _AH_CLI_TLV_TLV_H_S

#include "ah_tlv_msg.h"

#define AH_MAX_TLV_BUF_SIZE   1024
/* TLV Type ID */
enum {
	AH_CLI_TLV_CMD_TYPE_T,
	AH_CLI_TLV_INT_T,
	AH_CLI_TLV_ID_T,
	AH_CLI_TLV_IFNAME_T,
	AH_CLI_TLV_IPADDR_T,
	AH_CLI_TLV_NETMASK_T,
	AH_CLI_TLV_MAC_T,
	AH_CLI_TLV_GET_RUN_CFG_T,
	AH_CLI_TLV_STRING_T,
	AH_CLI_TLV_BYE_T,
	AH_CLI_TLV_DEBUG_FLAG_T,
	AH_CLI_TLV_DEBUG_MOD_T,
	AH_CLI_TLV_DEBUG_STOP_T,
	AH_CLI_TLV_DEBUG_INFO_T,
	AH_CLI_TLV_BITMASK_T,
	AH_CLI_TLV_MODULE_NAME_T,
	AH_CLI_TLV_VEC_ID_T,
	AH_CLI_IPC_STRUCT_T,
	AH_CLI_TLV_STR_T,
	AH_CLI_TLV_FILENAME_T,
	AH_CLI_TLV_CMD_COOKIE_T,
	AH_CLI_TLV_CFG_STR_T,
	AH_CLI_TLV_CFG_RELYID_T,
	AH_CLI_TLV_CFG_END_T,
	AH_CLI_TLV_GET_INSTANCE_T,
	AH_CLI_TLV_END_INSTANCE_T,
	AH_CLI_TLV_CMD_SESS_T,
	AH_CLI_TLV_UI_REQUEST_T,
	AH_CLI_TLV_TAB_STR_T,
	AH_CLI_TLV_UI_CALLBACK_T,
	AH_CLI_TLV_ERR_T,
	AH_CLI_TLV_ERR_STR_T,
	AH_CLI_TLV_ERR_LEAD_SPACE_T,
	AH_CLI_TLV_EOTLV_T,
	AH_CLI_TLV_RELOGIN_T,
	AH_CLI_TLV_FILTER_T,
	AH_CLI_TLV_FILTER_STR_T,
	AH_CLI_TLV_REDIRECT_STR_T,
	AH_CLI_TLV_KEEPALIVE_T,
	AH_CLI_TLV_REFRESH_WINSIZE_T,
	AH_CLI_TLV_MAX_TVL_T,
};

enum {
	AH_CLI_HELP_REQ,
	AH_CLI_TAB_REQ,
	AH_CLI_EXEC_REQ,
	AH_CLI_LOGIN_REQ,
	AH_CLI_EXEC_FLAG_REQ,
};

/* need define type size here */

#define AH_FOREACH_TLV(tlvptr, tlvbuf, ntlvs, iter)\
	for(tlvptr = ah_first_tlv(&iter, tlvbuf, ntlvs);\
		ah_more_tlv(&iter);\
		tlvptr = ah_next_tlv(&iter))
#endif
