#!/bin/sh /etc/rc.common
START=90
STOP=20

SERVICE_DAEMONIZE=1
#SERVICE_WRITE_PID=1
#SERVICE_USE_PID=1
SERVICE_STOP_TIME=3

start () {
    service_start /lib/okos/handle_cloud.sh
}

stop () {
    service_stop /lib/okos/handle_cloud.sh
    killall -9 handle_cloud.sh
    killall -9 wget
}


