#!/bin/sh /etc/rc.common

START=20
STOP=90

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start() {
	stop
	[ -e /proc/sys/kernel/core_pattern ] && {
		ulimit -c unlimited
		echo '/tmp/%e.%p.%s.%t.core' > /proc/sys/kernel/core_pattern
	}
	service_start /sbin/netifd

	setup_switch() { return 0; }

	include /lib/network
	setup_switch

	sleep 5

	/sbin/wifi down
    sleep 1
    /sbin/wifi up

}

restart() {
	ifdown -a
	start
}

shutdown() {
	ifdown -a
	stop
}

stop() {
	/sbin/wifi down
    sleep 1
	service_stop /sbin/netifd
}

reload() {
	ubus call network reload
    sleep 5
	/sbin/wifi down
    sleep 1
	/sbin/wifi up
}
