#!/bin/sh /etc/rc.common
START=90

SERVICE_DAEMONIZE=1
#SERVICE_WRITE_PID=1
#SERVICE_USE_PID=1
SERVICE_STOP_TIME=3

start () {
    service_start /lib/okos/okos_mgr.py
}

stop () {
    service_stop /lib/okos/okos_mgr.py
}


