#!/bin/sh /etc/rc.common

START=99


stop ()
{
    pid=`pgrep -f "wget -c $imgurl"`
    [ -n "$pid" ] &&  kill $pid
}


start ()
{
    [ -f "/overlay/root/imgurl" ] && { 
        imgurl="`cat /overlay/root/imgurl`"
        dd if=/dev/zero of=/overlay/root/dump count=1 bs=128k conv=fsync
        (sleep 120;wget -c "$imgurl" -O "/overlay/root/${imgurl##*/}" 2>&1 | logger -t 'predownload') & 
    }
}

