#!/bin/sh /etc/rc.common

START=99


imgurl="`cat /root/imgurl`"

stop ()
{
    pid=`pgrep -f "wget -c $imgurl"`
    [ -n "$pid" ] &&  kill -9 $pid
}


start ()
{
    [ -f "/root/imgurl" ] && { 
        dd if=/dev/zero of=/root/dump count=1 bs=128k conv=fsync
        (sleep 600;wget -c "$imgurl" -O "/root/${imgurl##*/}" 2>&1 | logger -t 'predownload') & 
    }
}

