#!/bin/sh /etc/rc.common
START=40

SERVICE_DAEMONIZE=1
#SERVICE_WRITE_PID=1
#SERVICE_USE_PID=1
SERVICE_STOP_TIME=3

start () {
    service_start /lib/okos/sysloader.sh
}

stop () {
    service_stop /lib/okos/sysloader.sh
    killall -9 sysloader.sh
    killall -9 aria2c
    killall -9 kexec
}


