from cfg_system import CfgSystem
from cfg_interface import CfgInterface
from cfg_network import CfgNetwork
from cfg_port_forwarding import CfgPortForwarding
from cfg_ip_forwarding import CfgIpForwarding
from cfg_mac_ip import CfgMacIpBinding
from cfg_dhcp_option import CfgDhcpOption
from cfg_done import CfgDone
from cfg_site_to_site_vpn import CfgSiteToSiteVPN
from cfg_kickoff import CfgKickoff
from cfg_ddns import CfgDDNS