LIBOBJS = ah_pthread.o\
		  ah_nptimer.o\
		  ah_ptimer.o\
		  ah_tnptimer.o \
		  ah_logutil.o \
		  ah_event_lib.o \
		  ah_event_thread.o \
		  ah_shm.o \
		  ah_sem.o \
		  ah_mpi.o


SHLIB = libok_sys.so.1.0

EXTRA_CFLAGS +=
EXTRA_LDFLAGS +=

include $(TOPDIR)/package_repos/build/okpost.mk
