#!/bin/sh

LOG_MERG=0
LOG_NOTICE=4
LOG_WARNING=5
LOG_INFO=6
LOG_DEBUG=7
log ()
{
    local pri=$1
    shift 1
    echo "$@" | logger -t qosscript -p $pri
}
run ()
{
    local cmd=$1
    echo "==> ${cmd}" | logger -t qosscript -p 8
    [ -z "$debug" ] && $cmd
}
qos_trap ()
{
    log $LOG_DEBUG "QoS Trapped."
    lock -u /var/run/qos.lock
}

lock /var/run/qos.lock
trap 'qos_trap; exit' INT TERM ABRT QUIT ALRM

#debug=True
QDISC="htb"
#QDISC="hfsc"

id_file="/tmp/qos_client_id"
id_base=100
arp_db="/tmp/arptables.db"
sta_db="/tmp/stationinfo.db"
#arp_file="/proc/net/arp"

if [ ! -z "$debug" ]; then
    ifaces="ath00 ath10 ath01 ath11 eth0"
else
    ifaces="`ifconfig | awk '/ath/{print $1}'` eth0"
fi
[ ! -z "$debug" ] && echo "interfaces: $ifaces "

FULL_SPEED_eth0="500000"

#generate_id ()
#{
#    [ ! -f $id_file ] && echo >&2 "$id_flie is absent, create new one." &&  touch $id_file
#
#    local seq=`cat $id_file`
#    local id=100
#    for n in $seq; do
#        for m in $seq; do
#            if [ $id -eq $m ]; then
#                id=$(( id + 1 ))
#                break
#            fi
#        done
#    done
#    seq="$seq $id"
#    echo $seq > $id_file
#    echo "$id"
#}

#####################################################
# Format of ID file: /tmp/qos_client_id
# -------------------------------------------------
# MAC               IP              Interface   ID
# fc:ad:0f:06:a3:28 192.168.254.193 ath11       104
# f0:b4:29:c7:70:da 192.168.254.173 ath01       105
# f4:0f:24:2d:da:08 192.168.254.141 ath10       106
#
#####################################################

get_id ()
{
    [ ! -f $id_file ] && log $LOG_DEBUG "$id_file is absent, create new one." &&  touch $id_file
    log $LOG_DEBUG "get_id(): for $mac ."

    local mac=$1

    local ck=`grep "${mac}" ${id_file}`
    log $LOG_DEBUG "get_id(): $ck ."

    # Reture entry corresponding to given MAC.
    echo "${ck}"
}

new_id ()
{
    local mac=$1
    local ip=$2
    local ifname=$3
    log $LOG_DEBUG "new_id(): ( MAC:$mac , IP:$ip , IFNAME:$ifname )"

    local id=$id_base
    local ids=`cat $id_file | awk '{print $4}'`
    for n in $ids; do
        for m in $ids; do
            if [ $id -eq $m ]; then
                id=$(( id + 1 ))
                break
            fi
        done
    done

    echo "$mac $ip $ifname $id" >> $id_file
    log $LOG_DEBUG "new_id(): get ID:$id ."

    echo "${id}"
}

del_id ()
{
    local id=$1
    log $LOG_DEBUG "del_id(): ID:$id "
    sed -i "/ ${id}$/d" ${id_file}

    log $LOG_DEBUG "del_id(): done."
}


del_id_by_mac ()
{
    local mac=$1
    log $LOG_DEBUG "del_id_by_mac(): MAC:$mac "
    sed -i "/^${mac} /d" ${id_file}

    log $LOG_DEBUG "del_id_by_mac(): done."
}

###############################################################################
# INPUT:
#   1. MAC
#   2. ifname (optional)
# OUTPUT:
#   1. IP
#   2. ifname
#
# IP got from arptables.db which is generated by ArpWatch with VLAN, since
# ArpWatch damon is run on L3 interface corresponding to each VLAN bridge.
# How to get VLAN ID?
#   1. if you only have client MAC, you have to query stationinfo.db. then,
#      you got vlan and ifname together.
#   2. if you have ifname, you can check uci wireless configuration by ifname.
#
###############################################################################

get_ip ()
{
    local mac=$1
    local ifname=$2
    log $LOG_DEBUG "get_ip(): MAC:$mac IFNAME:$ifname "

    local rc
    local vlan
    local ip
    if [ -z "$ifname" ]; then
        rc=`sqlite3 $sta_db "select IFNAME,VLAN from STAINFO where MAC='${mac}' COLLATE NOCASE;"`
        OIFS=$IFS;IFS='|';set -- $rc;ifname=$1;vlan=$2;IFS=$OIFS
        vlan="br-lan${vlan}"
        log $LOG_DEBUG "get_ip(): got IFNAME:$ifname and VLAN:$vlan from $sta_db ."

        [ -z "$ifname" ] && log $LOG_DEBUG "Get IFNAME from $sta_db failed." && echo "" && return 1
        [ -z "$vlan" ] && log $LOG_DEBUG "Get VLAN from $sta_db failed." && echo "" && return 1
    else
        if [ ! -z "$debug" ]; then
            rc="'lan3000'"
        else
            rc=`uci -q show wireless.${ifname}.network`
        fi
        [ -z "$rc" ] && log $LOG_DEBUG "Get IFNAME from uci failed." && echo "" && return 1
        vlan=`echo $rc | awk -F "'" '{print $2}'`
        vlan="br-${vlan}"
        log $LOG_DEBUG "get_ip(): got VLAN:$vlan by IFNAME:$ifname from uci."
    fi

    log $LOG_DEBUG "get_ip(): try to get ip by MAC:$mac and VLAN:$vlan from $arp_db ."
#    for i in 1 2 3; do
#        ip=`sqlite3 $arp_db "select IP from '${vlan}' where MAC='${mac}' COLLATE NOCASE;"`
#        [ ! -z "$ip" ] && break
#        sleep 1
#    done
    ip=`sqlite3 $arp_db "select IP from '${vlan}' where MAC='${mac}' COLLATE NOCASE;"`
    [ -z "$ip" ] && log $LOG_DEBUG "Get IP from $arp_db failed." && echo "" && return 1
    
    log $LOG_DEBUG "get_ip(): output=>IP:$ip , IFNAME:$ifname ."
    echo "${ip} ${ifname}"
    return 0
}

hfsc_add_classes ()
{
    local iface=$1
    local id=$2
    local wt=$3
    local tx=$4
    local rx=$5

    local param="parent 1:1 classid 1:$id hfsc ls m2 ${wt}00kbit ul m2"
    run "tc class add dev $iface $param $rx"
    run "tc class add dev eth0 $param $tx"

    for i in eth0 $iface; do
        run "tc qdisc add dev $i parent 1:$id handle ${id}: sfq perturb 10"
    done
}

htb_change_classes ()
{
    local iface=$1
    local id=$2
    local wt=$3
    local tx=$4
    local rx=$5

    local param="parent 1:1 classid 1:$id htb burst 15k rate ${wt}00kbit ceil"
    run "tc class change dev $iface $param $rx"
    run "tc class change dev eth0 $param $tx"
}

htb_add_classes ()
{
    local iface=$1
    local id=$2
    local wt=$3
    local tx=$4
    local rx=$5

    local param="parent 1:1 classid 1:$id htb burst 15k rate ${wt}00kbit ceil"
    run "tc class add dev $iface $param $rx"
    run "tc class add dev eth0 $param $tx"

    for i in eth0 $iface; do
        run "tc qdisc add dev $i parent 1:$id handle ${id}: sfq perturb 10"
    done
}

add_filters ()
{
    local iface=$1
    local ip=$2
    local id=$3
    local U32="parent 1:0 handle ::${id} protocol ip prio 1 u32"
    run "tc filter add dev $iface ${U32} match ip dst ${ip}/32 flowid 1:$id"
    run "tc filter add dev eth0 ${U32} match ip src ${ip}/32 flowid 1:$id"
}


#add_o1 ()
#{
#    # add aa:bb:cc:dd:ee:ff pri tx_up rx_up
#    # add aa:bb:cc:dd:ee:ff pri
#    local mac=$1
#    local pri=$2
#    local tx
#    [ ! -z $3 ] && tx=$3 || tx=$FULL_SPEED_eth0
#    [ $tx -eq 0 ] && tx=$FULL_SPEED_eth0
#    tx="${tx}kbit"
#    local rx
#    [ ! -z $4 ] && rx=$4 || rx=$FULL_SPEED_eth0
#    [ $rx -eq 0 ] && rx=$FULL_SPEED_eth0
#    rx="${rx}kbit"
#    local ifname=$5
#
#    local rc
#    local ip
#    local ip2
#    local ifname2
#    local id
#    local id2
#
#    log $LOG_INFO "Add client [${mac}] on <${ifname}> with priority $pri and limitation TX/RX [${tx}/${rx}]."
#
#    rc=$( get_ip $mac $ifname )
#    log $LOG_DEBUG "get_ip()=>$rc <"
#    [ -z "$rc" ] && $LOG_WARNING "Get IP failed." && return 1
#    OIFS=$IFS;IFS=' ';set -- $rc;ip=$1;ifname=$2;IFS=$OIFS
#    log $LOG_DEBUG "Add: Get IP:$ip & IFNAME:$ifname ."
#    
#    #local id=$( generate_id )
#    rc=$( get_id $mac )
#    log $LOG_DEBUG "get_id()=>$rc <"
#    if [ ! -z "$rc" ]; then
#        OIFS=$IFS;IFS=' ';set -- $rc;_=$1;ip2=$2;ifname2=$3;id=$4;IFS=$OIFS
#        log $LOG_DEBUG "Client exists in $id_file {MAC:$mac , ID:$id , IP:$ip2 , IFNAME:$ifname2 }."
#        if [ "$ip" == "$ip2" -a "$ifname" == "$ifname2" ]; then
#            log $LOG_DEBUG "Client info(ip & ifname) in $id_file match input."
#            local id2=$( chk_hw_id_by_ip $ip )
#            log $LOG_DEBUG "chk_hw_id_by_ip()=>$id2 <search id by ip in filter."
#            if [ "$id" == "$id2" ]; then
#                log $LOG_INFO "Client ID match ID in hardware, just change the setting."
#                ${QDISC}_change_classes $ifname $id $pri $tx $rx 
#                return 0
#            else
#                log $LOG_INFO "ID got from $id_file doesn't exist in hardward."
#                log $LOG_DEBUG "Delete client in TC by ID:$id2 ."
#                del_tc_by_id_ifname $id2
#            fi
#        else
#            log $LOG_INFO "Client info dones't match $id_file "
#            log $LOG_DEBUG "Delete client in TC by $id_file info: IP:$ip2 & IFNAME:$ifname2 "
#            del_tc_by_ip_ifname $ip2 $ifname2
#        fi
#
#        log $LOG_DEBUG "Release client ID by MAC: ${mac}."
#        del_id_by_mac "$mac"
#    fi
#    
#    id=$( new_id $mac $ip $ifname )
#    log $LOG_DEBUG "Generate ID:${id} for client [${ifname}/${ip}/${mac}]."
#    ${QDISC}_add_classes $ifname $id $pri $tx $rx
#    add_filters $ifname $ip $id
#
#    log $LOG_INFO "Add client done"
#}

add ()
{
    # add aa:bb:cc:dd:ee:ff pri tx_up rx_up ifname
    local mac=$1
    local pri=$2
    local tx
    [ ! -z $3 ] && tx=$3 || tx=$FULL_SPEED_eth0
    [ $tx -eq 0 ] && tx=$FULL_SPEED_eth0
    tx="${tx}kbit"
    local rx
    [ ! -z $4 ] && rx=$4 || rx=$FULL_SPEED_eth0
    [ $rx -eq 0 ] && rx=$FULL_SPEED_eth0
    rx="${rx}kbit"
    local ifname=$5

    local rc
    local ip
    local id

    log $LOG_INFO "Add client [${mac}] on <${ifname}> with priority $pri and limitation TX/RX [${tx}/${rx}]."

    log $LOG_DEBUG "Del client by ${mac}."
    del $mac

    rc=$( get_ip $mac $ifname )
    log $LOG_DEBUG "get_ip()=>$rc <"
    [ -z "$rc" ] && $LOG_WARNING "Get IP failed and exit." && return 1
    OIFS=$IFS;IFS=' ';set -- $rc;ip=$1;ifname=$2;IFS=$OIFS
    log $LOG_DEBUG "Add: Get IP:$ip & IFNAME:$ifname ."
    
    id=$( new_id $mac $ip $ifname )
    log $LOG_DEBUG "Generate ID:${id} for client [${ifname}/${ip}/${mac}]."
    ${QDISC}_add_classes $ifname $id $pri $tx $rx
    add_filters $ifname $ip $id

    log $LOG_INFO "Add client done"
}

chk_hw_id_by_ip ()
{
    local ip=$1
    log $LOG_DEBUG "chk_hw_id_by_ip(): for IP:$ip "

    local _ip_16_=$(for i in $(echo ${ip} | tr '.' ' '); do printf "%02x" $i; done)
    local id
    
    if [ ! -z "$debug" ]; then
        id=100
    else
        id=`tc filter show dev eth0 | grep -B 1 -i "$_ip_16_" | grep "fh" | awk '{print $10}' | awk -F ':' '{print $3}'`
    fi

    log $LOG_DEBUG "chk_hw_id_by_ip()=> get id:$id "
    echo "${id}"
}


del_tc_by_id_ifname ()
{
    local id=$1
    local ifname=$2
    log $LOG_DEBUG "del_tc_by_id_ifname(): ID:$id IFNAME:$ifname "

    log $LOG_DEBUG "Delete filter to class ${id}."
    for iface in eth0 $ifname; do
        run "tc filter del dev $iface handle 800::${id} prio 1 protocol ip u32"
    done

    log $LOG_DEBUG "Delete class for client [${id}]."
    for iface in eth0 $ifname; do
        run "tc class del dev $iface classid 1:${id}"
    done

    log $LOG_DEBUG "del_tc_by_id_ifname(): done."
}

del_tc_by_ip_ifname ()
{
    local ip=$1
    local ifname=$2
    log $LOG_DEBUG "del_tc_by_ip_ifname(): IP:$ip IFNAME:$ifname "

    local id=$( chk_hw_id_by_ip $ip )
    log $LOG_DEBUG "del_tc_by_ip_ifname(): get ID:$id from chk_hw_id_by_ip( $ip )."


    log $LOG_DEBUG "Delete client by ID:$id IFNAME:$ifname "
    del_tc_by_id_ifname $id $ifname
    log $LOG_DEBUG "del_tc_by_ip_ifname(): done."
}

#del_o1 ()
#{
#    local mac=$1
#    local ifname=$2
#    log $LOG_DEBUG "Del: $@ ."
#    local ip2
#    local ifname2
#    local ip3
#    local ifname3
#    local rc2
#    local rc3
#
#    rc2=$( get_id $mac )
#    if [ ! -z "$rc2" ]; then
#        OIFS=$IFS;IFS=' ';set -- $rc2;_=$1;ip2=$2;ifname2=$3;id=$4;IFS=$OIFS
#        log $LOG_DEBUG "Del(): get_id( $mac ) => IP:$ip2 IFNAME:$ifname2 ID:$id ."
#    fi
#    rc3=$( get_ip $mac $ifname )
#    if [ ! -z "$rc3" ]; then
#        OIFS=$IFS;IFS=' ';set -- $rc3;ip3=$1;ifname3=$2;IFS=$OIFS
#        log $LOG_DEBUG "Del(): get_ip( $mac , $ifname ) => IP:$ip3 IFNAME:$ifname3 ."
#    fi
#
#    if [ -z "$rc2" -a -z "$rc3" ]; then
#        log $LOG_DEBUG "Don't know how to delet $mac on interface $iface ."
#    elif [ ! -z "$rc2" -a -z "$rc3" ]; then
#        del_tc_by_id_ifname $id $ifname2
#    elif [ ! -z "$rc3" -a -z "$rc2" ]; then
#        del_tc_by_ip_ifname $ip3 $ifname3
#    elif [ "$ip2" == "$ip3" -a "$ifname2" == "$ifname3" ]; then
#        del_tc_by_id_ifname $id $ifname2
#    else
#        del_tc_by_ip_ifname $ip2 $ifname2
#    fi
#
#    log $LOG_DEBUG "Release client ID by MAC: ${mac}."
#    del_id_by_mac "$mac"
#
#    log $LOG_DEBUG "Del(): done."
#}

del ()
{
    local mac=$1
    local ifname=$2
    log $LOG_DEBUG "Del: $@ ."

    local rc2
    local ip2
    local ifname2
    local id2

    rc2=$( get_id $mac )
    if [ ! -z "$rc2" ]; then
        OIFS=$IFS;IFS=' ';set -- $rc2;_=$1;ip2=$2;ifname2=$3;id2=$4;IFS=$OIFS
        log $LOG_DEBUG "Del(): get_id( $mac ) => IP:$ip2 IFNAME:$ifname2 ID:$id2 ."
    fi

    if [ -z "$rc2" ]; then
        log $LOG_DEBUG "Don't know how to delet $mac on interface $iface ."
    else
        del_tc_by_id_ifname $id2 $ifname2
    fi

    log $LOG_DEBUG "Release client ID by MAC: ${mac}."
    del_id_by_mac "$mac"

    log $LOG_DEBUG "Del(): done."
}

hfsc_start_iface ()
{
    local _iface_=$1
    local _speed_=${2}bit
    run "tc qdisc add dev $_iface_ root handle 1: hfsc default 30"
    run "tc class add dev $_iface_ parent 1: classid 1:1 hfsc ls m2 $_speed_"
    run "tc class add dev $_iface_ parent 1:1 classid 1:30 hfsc ls m2 100kbps ul m2 $_speed_"
    run "tc qdisc add dev $_iface_ parent 1:30 handle 30: sfq perturb 10"
}

htb_start_iface ()
{
    local _iface_=$1
    local _speed_="${2}bit"
    run "tc qdisc add dev $_iface_ root handle 1: htb default 30"
    run "tc class add dev $_iface_ parent 1: classid 1:1 htb rate $_speed_ burst 150k"
    run "tc class add dev $_iface_ parent 1:1 classid 1:30 htb rate 1kbit ceil $_speed_ burst 15k"
    run "tc qdisc add dev $_iface_ parent 1:30 handle 30: sfq perturb 10"
}

thtb_start_iface ()
{
    local _iface_=$1
    local _speed_=$2
    run "tc qdisc add dev $_iface_ root handle 10: htb default 30"
    run "tc class add dev $_iface_ parent 10: classid 10:1 htb rate $_speed_ burst 150k"
    run "tc class add dev $_iface_ parent 10:1 classid 10:30 htb rate 1kbit ceil $_speed_ burst 15k"
    run "tc qdisc add dev $_iface_ parent 10:1 handle 1: htb default 30"
    run "tc class add dev $_iface_ parent 1: classid 1:1 htb rate $_speed_ burst 150k"
    run "tc class add dev $_iface_ parent 1:1 classid 1:30 htb rate 1kbit ceil $_speed_ burst 15k"
}


start ()
{
    log $LOG_INFO "Kickoff QoS service now."
    log $LOG_DEBUG "Touch $id_file for restoring client ID infor."
    touch $id_file

    log $LOG_DEBUG "Install $QDISC qdisc and root class."
    local full_speed
    for iface in $ifaces; do
        case "$iface" in
            ath0*)
                full_speed=100m
                ;;
            ath1*)
                full_speed=500m
                ;;
            *)
                full_speed=900m
                ;;
        esac
        #echo $iface $full_speed
        ${QDISC}_start_iface $iface $full_speed
    done

    log $LOG_INFO "QoS service done."
}


stop ()
{
    log $LOG_INFO "Stop QoS service now."

    log $LOG_INFO "1. Remove filter for client."
    for iface in $ifaces; do
        run "tc filter del dev $iface parent 1: protocol ip prio 1 u32"
    done

    log $LOG_INFO "2. Remove qdisc and all the classes."
    for iface in $ifaces; do
        run "tc qdisc del dev $iface root"
    done

    log $LOG_DEBUG "Client id file $id_file removed."
    rm $id_file
    log $LOG_INFO "QoS service finished."
}

show ()
{
    for iface in $ifaces; do
        echo "<${iface}>:"
        tc qdisc show dev $iface
        tc class show dev $iface
        tc filter show dev $iface
    done
    
}

case "$1" in
    start)
        shift 1
        start $@
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    show)
        show
        ;;
    add)
        if [ $# -ne 3 -a $# -ne 5 -a $# -ne 6 ]; then
            echo "Usage:"
            echo "    add xx:xx:xx:xx:xx:xx priority"
            echo "    add xx:xx:xx:xx:xx:xx priority tx_up rx_up"
            echo "    add xx:xx:xx:xx:xx:xx priority tx_up rx_up athXX"
            exit 1
        fi
        shift 1
        add $@
        ;;
    del)
        shift 1
        [ -z $1 ] && echo "Usage: del xx:xx:xx:xx:xx:xx [athxx] " && exit 1
        del $@
        ;;
    *)
        echo "Usage: $0 [restart|start|stop|add|del|show]"
        exit 1
        ;;
esac

lock -u /var/run/qos.lock
